### ISSUE TITLE
Saved image is gren

### ISSUE THREAD

**Issue by yoyoy** [oliver-moran/jimp#1]
Hello,
I try to use your ib with a large jpg file but the saved file is totally green (#008700) ...
do you have ane idea ? 
thanks

**Comment by yoyoy** [comment]
hello
i've uploaded again an image that cause the problem
http://dropcanvas.com/jti5x
24bit 96ppp image

my code is quite simple
var monimgresize = new Jimp(targetFileUpload, function () {
	this.resize(neww, newh).write(targetFileUpload); // save again
});
with neww and newh in scalled to the original (so 2000x1498)

if you have an idea you can save me ;)
thanks a lot

**Comment by yoyoy** [comment]
exifs datas of this image

<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.0-c061 64.140949, 2010/12/07-10:57:01        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/">
         <xmpMM:DocumentID>8B4B99099444A7275B7EECED9F2E31FD</xmpMM:DocumentID>
         <xmpMM:InstanceID>8B4B99099444A7275B7EECED9F2E31FD</xmpMM:InstanceID>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:dc="http://purl.org/dc/elements/1.1/">
         <dc:format>image/jpeg</dc:format>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">
         <photoshop:ColorMode>3</photoshop:ColorMode>
         <photoshop:ICCProfile>sRGB IEC61966-2.1</photoshop:ICCProfile>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
         <tiff:ImageWidth>1558</tiff:ImageWidth>
         <tiff:ImageLength>2079</tiff:ImageLength>
         <tiff:BitsPerSample>
            <rdf:Seq>
               <rdf:li>8</rdf:li>
               <rdf:li>8</rdf:li>
               <rdf:li>8</rdf:li>
            </rdf:Seq>
         </tiff:BitsPerSample>
         <tiff:PhotometricInterpretation>2</tiff:PhotometricInterpretation>
         <tiff:SamplesPerPixel>3</tiff:SamplesPerPixel>
         <tiff:XResolution>72/1</tiff:XResolution>
         <tiff:YResolution>72/1</tiff:YResolution>
         <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:exif="http://ns.adobe.com/exif/1.0/">
         <exif:ExifVersion>0221</exif:ExifVersion>
         <exif:ColorSpace>1</exif:ColorSpace>
         <exif:PixelXDimension>1558</exif:PixelXDimension>
         <exif:PixelYDimension>2079</exif:PixelYDimension>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:xmp="http://ns.adobe.com/xap/1.0/">
         <xmp:CreateDate>2015-01-05T18:28:42+01:00</xmp:CreateDate>
         <xmp:ModifyDate>2014-05-27T09:46:15+02:00</xmp:ModifyDate>
         <xmp:MetadataDate>2014-05-27T09:46:15+02:00</xmp:MetadataDate>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>
                         
<?xpacket end="w"?>

**Comment by yoyoy** [comment]
i've made another test
open in photoshop
modified the size
saved for the web
and the result is different... but always bugged
check here
http://dropcanvas.com/7mu2a

**Comment by charafsalmi** [comment]
I confirm this issue with a simple jpeg image.
```javascript
        var jimp = new Jimp(newFile, function() {
          this.scale(0.9);
          this.quality(100);
          this.write(newFile, function() {
            reply();
          })
        });
```

![dinar_n_dirham_3](https://cloud.githubusercontent.com/assets/278809/5641116/1e3ef41e-9632-11e4-93d8-d84e578f0add.jpg)
![dinar_n_dirham_3](https://cloud.githubusercontent.com/assets/278809/5641095/a11e41ec-9631-11e4-9428-e159d360ae98.jpg)

**Comment by yoyoy** [comment]
hi @charafsalmi
did you know another library to do that without installing imagemagik or other external tool ? 
thanks

**Comment by yoyoy** [comment]
hi ! 
i've found the (fu****g) solution ... 
just Math.round your size .... 
no comment :'(

**Comment by charafsalmi** [comment]
Nope. I don't know any other one.
What do you mean by "just Math.round your size .... ", could you give an example ?
Thanks.

**Comment by charafsalmi** [comment]
i've did a pull request for this =)
https://github.com/oliver-moran/jimp/pull/4

**Comment by yoyoy** [comment]
right ;) 
so you understood ;)

**Comment by oliver-moran** [comment]
That's great, guys. Thanks so much for this. I've pulled the solution in.
