### ISSUE TITLE
Move test assets to somewhere else to reduce clone/install time

### ISSUE THREAD

**Issue by xlc** [oliver-moran/jimp#101]
Most people don't need them but git clone will download all the images regardless. It is better to move the test assets to a different repo and add it as submodule so people can still fetch them easily if they want to run tests. You can even update the submodule in the tests.sh script.

**Comment by arminrosu** [comment]
I would just delete most of them. There are almost 400MB in that folder, most of which in _test/samples/original_ (322MB).

As far as I can tell, _test/phash.js_ is the only test that requires _test/samples/_ images. I think 400MB is excessive for testing phash.

**Comment by oliver-moran** [comment]
Thanks. I've taken the `phash` test out. We can review tests at some later point.
