### ISSUE TITLE
Error: Could not find MIME for Buffer <null>

### ISSUE THREAD

**Issue by Grayseon** [oliver-moran/jimp#1027]
# Expected Behavior

Jimp reads the local png file.

# Current Behavior

It errors when running it.

# Failure Information (for bugs)

When I run it, it gives this error:
![image](https://user-images.githubusercontent.com/86214551/125697490-5efaee27-ce56-413f-ba18-53d756897db6.png)
I can still run the program if I just require Jimp, but if I use Jimp.read() then it errors.
My code:
![image](https://user-images.githubusercontent.com/86214551/125697625-c6959d36-177d-4cb6-bda2-7ffba8bb587e.png)

## Steps to Reproduce

The image is just plain white, and it is a local file named white.png
![image](https://user-images.githubusercontent.com/86214551/125697740-bef89ed8-42ca-4658-a955-9c2589cd4673.png)

1. install Jimp (I did --save by the way)
2. put this in the index.js: 
var Jimp = require('jimp');
 
// open a file called "lenna.png"
Jimp.read('white.png', (err, lenna) => {
  if (err) throw err;
  lenna
    .resize(256, 256) // resize
    .quality(60) // set JPEG quality
    .greyscale() // set greyscale
    .write('white.jpg'); // save
});
3. run index.js (node index.js)

## Context

I am making a minecraft challenge for me and my friends where every block is white, but just has the name of the block on it in black text.

- Jimp Version: 0.16.1
- Operating System: Windows 10 Desktop x64
- Node version: 12.18.4

## Failure Logs
![image](https://user-images.githubusercontent.com/86214551/125697490-5efaee27-ce56-413f-ba18-53d756897db6.png)

**Comment by mikakaraila** [comment]
One extra note, I got same error as multiple other Windows programs had same png file open. 
Error could be caused by file sharing access rights?

**Comment by Grayseon** [comment]
Did it work when you closed all of the programs?

**Comment by mikakaraila** [comment]
Yes, after closing other programs it doesn't complain anything.

**Comment by Grayseon** [comment]
I'm still getting the error after closing out any viewers or editors.

**Comment by mikakaraila** [comment]
Hmm, I still expect it has something related to File share like here: https://stackoverflow.com/questions/7007671/file-open-for-read-access-denied-on-executing-file-in-windows/7007790#7007790

**Comment by mikakaraila** [comment]
I found another case from my code. After image.write("filename") trying to image2.read("filename") seems to fail because file is not yet flushed/closed by operating system. 
I change code to clone() image and no more error "Error: Could not find MIME for Buffer <null>"

**Comment by Grayseon** [comment]
Thank you for your help!
