### ISSUE TITLE
Error: Invalid format: 25963

### ISSUE THREAD

**Issue by fabiusss** [oliver-moran/jimp#103]
C:\Users\xxx\Documents\progetto\node_modules\exif-parser\lib\exif.js:38
                        throw new Error('Invalid format: ' + format);
                              ^

Here's the file that causes the error
https://drive.google.com/file/d/0B3j26P1F54BCTllpMF9fa0FfSDA/view?usp=sharing

**Comment by arminrosu** [comment]
The error is generated by another node module, you should open an issue on [node-mime](https://github.com/broofa/node-mime).

I managed to reproduce the error, but couldn't find a fix. Exif isn't my specialty. In the meantime, run your images through [pyExifToolGUI](https://hvdwolf.github.io/pyExifToolGUI/) to fix the broken exif, without losing it.

@oliver-moran I propose you close this issue.

**Comment by oliver-moran** [comment]
Thanks, @arminrosu. Closing issue.
