### ISSUE TITLE
Size of image after processing

### ISSUE THREAD

**Issue by alokrajiv** [oliver-moran/jimp#107]
Is it possible to get the file or image size after processing. If the output is a buffer and I need to store to azure or s3 i require to know the total content length. GraphicsMagick gives a filesize function. is there something like that in jimp?

**Comment by arminrosu** [comment]
Is [Buffer.length](https://nodejs.org/api/buffer.html#buffer_buf_length) giving you the wrong filesize? e.g.

```js
image.getBuffer(jimp.MIME_PNG, function(error, buffer) {
    console.log(buffer.length);
});
```

**Comment by alokrajiv** [comment]
@arminrosu  but buffer size will not necessarily be the file size. It could be smaller or larger. For.ex If it is a big file, the buffer could be smaller. Write now I am making a stream and passing the stream through a counter function as a work-around to get length.

**Comment by arminrosu** [comment]
Hmmm, I didn't know that, thanks :)

Could you add your code to jimp?

**Comment by alokrajiv** [comment]
@arminrosu I'll try. Is there any contributor-Readme.md or instructions to run the tests?

**Comment by arminrosu** [comment]
Nope, I didn't find a contributor.md.

You can run the tests with `cd test;./test.sh;`. The tests are only _checking if the respective methods run_, they don't validate the results.

**Comment by alokrajiv** [comment]
Seems so. Anyways, I'll try to add it and hope nothing breaks.

**Comment by oliver-moran** [comment]
Hi, sorry for the delay getting back to you. Very busy IRR.

There's no method like that now. If you paste your method here I can add it or add it as a new method to `index.js` and I'll pull it in.

**Comment by mihaiserban** [comment]
any news on this issue? how does one get the size in bytes of the new image?

**Comment by hipstersmoothie** [comment]
@mihaiserban you can just do this to get the byte length of the buffer

```js
Jimp.read('./exampleImages/dice.png').then(image => {
   image.write('test.png').toBuffer(Jimp.AUTO, (err, buffer) => {
      console.log(buffer.byteLength) // size of buffer in bytes
   })
});

```
