### ISSUE TITLE
creating new image with default background image 

### ISSUE THREAD

**Issue by majdkilou** [oliver-moran/jimp#1078]
Hello guys, 
is there anyway to set the background layer from input image file when creating a new image ? 

const modifyFrame = async (frame) => {
  let newHeight = (16 * frame.bitmap.width) / 9;
  newHeight = newHeight % 2 === 0 ? newHeight : newHeight + 1;

  // Create new image width current width, new height and white background
  const newImage = new Jimp(frame.bitmap.width, newHeight, "white";

  const font = await Jimp.loadFont(Jimp.FONT_SANS_64_BLACK);
  newImage.print(font, 20, newImage.bitmap.height - 100, "Life Inside");

  // Center the video in the current 9:16 image
  newImage.composite(frame, 0, newHeight / 2 - frame.bitmap.height / 2);

  return newImage;

**Comment by joelcoronah** [comment]
hi, any update?
