### ISSUE TITLE
Setting pixel colours in a loop does not work.

### ISSUE THREAD

**Issue by SirCameron** [oliver-moran/jimp#1098]
# Expected Behavior

setting pixels in a loop actually set the pixels

# Current Behavior

pixel colours are not set. image is black.

## Steps to Reproduce

```
new Jimp(200, 200, (error, image) => {
  for (let f = 100; f < 10; f++) {
    image.setPixelColor(0xff00ffff, f, 100);
  }
  image.writeAsync("./test.jpg");
})
```

## Context

- Jimp Version: ^0.16.1
- Operating System: mac os 12.4
- Node version: ts-node ^10.9.1, node 16.13.2

**Comment by SirCameron** [comment]
sorry, yes, that demo code is wrong. I wrote that here quickly as a demonstration.
My code, which has the correct parameters doesn't work, though.

I'm iterating through some images and creating one interlaced image of them (vertical lenticular).
```
new Jimp(widthPixels, heightPixels, async (error, destinationImage) => {
  sourceImages.forEach(async (sourceImage, index) => {
    const image = await Jimp.read(sourceImage);

    for (let x = index; x < widthPixels; x += sourceImages.length) {
      for (let y = 0; y < heightPixels; y++) {
        const color = image.getPixelColor(x, y);
        destinationImage.setPixelColor(color, x, y);
      }
    }
  });
  ```
  
  This produces a black image.

**Comment by justin-m-lacy** [comment]
array.forEach() is an asynchronous function which returns immediately. It does not matter that the individual function calls are asynchronous, control within the function passes immediately to destinationImagr.writeAsync()

Now there is a race condition that depends on the javascript interpreter.
Very unlikely any pixels will be read and written before the write.

For reference:
https://stackoverflow.com/questions/37576685/using-async-await-with-a-foreach-loop

**Comment by SirCameron** [comment]
@justin-m-lacy thanks for that. Then this is my bad - stupid mistake. I'll rework the asynchronisity of it.
