### ISSUE TITLE
Blit opacity

### ISSUE THREAD

**Issue by csysmans** [oliver-moran/jimp#117]
Hi!

When i create a new image (new Jimp(w, h, 0xFFFFFF... ) and I read and add an image (using blit), the transparency of the image is ignored. Is this a bug, or is there something wrong with the code below?

```
           new Jimp(size.width, size.height, 0xFFFFFFFF, function (err, image) {
               if(err){
			    	cb(err);
			    } else {
			    	Jimp.read(logoPath, function(err, logo){			    		
					logo.resize(width, height).rgba(true);
					image.rgba(true).blit(logo, x, y).write(outputPath);

					cb();
				}).catch(function(err){
					cb(err);
				});
			    }
			});
```

**Comment by csysmans** [comment]
Side note:
logoPath points to a PNG file with a transparent background.

**Comment by oliver-moran** [comment]
I suspect the method you want is `composite`. It works the same way as `blit` but rather than blowing away the original images pixels the new pixels are composited over the original image.

Can you try again with `composite` and let me know how you get on? Thanks.

**Comment by csysmans** [comment]
Yes that works great. Thanks!

**Comment by csysmans** [comment]
One follow-up question:

We are experiencing pixelated edges when resizing (which we do not have when resizing with photoshop). Can this be fixed using the different interpolation methods, or is there an antialiasing option available?

**Comment by csysmans** [comment]
Actually, the problem is more the discolouration on the edges.

Original:
![itunesartwork 2x](https://cloud.githubusercontent.com/assets/13849181/14326657/45d455f0-fc2f-11e5-956f-c82f34bdf0e6.png)

Resized:
![icon-watch-40 2x](https://cloud.githubusercontent.com/assets/13849181/14326666/50c0a46e-fc2f-11e5-9165-8edbb7806960.png)

I've tried all the resize modes, and the problem remains.
(If you zoom your browser, you'll see that the edges look really bad)

**Comment by oliver-moran** [comment]
This is probably solved using a different resize method. Those methods haven't been published yet but you can take them off the unstable master branch. Please let me know if it works.
