### ISSUE TITLE
How to merge two images together?

### ISSUE THREAD

**Issue by robertleeplummerjr** [oliver-moran/jimp#12]
I need to be able to merge more than one image together using web workers.  How can I do that with your lib.

**Comment by oliver-moran** [comment]
Hi, Robert. Interesting case. Definitely possible and probably a very easy function to write.

Describe what you mean by "merge" though. Do you mean to superimpose one on top of another?

**Comment by robertleeplummerjr** [comment]
Imagine a have a base image, a canvas, and I have two points I want to put
on it.  The issue is with leaflet.js and the amount of elements it draws.
I want to use the web worker to process those images and return a single or
a small amount of elements on the fly.  The closest ones to the center of
the viewport first, and then those outside of it, somewhat like target
rings.

On Thu, Feb 12, 2015 at 5:43 PM, Oliver Moran <notifications@github.com>
wrote:

> Hi, Robert. Interesting case. Definitely possible and probably a very easy
> function to write.
>
> Describe what you mean by "merge" though. Do you mean to superimpose one
> on top of another?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/oliver-moran/jimp/issues/12#issuecomment-74169662>.
>



-- 
Robert Plummer

**Comment by robertleeplummerjr** [comment]
Any thoughts?

**Comment by oliver-moran** [comment]
Robert, sorry for the hold up. If it's not too late, I think this will solve your issue:

https://github.com/oliver-moran/jimp/pull/15
