### ISSUE TITLE
All images made on Windows have size 0

### ISSUE THREAD

**Issue by simonh1000** [oliver-moran/jimp#126]
I use this snippets
```
        return jimp.read(srcFileName)
            .then( img => {
                img
                .resize(width, jimp.AUTO)
                .quality(75)                 // set JPEG quality
                .write(destFileName);

                returnObj.fname = destFileName;
                console.log("Created new image:", srcFileName);

                return resolve(returnObj);
            })
            .catch (err => reject(err) );
```
the files are being created but have size 0 bytes in Win 10. All working on Ubuntu though. What could be wrong?

**Comment by oliver-moran** [comment]
Hmmm ... sorry for being so slow getting back. Is this issue still presenting?

**Comment by oliver-moran** [comment]
Can't reproduce on Windows 7 using the following test script:

```js
var Jimp = require("jimp");

Jimp.read("lenna.png").then( img => {
	img
	.resize(100, Jimp.AUTO)
	.quality(75)
	.write("lenna-100px.png");
})
.catch (err => reject(err) );
```

Does it still present on Windows 10?

**Comment by simonh1000** [comment]
I'll close as I have shipped code, so I think it must have fixed itself

**Comment by bckr75** [comment]
This is still NOT FIXED, Jimp still saves 0 bytes images. Using Windows 10 Pro 1909. Simply reading resizing and saving. Trying to save img anytime in code causes 0 bytes images being saved.

**Comment by bckr75** [comment]
> I'll close as I have shipped code, so I think it must have fixed itself

Nope it's obviously not

**Comment by Umopepisdn** [comment]
I'm seeing this too, but only in my production app, not my module tester...

**Comment by andrewrproper** [comment]
I found an interesting situation. If I use image.write("filename.jpg") from within an async function, then it doesn't complete, even if I use await.

The fix is to use the Async version every time it is being called from within any async process:
image.writeAsync("filename.jpg");
I think I'll probably only use writeAsync going forward. The other one was creating strange problems, when used within async and Promises.
