### ISSUE TITLE
Error installing jimp, 'node-zlib-backport error'

### ISSUE THREAD

**Issue by mirkomilova10** [oliver-moran/jimp#129]
So, for some reason, out of the blue my nodejs refuses to work as it should. when i run `npm insall jimp` i get a node-gyp error on the module node-zlib-backport used by the dependency pngjs. it returns an error when compiling the source giving a `Users/mirko/.node-gyp/5.11.0/include/node/node_internals.h:6:10: fatal error: 'util-inl.h' file not found
#include "util-inl.h"` error.

Heres the (almost) full terminal log. i know this might not be jimp's problem but i wonder if anyone experienced it before:

```
node-zlib-backport@0.11.15 install /Users/mirko/seriesrocketNotifierApp/node_modules/node-zlib-backport
> node-gyp rebuild

  CXX(target) Release/obj.target/zlib/src/node_zlib.o
In file included from ../src/node_zlib.cc:32:
/Users/mirko/.node-gyp/5.11.0/include/node/node_internals.h:6:10: fatal error: 'util-inl.h' file not found
#include "util-inl.h"
         ^
1 error generated.
make: *** [Release/obj.target/zlib/src/node_zlib.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mirko/seriesrocketNotifierApp/node_modules/node-zlib-backport
gyp ERR! node -v v5.11.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:node-zlib-backport@0.11.15 node-zlib-backport@0.11.15 install: `node-gyp rebuild`
npm WARN install:node-zlib-backport@0.11.15 Exit status 1
```

Running on OS X with node 5.11.0 and npm 3.8.6

**Comment by oliver-moran** [comment]
Thanks! Looks like a problem with the latest version of `pngjs`. The previous version is still good. I'll do an emergency release tonight.

**Comment by malexdev** [comment]
@oliver-moran getting this as well, thanks so much for the quick response! 😀

**Comment by mirkomilova10** [comment]
Yeah, thanks for the super quick response, hope it will not cause anymore problems

**Comment by oliver-moran** [comment]
OK. I did an emergency release just now. (Even though it broke the browserify version by doing so.)

Can you guys check that all is OK again? Thanks.

**Comment by rjw209** [comment]
Non-transpiled arrow function in https://github.com/oliver-moran/jimp/blob/a6a4bfad75dec7595c8f9e05e717e00dd174c4b7/index.js#L1169

**Comment by Igor1201** [comment]
@lukeapage just updated `pngjs` to 2.3.1

**Comment by lukeapage** [comment]
Sorry about this - it is a bug in npm - I should be able to add an optional dependency without breaking peoples builds, but nevermind, the dependency is removed.

**Comment by manikmi** [comment]
It stopped working with my nodejs version. (I think node compatability is the reason) my nodejs version is 0.12.9. It gives the error with histogram method (ln 1169) in index.js for => notation.
Do we have a version which can work with node 0.12.9?

**Comment by mirkomilova10** [comment]
Now it executes npm install with no problems but it seems that it doesn't work. Have an app that fetches a remote image and then it saves it locally, with a mask applied, but it doesn't seem to work. the function gets called but nothing happenes. heres the function if it can help

```javascript
var imgSet				= function( Url, c )
{
	console.log("imgSet");
	var Immagine = Jimp.read( Url ).catch( function( e ){
		throw e;
	});
	
	var Maschera = Jimp.read( Path.join( __dirname, '/data/media/images/mask.png' ) ).catch( function( e ){
		throw e;
	});
	
	Promise.all( [ Immagine, Maschera ] ).then( function( Immagini )
	{
		var ImmagineProfilo = Immagini[0];
		var ImmagineMaschera = Immagini[1];
		
		ImmagineProfilo.resize( 512, 512 ).mask( ImmagineMaschera, 0, 0 ).resize( 80, 80 ).write( Path.join( __dirname, '/data/media/images/iconProfile@2x.png' ) );		
		ImmagineProfilo.resize( 512, 512 ).mask( ImmagineMaschera, 0, 0 ).resize( 40, 40 ).write( Path.join( __dirname, '/data/media/images/iconProfile.png' ), function( e ){
		
			c( NativeImage.createFromPath( Path.join( __dirname, '/data/media/images/iconProfile.png' ) ) );
			
		});
		
	});
	
};
```

**Comment by malexdev** [comment]
@oliver-moran Works perfectly on Node 5.11 for me. Thanks again!

**Comment by rjw209** [comment]
@oliver-moran per @manikmi and my comment above, there's an ES6 arrow function that breaks compatibility with older versions of node. @Igor1201 PR#130 includes a fix for this, but not sure when you plan to merge/release that work.

**Comment by Igor1201** [comment]
we should just fix this threading arrow problem on master, because my PR is supposed to do other things as well

**Comment by oliver-moran** [comment]
Just checking, any of these issues still presenting?

**Comment by malexdev** [comment]
Ever since I upgraded the project that uses this to node 5.11 I haven't been having any issues. 


Alex






On Tue, Jul 26, 2016 at 4:53 PM -0500, "Oliver Moran" <notifications@github.com> wrote:












Just checking, any of these issues still presenting?

**Comment by mirkomilova10** [comment]
Issue can be closed, it's safe to say that it's fixed now 👍

**Comment by oliver-moran** [comment]
Happy days! Thank you!
