### ISSUE TITLE
Blend mode argument for composite()

### ISSUE THREAD

**Issue by positlabs** [oliver-moran/jimp#139]
It would be nice to be able to blend images together instead of just straight pixel-copy compositing.

e.g. `image.composite( src, x, y, blendMode );`

`blendMode` could be `screen`, `multiply`, `overlay`, etc.

https://en.wikipedia.org/wiki/Blend_modes

**Comment by oliver-moran** [comment]
Nice idea. Will develop a road map and add it to that.

**Comment by renatorib** [comment]
Progress?

**Comment by skoa-h** [comment]
I'm currently implementing blendmodes.

@oliver-moran what would be you proposition for the api?
Currently composite takes the arguments  src, x, y, cb. For being downward compatible, it needs to be src, x, y, cb, blendMode.

**Comment by oliver-moran** [comment]
@skoa-h The pattern used is for overloading is that at the top of every function the arguments are inspected and it is determined what optional arguments, if any, were passed.

See the example of `Jimp.prototype.scale` in `index.js`.

**Comment by renatorib** [comment]
@skoa-h 
You can use (src, x, y, blendMode, cb) without break compatibility.
You can check if blendMode is a function, then it is a callback. Check if is string, then it is blendMode.

Well, this is my suggestion,

**Comment by renatorib** [comment]
Sorry, this whas what @oliver-moran said in his comment. 
https://github.com/oliver-moran/jimp/blob/master/index.js#L1830

**Comment by skoa-h** [comment]
Ahh yes of course, I forget about the pattern. I will implement it like that.

**Comment by skoa-h** [comment]
#191
