### ISSUE TITLE
getBuffer without MIME

### ISSUE THREAD

**Issue by thisconnect** [oliver-moran/jimp#141]
Is it possible to return the buffer without knowin the MIME?

This example works (by accessing `img._originalMime`) but I would prefer an official API
```javascript
const resize = path => {
	return readFile(path)
	.then(buffer => Jimp.read(buffer) )
	.then(img => img.resize(256, Jimp.AUTO))
	.then(img => new Promise((resolve, reject) => {  // resize does not return a promise
		img.getBuffer(img._originalMime, (err, buffer) => {
			if (err) reject(err)
			resolve(buffer)
		})
	}))
}
```

**Comment by thisconnect** [comment]
Or would you accept a PR that adds `Jimp.getOriginalMime` or just `Jimp.getMime` ?

**Comment by thisconnect** [comment]
I'd kind of prefer to completely omit the mime argument and just do `img.getBuffer((err, buffer) => {})`

**Comment by oliver-moran** [comment]
Have a few requests for a feature like this. Will do a release this week and hopefully add this to the release after.

**Comment by thisconnect** [comment]
Thanks, looking forward to it.

**Comment by oliver-moran** [comment]
OK. You can now do this using:

```js
image.getBuffer(Jimp.AUTO, (err, buffer) => {
    // do stuff with buffer
});
```

**Comment by thisconnect** [comment]
Thank you!
