### ISSUE TITLE
Jimp.read returns a promise that cannot be then'd

### ISSUE THREAD

**Issue by elliotatRetireup** [oliver-moran/jimp#149]
Jimp's then returns a promise. When I .then this promise, I get an error: 'TypeError: Cannot read property 'then' of undefined'.

I have no clue why this would be happening. Inside the .read method it very clearly returns a promise in the last line. Then when it returns to the calling line, it throws an error.

Example of what is causing the error:

    jimp.read(theFile).then(function(logo) {
    }

**Comment by crosofg** [comment]
@elliotatRetireup  How was this resolve?
