### ISSUE TITLE
getMIMEFromPath call cb two time in error case.

### ISSUE THREAD

**Issue by szk360** [oliver-moran/jimp#152]
getMIMEFromPath call cb two time in error case.

index.js line 223
// gets a MIME type of a file from the path to it
function getMIMEFromPath(path, cb) {
    ReadChunk(path, 0, 262, function (err, buffer) {
        if (err) { cb(null, ""); }
        var fileType = FileType(buffer);
        return cb && cb(null, fileType && fileType.mime || "");
    });
}

Following code work for me.

// gets a MIME type of a file from the path to it
function getMIMEFromPath(path, cb) {
    ReadChunk(path, 0, 262, function (err, buffer) {
        if (err) { cb(null, ""); return;}   // need return here !!
        var fileType = FileType(buffer);
        return cb && cb(null, fileType && fileType.mime || "");
    });
}

**Comment by oliver-moran** [comment]
Sure does. Nice catch. Thanks. Added to master and will release later this week.
