### ISSUE TITLE
[Error: Invalid format: 0]

### ISSUE THREAD

**Issue by chesiri** [oliver-moran/jimp#156]
i try load the images but i get the next error: "[Error: Invalid format: 0]"

this is an example of image:  http://static.dafity.com.br/p/-6211-0110871-1-catalog.jpg

thanks!

**Comment by oliver-moran** [comment]
Thanks. Issue tracked down to the exif-parser. I've wrapped it with a try...catch and will open an issue at the exif-parser library.
