### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by aaronsamuel137** [oliver-moran/jimp#16]
@oliver-moran, it looks like the recent pull request (#11) fixed an issue I was having with images writing to disk properly (#13).

Would you be willing to publish a new version to npm so that I can npm install the working version. I would greatly appreciate it.

**Comment by oliver-moran** [comment]
Will be make a change to fix #9 in the next few days. Will make a new NPM release then.

**Comment by oliver-moran** [comment]
Done. Version 0.2.0 released here and on NPM.
