### ISSUE TITLE
Grey Pixel Line

### ISSUE THREAD

**Issue by jeremypiednoel** [oliver-moran/jimp#163]
Hi, I have a grey line appear on the right of the image when i try to scale 

`image.scale(ratio);`

Original
![a182e56b9db451c501911cbb6fc744ad_cover](https://cloud.githubusercontent.com/assets/3902298/18142964/ee58845e-6f8d-11e6-9db8-96ad145fc466.png)

Scale
![35b28b7176f705f3d87b72bb96a98091_medium](https://cloud.githubusercontent.com/assets/3902298/18142965/f23cadc0-6f8d-11e6-8dd1-791d1b4ae3ac.png)

you guys have a idea ?
Thanks

**Comment by Iwasawafag** [comment]
Rightmost pixel on your image is transparent. Here I opened it in new tab and added `background: crimson;` to `<img>` element so it could be easily visible:

![image](https://cloud.githubusercontent.com/assets/5304842/18150960/43918d82-6feb-11e6-9ec4-9e6f251949da.png)

Short version is: those transparent pixels are described as transparent black (0x00000000 in your case, but could be anyting based on encoder liking) and when pixel color is averaged for chunk of pixels during scaling down that meaningless black color is getting mixed with visible white and we are getting grey, when should be getting white

PR #159 which I submitted two weeks ago fixes that. You will also better explanation there with some examples

**Comment by jeremypiednoel** [comment]
Indeed you're right, thanks for the answer !
