### ISSUE TITLE
read the image path is not the same like write path

### ISSUE THREAD

**Issue by Messilimeng** [oliver-moran/jimp#165]
var fileSrc = uploadPath + filename +".png";
		think.mkdir(uploadPath);
        fs.writeFileSync(fileSrc, dataBuffer, "binary");
        let rest = await Jimp.read(fileSrc);
        let smallimg = filename +"_small.png"
        rest.resize(10,10).write(smallimg);

The "smallimg" image is different to the read "fileSrc" path

**Comment by Iwasawafag** [comment]
Not a bug.

What gave you an impression that it will write new file to the same directory as the one image was read from? Readme doesn't promise that. Both `read` and `write` methods simply pass paths they were given to methods of a native 'fs' module so they are resolved relatively to current working directory. In your example you prepend `fileSrc` with  `uploadPath`, but for `smallimg` you don't. Neither working directory changes in-between thoes lines. You should change penultimate line to 

```js
    let smallimg = uploadPath + filename +"_small.png";
```

if you want resized image to appear in the same directory as source image.

**Comment by Messilimeng** [comment]
@Iwasawafag  Yes your are right.
