### ISSUE TITLE
gif support

### ISSUE THREAD

**Issue by ArmorDarks** [oliver-moran/jimp#166]
Some people mentioned [omggif](https://github.com/deanm/omggif)

Any chances to see support of gifs in Jimp too?

**Comment by oliver-moran** [comment]
Thanks. Lots of potential there. Including exporting animated gifs. Will add to the road map.

**Comment by aurium** [comment]
I believe this must be done by supporting multi layer images. At exporting we could do a GIF, an MNG... or export an multi layer format to another editor, like XCF, OpenRaster... or flatten all layers to a simple JPG or PNG.

**Comment by andreimcristof** [comment]
is there an ETA for this? we need this on production, since we use this module. Many thanks!

**Comment by slidenerd** [comment]
Perhaps you may find it useful to generate GIFS with the gifencoder and JIMP
```
var GIFEncoder = require('gifencoder');
var Jimp = require('jimp');
var fs = require('fs');

var encoder = new GIFEncoder(320, 240);
// stream the results as they are available into myanimated.gif 
encoder.createReadStream().pipe(fs.createWriteStream('myanimated.gif'));

encoder.start();
encoder.setRepeat(0);   // 0 for repeat, -1 for no-repeat 
encoder.setDelay(500);  // frame delay in ms 
encoder.setQuality(10); // image quality. 10 is default. 

// use node-canvas 
var image = new Jimp(320, 240, 0xff0000, function (err, image) {
    encoder.addFrame(image.bitmap.data)
    // use node-canvas 
    var image = new Jimp(320, 240, 0x00ff00, function (err, image) {
        encoder.addFrame(image.bitmap.data)
        // use node-canvas 
        var image = new Jimp(320, 240, 0x0000ff, function (err, image) {
            encoder.addFrame(image.bitmap.data)
            encoder.finish()
        });
    });
})

```

**Comment by jtlapp** [comment]
I've created a library called [`gifwrap`](https://github.com/jtlapp/gifwrap) for working with single- and multi-frame GIFs and still allowing you to leverage Jimp for image manipulation.

**Comment by hipstersmoothie** [comment]
@jtlapp @ArmorDarks it seems like GIF support was added. Can you verify it does what you need?

**Comment by hipstersmoothie** [comment]
omggif is a dep already. if more features are needed new issues should be opened

**Comment by jtlapp** [comment]
Ah, I see that Jimp now uses the omggif repo. When I was working with it last year, it was using a local copy.

> if more features are needed new issues should be opened

Unless they belong in separate layer which can be implemented as an independent module.

In any case, I've gradually been rewriting Jimp methods for my own purposes at high performance, so I myself don't have any further need for Jimp.

**Comment by hipstersmoothie** [comment]
I would love to see those perf improvements in jimp! Do you think they
could be used in jimp?
