### ISSUE TITLE
autocrop an image with 2 transparent sides

### ISSUE THREAD

**Issue by thisconnect** [oliver-moran/jimp#169]
I had an issue with `img.autocrop` NOT cropping an image where only 2 sides of an image are transparent (see image attached).

I could fix this by using `img.autocrop(false)`, related code https://github.com/oliver-moran/jimp/blob/cedac67667b3aaee6f67eda86c8af07a39246609/index.js#L869-L883

current documentation:

```
/* Crop */
image.autocrop(); // automatically crop same-color borders from image (if any)
```

The autocrop is missing some documentation, as it accepts 
- tolerance (Number, defaults to 0.0002)
- cropOnlyFrames (Boolean, defaults to true)
- callback

i.e.

``` js
image.autocrop(0.0003, false, function(){ console.log('callback') });
```

`img.autocrop` in other image manipulation programs would crop any side that is transparent, so default would be `false` for `cropOnlyFrames`. This would be a breaking change.

**Comment by thisconnect** [comment]
![test](https://cloud.githubusercontent.com/assets/546900/19033488/efcd0630-895e-11e6-9f70-7a49d01add9f.png)

(image contains a transparent area on the right and at the bottom)

**Comment by oliver-moran** [comment]
Thanks. I'm counting this as a bug since the behavior you expect is what I would expect also. Will fix in a coming release.

**Comment by hipstersmoothie** [comment]
documentation reflects correct value. and test image works with false set on autocrop. definitely gonna clean up the that for loop though

**Comment by wmcmurray** [comment]
Using **jimp v0.6.0** I was unable to autocrop an image with **transparency on bottom side only**. Until I discovered that the image need to have at least 1px of transparent space ALL AROUND IT for this feature to work.

I think **this is not intuitive at all** and it differ from any other autocrop feature I've used in my whole life :man_shrugging: but lets just cite one : the autocrop feature of Gimp (from which this package name is probably inspired of)
