### ISSUE TITLE
Is it possible to check whether an image is in RGB or CMYK mode?

### ISSUE THREAD

**Issue by PierBover** [oliver-moran/jimp#171]

**Comment by oliver-moran** [comment]
Do you have an example image? Or test case?

**Comment by PierBover** [comment]
[Image Magic](http://www.imagemagick.org/script/color-management.php) can detect the color mode of an image. JPEG supports CMYK and sometimes designers export their images in CMYK by mistake.

I have a desktop app in Electron that imports images and I'd like to notify the user when they are using a CMYK JPEG.

Here is a JPEG in CMYK color mode.
![cat](https://cloud.githubusercontent.com/assets/226483/19664770/9079d35c-9a07-11e6-90af-bdd8661edd8b.jpg)

**Comment by PierBover** [comment]
Here is a screenshot of the difference I'm seeing.

![image](https://cloud.githubusercontent.com/assets/226483/19664801/bd9256fc-9a07-11e6-8472-0f45832c6e8d.png)

**Comment by skoa-h** [comment]
I just tested this in photoshop. Created two new images 2x2 (no color management) in rgb and cmyk mode saved them for web without sRGB conversion as png and jpg. Then i opened all of them and even photoshop says they are in rgb mode. So my guess is that you cannot detect it.

**Comment by skoa-h** [comment]
Even with cmyk color management and all metadata, photoshop thinks its a rgb file.

**Comment by hipstersmoothie** [comment]
No browser support CMYK and non of the libraries we use to decode images support it either. So not possible ATM.
