### ISSUE TITLE
Is there a way to replace a color or approximately by another one ?

### ISSUE THREAD

**Issue by y3nd** [oliver-moran/jimp#172]
?

**Comment by oliver-moran** [comment]
Yes, see the [advanced usage](https://github.com/oliver-moran/jimp#advanced-usage) section in the documentation. That allow for low-level manipulation of individual pixels and/or colour components.

**Comment by turakvlad** [comment]
Guys, I've created a small package for replacing color with another one pixel by pixel. I'll allow myself to share it with you. The package calls [`replace-color`](https://www.npmjs.com/package/replace-color) and it implements one of the best color difference algorithm - [CIEDE2000](https://en.wikipedia.org/wiki/Color_difference#CIEDE2000).

Image output:
![Output](https://camo.githubusercontent.com/c4bb4abb49d80f5de93dab6e40ac193afd35b99e/68747470733a2f2f692e696d6775722e636f6d2f526355706675632e6a7067)
