### ISSUE TITLE
Size of picture change!

### ISSUE THREAD

**Issue by leknoppix** [oliver-moran/jimp#176]
Hello

I use this module to flip image or rotate image.
But, my problem is, What the initial size is not the same after.

example, My first image: 7.53Mo

When a rotation of 180°:  14Mo

What?

**Comment by oliver-moran** [comment]
Probably to do with the quality of the saved image. JPEGs are saved at quality 100 by default but normally it is better to reduce it to 80 or 60.

```js
Jimp.read("image.jpg").then(image => {
    image.rotate(180)
    .write("image-rotate-100.jpg")
    .quality(60)
    .write("image-rotate-60.jpg");
});
```

PNGs have separate compression settings.

**Comment by rcfrias** [comment]
Is this the final answer? It doesnt make sense to me that an unmodified image doubles it size just because the quality is 100%. By reducing it to 80 or 60 must be even lower than the original size.
