### ISSUE TITLE
Single pixel png causes "Ran out of data" error

### ISSUE THREAD

**Issue by pqvst** [oliver-moran/jimp#181]
I've created an issue in the `pngjs` library as well, since that's where the root problem is. Not sure if there is anything that jimp can do to prevent the problem if/until pngjs is fixed...

https://github.com/lukeapage/pngjs/issues/65

**Comment by strandedcity** [comment]
I see there's some activity on that issue; looks like it will get a fix soon on the pngjs level. When it does, would you be able to send a PR to this repo, bumping the pngjs version number appropriately?
