### ISSUE TITLE
How can Jimp Support .tff fonts 

### ISSUE THREAD

**Issue by c1c2ai** [oliver-moran/jimp#182]
When will Jimp support .tff fonts or what can we do to make jimp support .tff fonts

**Comment by shawmraz** [comment]
1

**Comment by hipstersmoothie** [comment]
@c1c2ai @shawmraz Jimp is primarily a bitmap manipulator. So it needs a bitmap font. Try using a tool to convert your ttf font to a bitmap font. Jimp cannot support non-bitmap fonts
