### ISSUE TITLE
Error: Unsupported MIME type:

### ISSUE THREAD

**Issue by Messilimeng** [oliver-moran/jimp#186]
Error: Unsupported MIME type: 
development-0     at Jimp.throwError (/root/xiaoya/node_modules/jimp/index.js:82:43)
development-0     at Jimp.parseBitmap (/root/xiaoya/node_modules/jimp/index.js:307:31)
development-0     at /root/xiaoya/node_modules/jimp/index.js:200:29

code

      let name = think.uuid();
        let topath = think.RESOURCE_PATH+'/static/upload/headimg/';
        let fullpath = topath + name +'.png'
        console.log(fullpath);
        fs.createReadStream(path).pipe(fs.createWriteStream(fullpath));
        let rest = await Jimp.read(fullpath);
        let smallimg = name +"_small.png"
        let smallimgpath = topath + smallimg;
        rest.resize(65,65).write(smallimgpath);

**Comment by Messilimeng** [comment]
![image](https://cloud.githubusercontent.com/assets/12272166/19922896/af797d2e-a11f-11e6-9589-edfbd3622ee7.png)

**Comment by jacobespersen** [comment]
+1

**Comment by jacobespersen** [comment]
@Messilimeng  I found a workaround by using fs-extra to copy the file to another location instead of using fs

**Comment by strandedcity** [comment]
Is this a problem with a particular image? If there's a mimetype problem for a particular image, it would be great to get a PR with a failing test so we can all reproduce the issue.

**Comment by hipstersmoothie** [comment]
@Messilimeng Can we get a test image? Or can you try again? Will close if no response

**Comment by Messilimeng** [comment]
yes，it works ,thanks
