### ISSUE TITLE
(different) webpack issue

### ISSUE THREAD

**Issue by bebbi** [oliver-moran/jimp#190]
I have bundled jimp with webpack / ES6 / babel6.
But running it produces an error:

```
import Jimp from 'jimp';
Jimp.read('pic.png', myCb);
```

bundles fine, but when running, the `Jimp.read()` statement produces

`index.js:7 Uncaught (in promise) TypeError: fs.open is not a function`

It appears to use node-only modules to read the pic.
May be related to #75 but looks like a different error.

**Comment by mydiscogr** [comment]
AFAIK is because you don't use browser version... look here https://github.com/oliver-moran/jimp/tree/master/browser

bytheway I get other error
Error: data must be a Buffer

let me know

**Comment by aurium** [comment]
Yes, you should use the browser version provided by Jimp project, because the `browser-wrapper` applied with browserify task when publishing.

Jimp may test the environment features in the future, so the same code (without wrappers) could be used anyware, with any bundler.

**Comment by hipstersmoothie** [comment]
browser version fixed in latest master. make sure that you're webpack build is using the "browser" version, although this should be done automatically.  closing in favor of #280
