### ISSUE TITLE
getExtension not working

### ISSUE THREAD

**Issue by alexdarland** [oliver-moran/jimp#193]
Hi!

I'm noticing that the package published to npm has same version number (0.2.27) as the repo here at Github, but the codebase is different (and doesn't include the getExtension functions among other things). Is it just an npm publish that's required or am I looking in the wrong place :)

Thanks!
/Alex

**Comment by jakeknerr** [comment]
+1

image.getExtension() is undefined

**Comment by harivasista** [comment]
+1
image.getExtension() is not a function.

**Comment by cryptoquick** [comment]
+1
`TypeError: image.getExtension is not a function`

**Comment by colynb** [comment]
+1 still not a function

**Comment by aurium** [comment]
I'm back from my vacation today. I'll see this bug as sun as i can, after push some testing updates.

**Comment by Iwasawafag** [comment]
Isn't really a bug though, it's just npm version is outdated

**Comment by alexdarland** [comment]
Welcome back @aurium! :) Thanks for the info. I'm looking forward to working with the updated version!

/Alex

**Comment by markbame** [comment]
Hi, i'm getting is this issue also. Is there a way around this? :)

**Comment by Iwasawafag** [comment]
Never version was pusblished to NPM a week ago, this problem is now resolved. 
Closing the issue
