### ISSUE TITLE
how can i get cropedImage's fileSize?

### ISSUE THREAD

**Issue by wuzeru** [oliver-moran/jimp#195]
```
Jimp.read(srcPath).crop(0,image.top,width,image.height); 
```

I want to get croped image's filesize, before write it to a real file

can i do it ?

**Comment by Iwasawafag** [comment]
First you would have to encode your image with `.getBuffer()` call and then you will be able to get byte size from the buffer's length.

**Comment by strandedcity** [comment]
Yes. Untested, but this should work:

```javascript
.getBuffer(Jimp.MIME_JPEG,function(mime,data){
    // file size in base-10 Mb
    console.log(data.length/1000000);
});
```
