### ISSUE TITLE
Can You Align Text?

### ISSUE THREAD

**Issue by Ratismal** [oliver-moran/jimp#196]
I love the simplicity of Jimp, but I've run into a few issues regarding text.

Is it possible to center align text? I'm trying to move away from GraphicsMagick, but text alignment is the one thing holding me back.

**Comment by maqboolkhan** [comment]
same issue

**Comment by Ratismal** [comment]
I have made a PR to implement this (#199)

**Comment by strandedcity** [comment]
Will be looking at #199 in the next couple days, closing this issue to move commentary to the PR.
