### ISSUE TITLE
Round jimp.rgbaToInt values

### ISSUE THREAD

**Issue by flash1293** [oliver-moran/jimp#197]
The r,g,b and a parameters of the jimp.rgbaToInt method should be rounded.
I just encountered strange results because I passed floating-point values as color values which causes them to leak into the other channels (because e.g `r = 122.354564; r * Math.pow(256, 3)` is not suffixed with 24 zero bits).

Proposed fix (add after line 408):
either rounding 
```js
r = Math.round(r);
b = Math.round(b);
g = Math.round(g);
a = Math.round(a);
```
or throwing
```js
if (r % 1 !== 0 || g % 1 !== 0 || b % 1 !== 0 || a % 1 !== 0)
        return throwError.call(this, "r, g, b and a must be integers", cb);
```

**Comment by strandedcity** [comment]
This is a good idea. Could you code up a pull request?

**Comment by oliver-moran** [comment]
Fixed with https://github.com/oliver-moran/jimp/pull/226. Thank you.
