### ISSUE TITLE
making crop fastere

### ISSUE THREAD

**Issue by pelikhan** [oliver-moran/jimp#2]
I've noticed that crop was quite slow. The problem is that you are creating and copying a new array on each pixel with .concat. Just use .push to avoid this behavior.

                bitmap.push(data[idx]);
                bitmap.push(data[idx+1]);
                bitmap.push(data[idx+2]);
                bitmap.push(data[idx+3]);

**Comment by charafsalmi** [comment]
i guess that would also make the resize quicker =)

**Comment by oliver-moran** [comment]
Thakns a lot, Pelikhan. A lot faster. I've integrated your code.
