### ISSUE TITLE
scaling an animated gif crashes

### ISSUE THREAD

**Issue by martinsookael** [oliver-moran/jimp#20]
Thank you for this library! 
I've been looking for something dependency less and am now playing around with this.
```
    var file = "animated_gif.gif";
    var scale = 2;
    new Jimp(file, function (err, image) {
      this.scale(scale)
        .quality(quality) // set JPEG quality
        .write(filename + ".jpg");
    })
....

causes
....
/node_modules/jimp/resize.js:25
        throw (new Error("Invalid settings specified for the resizer."));
               ^
Error: Invalid settings specified for the resizer.
at Resize.initialize (/node_modules/jimp/resize.js:25:16)
at new Resize (/node_modules/jimp/resize.js:17:10)
at Jimp.resize (/node_modules/jimp/jimp.js:815:18)
at Jimp.scale (/node_modules/jimp/jimp.js:840:10)
at Jimp.<anonymous> (/node_modules/jay-npm/lib/jay.js:371:12)
at Jimp.throwError (/node_modules/jimp/jimp.js:40:44)
at Jimp.parseBitmap (/node_modules/jimp/jimp.js:190:24)
at /node_modules/jimp/jimp.js:139:25
at fs.js:266:14
at Object.oncomplete (fs.js:107:15)
....

**Comment by gcq** [comment]
AFAIK this library can't handle gifs. Currently supported mime types are [png, jpeg and bmp](https://github.com/oliver-moran/jimp/blob/master/jimp.js#L160-L162). Should fail at [line 190](https://github.com/oliver-moran/jimp/blob/master/jimp.js#L190) instead, where mime types are handled.

Maybe post the gif you are having problems with.

**Comment by oliver-moran** [comment]
Yes. Short answer is that gifs aren't supported.

Longer answer is that you should check for errors in the regular node style:

    var file = "animated_gif.gif";
    var scale = 2;
    new Jimp(file, function (err, image) {
      if (err) throw err; // argh! an error!!
      this.scale(scale)
        .quality(quality) // set JPEG quality
        .write(filename + ".jpg");
    })

I haven't tested the above but let me know if it works.

And if anybody knows of a suitable gif library, would be happy to include support.

**Comment by oliver-moran** [comment]
Looks like it has potential: https://www.npmjs.com/package/omggif

**Comment by jtlapp** [comment]
You can now do this using the [`gifwrap`](https://github.com/jtlapp/gifwrap) library. It uses the same internal image format as Jimp, so you can easily leverage Jimp for manipulating GIF image frames.
