### ISSUE TITLE
NPM package: --use_strict mode

### ISSUE THREAD

**Issue by ytiurin** [oliver-moran/jimp#201]
Hi Oliver,
When using Jimp in Node environment with the --use_strict mode enabled, dependency module `bmp-js` causes an exception. I raised an issue on `bmp-js` repo https://github.com/shaozilee/bmp-js/issues/8 and author fixed it in the latest version (0.0.3) on NPM.
Whould be great to have it up-to-date in Jimp package dependency.

Many production environments run in --use_strict mode so it would be great if Jimp also did.

Amazing lib!
Cheers :beer:

**Comment by Tarpsvo** [comment]
Thanks for reporting it to `bmp-js` and for getting it fixed. I support this as I ran into the same problem. 👍

**Comment by Dewep** [comment]
Same problem, it would be cool to update the package! :)

**Comment by strandedcity** [comment]
https://github.com/oliver-moran/jimp/pull/225
