### ISSUE TITLE
Drawing a rectangle

### ISSUE THREAD

**Issue by JpEncausse** [oliver-moran/jimp#202]
Hi,
Very clean API and library very close to OpenCV

I assume if I want to draw a rectangle I'll to use low level x,y,z ?

**Comment by Iwasawafag** [comment]
Correct, there's no drawing API at the moment so you would have to manipulate pixel values directly:

```js
const Jimp = require('jimp');
const canvas = new Jimp(512, 256, 0xFFFFFFFF)

// fill
canvas.scan(32, 32, 256, 128, function (x, y, offset) {
     this.bitmap.data.writeUInt32BE(0x00000088, offset, true);
});

// border 
function iterator(x, y, offset) { 
    this.bitmap.data.writeUInt32BE(0x00000088, offset, true); 
}

canvas.scan(236    , 100    , 240, 1  , iterator);
canvas.scan(236    , 100+110, 240, 1  , iterator);
canvas.scan(236    , 100    , 1  , 110, iterator);
canvas.scan(236+240, 100    , 1  , 110, iterator);
```

[Live version of this code](https://runkit.com/5837aadc97657a0014e13f3e/5837aadc2864a00013d4e123) because why not. It's not too bad as long as you're fine with lack of antialiasing, I guess,

I think @houd1ni is working on implementing "basic canvas functionality" (according to #183) but I don't know what's the progress on that and what features are planned.

**Comment by houd1ni** [comment]
@Iwasawafag  It's OK: the plan is to implement the very basics during this week and complete the task within 1.5-2 weeks. Just have to lookup free rest hours to make it with ❤️

**Comment by houd1ni** [comment]
First features is to just draw lines / rectangles / ovals and, maybe, other primitive 2D figures.

The second, maybe, will be more complex "3D" transitions and projections. But I guess, this should be kinda plugin, maybe. And most probable, I'll just make some special convenient API to implement this advanced actions. Maybe via transitions to 2D canvas engine described before. Will think and discuss.

**Comment by JpEncausse** [comment]
Thanks @Iwasawafag for the feedback !

**Comment by houd1ni** [comment]
@JpEncausse just rolled out very first stuff. See example in /test/canvas.js
There will be big improvements in algorithms and methods in December.
https://github.com/houd1ni/jimp/

Also keep an eye at https://github.com/oliver-moran/jimp/issues/183
I'm going to write there info about the progress. Any code is welcome, by the way 😸

**Comment by subhamchatterjee** [comment]
I get this error when I implement the same thing to update a few colors of a JIMP image.

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 50135036. Received 50135040

Can you suggest a solution to this?

`loadedImage.scan(0, (startingPositionY - 15), (fontWidth + 20), (imageDimension.height - startingPositionY + 30), function (x, y, offset) {
	this.bitmap.data.writeUInt32BE(Jimp.cssColorToHex('rgba(0,0,0,0.1)'), offset, true);
});`

**Comment by hipstersmoothie** [comment]
Please file a new issue with runnable code @subhamchatterjee
