### ISSUE TITLE
Cannot load custom font into Jimp

### ISSUE THREAD

**Issue by NellyWhadsDev** [oliver-moran/jimp#205]
Heyo,

I've been attempting to load a custom font into Jimp and get [this error](http://pastebin.com/Jm7QSkgt). The TrueType font is attached with the issue along with the BMfont conversion done using [Littera](http://kvazars.com/littera/).

[Font Files](https://drive.google.com/drive/folders/0ByIqPSg99E4LR3FzMEVJNXdQeXM?usp=sharing)

Anyone have any suggestions as to next steps? I'm not sure how to find the exact cause

Cheers,
Nelly

**Comment by kodie** [comment]
I'm getting this error as well

> (node:74513) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: cannot parse font file Cannot read property '0' of undefined

**Comment by kodie** [comment]
After some more testing, I think it just depends on the font. Maybe if the font is missing certain characters?

**Comment by omw2005** [comment]
@kodie which fonts did work for you? I got this error with every font I tried to load. (.ttf to .fnt conversion on Littera)

**Comment by Kxze** [comment]
This is still happening.

**Comment by Ojas-Gulati** [comment]
hmm, let me take a look

**Comment by Kxze** [comment]
[font.zip](https://github.com/oliver-moran/jimp/files/1264384/font.zip)
[font2.zip](https://github.com/oliver-moran/jimp/files/1264386/font2.zip)
[font3.zip](https://github.com/oliver-moran/jimp/files/1264385/font3.zip)

I tried these three formats with varying success. One of them gave me the error described in the issue and the other two ended up not writing anything to the file.

**Comment by grebett** [comment]
In fact, Bitmap fonts xml have a `kernings` xml tag that seems to be required by Jimp.

I've solved the problem supra adding the following code to the end of your font file:

```XML
<kernings count="0">
</kernings>```

**Comment by hipstersmoothie** [comment]
https://github.com/mattdesl/parse-bmfont-xml/pull/2

**Comment by mattdesl** [comment]
I merged in those two PRs for the bmfont modules. Let me know if there's anything else!

**Comment by hipstersmoothie** [comment]
@mattdesl I just tested it and it works! Thanks for the quick response.
