### ISSUE TITLE
Consider graceful-fs to allow opening lots of files at once

### ISSUE THREAD

**Issue by Tarpsvo** [oliver-moran/jimp#207]
Hey.

I ran into an issue when creating a spritesheet with a lot of emoticons (~1700), where node `fs` stopped working with the error `too many files open`.

The more difficult and manual solution would be to add a limit to how many files I read with `Jimp` at a time, but this can be also solved on a lower level, by replacing Node's `fs` with `graceful-fs`, which handles it for the user and holds back the read and write calls until there's enough free resources to execute them (or well, a slot opens).

I hastily implemented it by doing the following in `index.js`:
```shell
var FS = require("fs");
var gracefulFs = require('graceful-fs');
gracefulFs.gracefulify(FS);
```

But I guess this can be solved with a proper implementation of a `graceful-fs` instance as well. Thanks for the awesome library and please let me know what you think of this suggestion. 👍

**Comment by Iwasawafag** [comment]
You could also get away without patching 'fs' module. Just read files with `graceful-fs` in your code and feed file contents to Jimp constructor.

**Comment by strandedcity** [comment]
I agree with @Iwasawafag. Jimp's role is to process image data; I would consider the filesystem interaction a convenience that cleans up the syntax around loading images more than a core function of Jimp. ```graceful-fs``` is certainly a good idea for some implementations, but I think the base case of "load an image, process it" is well served by Node's native ```fs```.

@Tarpsvo I'm trying to help @oliver-moran by cleaning up the issues and PR's at the moment. If you think the issue needs more discussion please feel free to re-open. I'm not trying to shut down the discussion, but it seems like the number of open issues and PR's is starting to overwhelm the maintainers' ability to keep up!

**Comment by Tarpsvo** [comment]
Yup, @Iwasawafag's answer is most definitely the correct solution. I kind of overlooked that.

Thanks guys.

**Comment by RimacV** [comment]
After using the here suggested solution for reading files. 
I encountered the same problem for writing processed images to files.

I solved this by modifying  the write method.
I did not test this and I assume it breaks conventions and stuff but for my case it worked. It took me a while figuring this out, so I thought I would share it here.

```
/**
 * Writes the image synchronus to a file
 * @param path a path to the destination file (either PNG or JPEG)
 * @param (optional) cb a function to call when the image is saved to disk
 * @returns this for chaining of methods
 */
Jimp.prototype.writeSync = function (path, cb) {
    if ("string" != typeof path)
        return throwError.call(this, "path must be a string", cb);
    if ("undefined" == typeof cb) cb = function () {};
    if ("function" != typeof cb)
        return throwError.call(this, "cb must be a function", cb);

    var that = this;
    var mime = MIME.lookup(path);

    this.getBuffer(mime, function(err, buffer) {
        if (err) return throwError.call(that, err, cb);
        FS.writeFileSync(path,buffer)
        cb.call(that, null, that);
        return this;
    });


};
```
