### ISSUE TITLE
support efficiently manipulate the same image several times

### ISSUE THREAD

**Issue by fwang2002** [oliver-moran/jimp#211]
As I can see, the resize or crop of the same image must be used with a clone.
Can it be supported for using with image.resize().crop().crop()，or without a chain, but call resize, crop several times for the same object.
```
Jimp.read("lenna.png").then(function (lenna) {
    lenna.resize(256, 256)            // resize
         .write("lena-small-bw.jpg"); // save
    lenna.resize(64, 64)            // resize
         .write("lena-small-bw2.jpg"); // save
    lenna.crop(...)
         .write("lena-small-bw3.jpg"); // save
    lenna.crop(...)
         .write("lena-small-bw4.jpg"); // save
}).catch(function (err) {
    console.error(err);
});
```

**Comment by strandedcity** [comment]
It already works this way:

http://codepen.io/strandedcity/pen/NdRRMv?editors=1000#0

Jimp's methods return ```this``` to support chaining. The Jimp object's bitmap data is mutated by each operation, when you chain methods each will operate on the output of the last. If you want to have multiple crops of the original image, you would need to clone. But otherwise, you'll keep manipulating the output of the prior function.

**Comment by fwang2002** [comment]
But when I want to manipulate the original bitmap several times, I have to clone, and clone is slow.

**Comment by instructaPhil** [comment]
Oh, I see what you're after. Returning the original Jimp from every function doesn't make much sense to me... if I do this:

```javascript
1
.add(1)
.add(1)
```

I expect the output to be 3, not 1. So instead, what I think you want here is a version of creating a Jimp object from another Jimp object without copying the buffer of data. It would be an option for the Jimp constructor --

https://github.com/oliver-moran/jimp/blob/master/index.js#L140

Pull requests encouraged! This would be an easy one, and very nice behavior to have!

**Comment by strandedcity** [comment]
Oh, I see what you're after. Returning the original Jimp from every function doesn't make much sense to me... if I do this:

```javascript
1
.add(1)
.add(1)
```

I expect the output to be 3, not 1. So instead, what I think you want here is a version of creating a Jimp object from another Jimp object without copying the buffer of data. It would be an option for the Jimp constructor --

https://github.com/oliver-moran/jimp/blob/master/index.js#L140

Pull requests encouraged! This would be an easy one, and very nice behavior to have!

**Comment by Kamille-Ligula** [comment]
Has this functionality been implemented yet? I am presently finding myself needing it, but for what I understand the only way to get to crop the same image again at a different place is still to fully reload it from the buffer, right?
