### ISSUE TITLE
Progresssive JPEG export?

### ISSUE THREAD

**Issue by tomByrer** [oliver-moran/jimp#213]
In some cases, PJPEGs are smaller than the on progressives.
I found some C++ code if that's helpful.

**Comment by strandedcity** [comment]
Jimp relies on https://github.com/eugeneware/jpeg-js for jpeg encoding/decoding. Progressive JPEG export would need to be added there, and then an option for progressive export would need to be added to Jimp. Would be great to have!

**Comment by thisconnect** [comment]
Have a look at imagemin. I use jimp + imagemin since a while

**Comment by strandedcity** [comment]
They rely on https://github.com/mozilla/mozjpeg, which isn't a pure-JS implementation of the JPEG encoder. Unfortunately, won't work for Jimp.

**Comment by thisconnect** [comment]
You are right, I always forget people use jimp in the browser. Just for correction: imagemin has various plugins. One of them is depending on mozjpeg. Others are guetzli, jpegtran, jpeg-recompress, jpegoptim and many pther for png or webp.

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in [`v1.2.0`](https://github.com/jimp-dev/jimp/releases/tag/v1.2.0) :rocket:
