### ISSUE TITLE
how to preload images that will be generated?

### ISSUE THREAD

**Issue by slidenerd** [oliver-moran/jimp#217]
Thank you for all your hardwork in making this awesome library. I have a scenario where I need to show a random colored background each time with different text on it for a number guesser game. I believe creating one for each request would be a disaster in terms of memory usage. Lets say I decide 5 colors to render and pick one

let images = [
    new Jimp(width, height, red)
    new Jimp(width, height, blue)
    new Jimp(width, height, green)
]

How do I give a callback in this scenario? Promises arent working it seems. Any suggestions

**Comment by slidenerd** [comment]
No worries, I solved it

```
let colors = [0xFF5252FF, 0xE91E63FF, 0xE040FBFF, 0x673AB7FF, 0x3F51B5FF, 0x2196F3FF, 0x00BCD4FF, 0x009688FF, 0x4CAF50FF, 0x8BC34AFF, 0xCDDC39FF, 0xFFEB3BFF, 0xFFC107FF, 0xFF9800FF, 0xFF5722FF]

let promises = []
for (let i = 0; i < colors.length; i++) {
    promises.push(new Promise((resolve, reject) => {
        return new Jimp(width, height, colors[i], (error, image) => {
            if (error) {
                reject(error)
            }
            else {
                resolve(image)
            }
        });
    }))
}
```

**Comment by Iwasawafag** [comment]
Creating new image is a synchronous operation. Quoting readme:

> If you want to begin with an empty Jimp image, you can call the Jimp constructor passing the width and height of the image to create and *(optionally)* a Node-style callback:

So you could have simplified your code down to one line:

```js
const colors = [ /*...*/ ]
const images = colors.map(color => new Jimp(width, height, color))
```
