### ISSUE TITLE
Image processing Synchronously

### ISSUE THREAD

**Issue by harivasista** [oliver-moran/jimp#220]
Hello,
I am using the module with electron app. I need to calculate the average of pixels and then accordingly replace the alpha value of pixels. And I also need to calculate the average around few pixels which were not replaced. I went through the docs for promises but wasn't able to figure out. Could someone help me with this ?

**Comment by strandedcity** [comment]
It sounds like you're looking to pixelate an image, then use the greyscale values as an alpha channel. Can you post some sample code to illustrate the difficulty you're encountering?

**Comment by Ojas-Gulati** [comment]
+1 I often need some synchronous processing

**Comment by hipstersmoothie** [comment]
closing in favor of #303
