### ISSUE TITLE
Support reading from base64

### ISSUE THREAD

**Issue by cfjedimaster** [oliver-moran/jimp#231]
Forgive me if this is already supported and I missed it, but I noticed you can generate Base64 from an image but you can't create a new image from Base64. Would that be a good addition?

**Comment by Datamats** [comment]
Make the base64 into a buffer and read it

**Comment by cfjedimaster** [comment]
Ah, that makes sense. Thank you.

**Comment by boban984** [comment]
Hey Guys, i get the following error : **"mime must be a string"**

Jimp.read(Buffer.from('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAABkCAYAAADDhn8LAAAD1ElEQVR4Xu3cW3IUMQyFYWdnLI2lwcpI1dRMCBky7YtkS0c/TxR0u63j85XzlLfW2q/W2p/W2s/W2u/GHxIggY8E3u5/+3EHAhTKQQKfEngAefwTUKgHCbwAAhTqQQIdQIBCTUigtfb1R6zvQuFHL+pSMoFeINwoJevB0KNAgEJnSiUwCwQopWpSd9hVIECp250Sk1sBAUqJutQb0hoIUOp1SHpiLyBAka5NneG8gQClTpckJ90FBCiS9dEfajcQoOh3SmrCU0CAIlUj3WFOAwGKbrckJosCBCgSddIbIhoQoOh1LPVEUYEAJXWtdDYfHQhQdLqWcpIsQICSsl75N50NCFDydy7VBFmBACVVzfJuNjsQoOTtXoqdqwABSoq65dukGhCg5Otg6B2rAgFK6Nrl2Zw6EKDk6WLInVYBApSQ9Yu/qWpAgBK/k6F2WBUIUELVMO5mqgMBStxuhtgZQP49Bn5Jd4haxtkEQP5/FkCJ09GjOwHI6/iBcrSe5z8OkL4zAEpfTnJPAWTsSIEyllf6pwEyd4RAmcst3VsAWTsyoKzlF/5tgNgcEVBscgy3CkBsjwQotnkeXw0gPkcAFJ9ct68KEN/IgeKbr/vqAHGP+PYBoOzJ2fwrADGP9OWCQNmb9/LXALIc4dQCQJmKbf9LANmf+ecvAuVs/pdfB8hlRFseAMqWmMc/ApDxzDzfAIpnuhNrA2QitA2vAGVDyD2fAEhPSueeAcq57G9fBsjhA+j8PFA6g7J+DCDWifquBxTffJ9WB8jmwI0+BxSjIK+WAchVQrH/HyjO5wMQ54A3LQ8Up6AB4hTsoWWBYhw8QIwDDbIcUIwOAiBGQQZdBiiLBwOQxQCTvA6UyYMCyGRwSV8DyuDBAWQwMJHHgdJ5kADpDEr0MaBcHCxARJs/OBZQvgkMIINNEn8cKF8OGCDijZ8cDyj34AAy2aAir5WHApAiTV8csywUgCw2p9jr5aAApFjDjcYtAwUgRo0puow8FIAUbbbx2LJQAGLclOLLyUEBSPFGO40vAwUgTg1h2VsC6aEAhCbvSCAtFIDsqAffeCSQDgpAKO+JBNJAAciJevDNNDcKQChrhATC3igAiVAP9hD2RgEI5YyYQJgbBSAR68GewtwoAKGMGRI4dqMAJEM92OOxGwUglC9jAttuFIBkrAd73najAISyKSTgdqMARKEezOB2owCEcikmYHajAESxHsxkdqMAhDJVSGD6RgFIhXow4/SNAhDKUzGB7hsFIBXrwczdNwpAKAsJvPjlEgChHiTwN4GnH70AQj1I4DmBDyjvpHwrM11guxcAAAAASUVORK5CYII=', 'base64'));

**Comment by Iwasawafag** [comment]
You need to remove `data:image/png;base64,` from the string before passing it to `Buffer#from`.

**Comment by boban984** [comment]
Found the solution ... "data:image/png;base64" is redunant when using Buffer.from and should be removed, after that all is ok

**Comment by vichajser** [comment]
when i remove `data:image/png;base64,` like `url.replace('data:image/png;base64,', '');`, new issues that `path must be a string` is coming
so how to fix that?

**Comment by NeXTs** [comment]
Why don't add this small snippet to lib?

something like
```
if(input.indexOf('base64') != -1) {
    return Jimp.read(Buffer.from(input.replace(/^data:image\/png;base64,/, ""), 'base64'))
} else {
    // handle as Buffer, etc..
}
```

**Comment by altinselimi** [comment]
Hi, when I use Jimp to read a base64 buffer, it throws an error in the console 
`Jimp expects a single ArrayBuffer or image URL`
Here is how I am using it
```
let url = this.fileData.url.replace(/^data:image\/\w+;base64,/, "");
let buffer = new Buffer(url, 'base64');

Jimp.read(buffer).then(img => {
	let _img = img.greyscale().getBase64(Jimp.AUTO, src => {
		console.log('src');
	});
}).catch(function(err) {
	console.error(err);
});
```

**Comment by hipstersmoothie** [comment]
as it seem like the original issue has been fixed in a few ways. I'm gonna close this issue. @altinselimi feel free to open a new issue with a full example of what you are trying to accomplish

**Comment by taksenov** [comment]
> (input.replace(/^data:image\/png;base64,/, ""), 'base64'))

Why use a regular expression to delete this `data:image/png;base64` part. Maybe instead use split-logic in code:
```js
  const splitted = input.split(',');
  const [, string] = splitted;
```

`,` - this character is not used in base64 format
