### ISSUE TITLE
The write promise callback is called before file exists

### ISSUE THREAD

**Issue by karvapallo** [oliver-moran/jimp#232]
I just noticed that when using the promise based API, at least the write method actually resolves before the file was created, which is probably not what one would expect.

**Comment by thisconnect** [comment]
Could you test if the write callback works as expected? It looks as if jimp.protoype.write isn't a promise at all.

**Comment by karvapallo** [comment]
Yeah the callback works as expected. If it's not a promise, that would explain it. I'm just returning it within a "then" function of another promise (chained promises). The write function should be made to support a promises as well though right?

**Comment by thisconnect** [comment]
I would love all methods to support real native promises. First testing (#227) needs to be done, to ensure full backwards compatibility, before full promise support can be implemented. In the mean time you have to do something like

```js
return new Promise((resolve, reject) => { this.write(resolve) }) 
```
(or similar)

**Comment by karvapallo** [comment]
The documentation does currently imply that one can use either promises or callbacks. If this is not the case, I think it would be nice to point that out in the docs.

**Comment by thisconnect** [comment]
> The documentation does currently imply that one can use either promises or callbacks.

I can only find this about the write function https://github.com/oliver-moran/jimp#writing-to-files no mention of any promise here :(

**Comment by Iwasawafag** [comment]
`Jimp#write` does not return Promise at the moment. There is a pull request #188 implementing this feature but it looks like we didn't agree on the function signature and best solution of ones proposed (not providing a callback) would be a breaking change.

I agree, documentation is a little bit unclear and at first I also expected promise support. Yes, it does not promise promises to be returned by `write` or `getBuffer` methods, but the way snippet is written is quite misleading, as write call does not include the callback.

```js
Jimp.read("lenna.png").then(function (lenna) {
    lenna.resize(256, 256)            // resize
         .quality(60)                 // set JPEG quality
         .greyscale()                 // set greyscale
         .write("lena-small-bw.jpg"); // save            <------- this line
}).catch(function (err) {
    console.error(err);
});
```

**Comment by Haringat** [comment]
@Iwasawafag What would break when returning a promise whenever no second argument is given?

**Comment by rosygupta** [comment]
The functionality seems to return a callback (work in async) but does not accept then/exec in Node.

**Comment by Haringat** [comment]
@rosygupta I assume you tried something like this:
```js
async function write(lenna, path) {
    await lenna.write(path);
}
```
This doesn't work, but also won't throw an error, since in JavaScript you can basically await any value. If it is not a Promise then the expression will immediately return the awaited value. Jimp.prototype.write() returns an instance of Jimp (the one which was written). If you await that then v8 will just take the Jimp and return it in the expression. That's also the reason why you don't actually have any delay in the async method.
Here's the proof:
https://github.com/oliver-moran/jimp/blob/master/index.js#L2784
