### ISSUE TITLE
Cached images

### ISSUE THREAD

**Issue by extensionsapp** [oliver-moran/jimp#233]
Hello.

When using images at url, it would be good to cache the image to repeat again not to go.

```
Jimp.read("http://www.example.com/path/to/lenna.jpg", function (err, image) {
    // do stuff with the image (if no exception)
});
```

Is that possible?

**Comment by Iwasawafag** [comment]
Not out of the box, no. Of course it's possible to cache data in memory, add support for `Last-Modified` or `ETag` headers and handling of 304 code, but that would require cramming too much extra HTTP-protocol-related logic in, I don't think it's something worth doing. Not everyone needs this feature and for those users it would be just a waste of memory while others may even find caching unwanted.

But there are two ways of getting what you want.

### 1. Use `Jimp#clone`

```js
Jimp.read("http://www.example.com/path/to/lenna.jpg", function (err, originalImage) {
    if (err) return console.error(err);

    // do stuff with the image
    originalImage
        .clone()
        .scaleToFit(260, 120)
        .getBuffer(Jimp.AUTO, handleEncodedImage);

    // do more stuff with the image
    originalImage
        .clone()
        .scaleToFit(600, 400)
        .getBuffer(Jimp.AUTO, handleEncodedImage);
});
```

### 2. Use [`memoizee`](https://www.npmjs.com/package/memoizee) module

```js
const Jimp = require('jimp');
const memoize = require('memoizee');

const readImage = memoize(Jimp.read, { async: true, maxAge: 60000  }); // cache for a minute

readImage("http://www.example.com/path/to/lenna.jpg", function (err, originalImage) {
    if (err) return console.error(err);

    originalImage
        .clone() // still have to clone it, otherwise we will modify cached copy
        .scaleToFit(260, 120)
        .getBuffer(Jimp.AUTO, handleEncodedImage);
});

// some time later
readImage("http://www.example.com/path/to/lenna.jpg", function (err, image) {
    /* do something else (just don't forget to clone the image) */
});
```

This could be handy if you can't predict beforehand how many times you will need to access the same image. Also very flexible in terms of caching configuration.

I will close the issue now, but feel free to continue discussion if you want
