### ISSUE TITLE
How to do Image Overlays, Underlays and Watermarks

### ISSUE THREAD

**Issue by rahadur** [oliver-moran/jimp#235]
Hello i am just new to this npm package i think this is a very good tools for Node image processing  but i am facing some problem when i am trying to do Image **Overlay, Underlays and Watermarks**  i was try to use this methods

image.composite( src, x, y ); 
image.mask( src, x, y ); 

i am just field, can any one tell that how can i do it using this amazing image processing tool.

Here is the example what i am trying to do.. 
http://cloudinary.com/documentation/node_image_manipulation#overlays_underlays_and_watermarks

**Comment by hipstersmoothie** [comment]
The `composite` function will overlay one image onto another. You can also set the opacity of the overlayed image. 

```js
const Jimp = require('jimp');

async function waterMark(image) {
  const image = await Jimp.read(image);
  const watermark = await Jimp.read('./watermark.png');

  image.composite(src, 0, 0, {
    mode: Jimp.BLEND_SOURCE_OVER,
    opacityDest: 1,
    opacitySource: 0.5
  })

  await image.writeAsync('watermarked.png');
}

waterMark('./your-image.png');
```

**Comment by ashadnasim52** [comment]
how to put image in center

**Comment by widada** [comment]
> how to put an image in the center

Same problem

**Comment by MaximilianLloyd** [comment]
Is there a way to add "padding", say you have an overlay that is a 20px red border. Can you inset the image inside that border something?
