### ISSUE TITLE
Can't import custom font

### ISSUE THREAD

**Issue by Sneezembop** [oliver-moran/jimp#236]
Having trouble getting this [font ](https://drive.google.com/file/d/0B53DM11wrWW3Qk1xMk55NW4tMmM/view?usp=sharing)to work.  I'm using font forge to convert it from TTF to FNT.  If anyone can figure it out please let me know how.

I've tried opening the provided fonts in font forge and they all throw an error.
![image](https://cloud.githubusercontent.com/assets/1168606/22764088/8c1dd92e-ee36-11e6-93c3-ece3e3abe102.png)
![image](https://cloud.githubusercontent.com/assets/1168606/22764186/14d7999e-ee37-11e6-9310-6c6cac996f8c.png)

**Comment by hipstersmoothie** [comment]
The fonts do work, I can verify that. use a tool like https://github.com/libgdx/libgdx/wiki/Hiero to convert your font. I tried your font and it worked fine. make sure to move both the .fnt and .png file that are generated.
