### ISSUE TITLE
NPM issues

### ISSUE THREAD

**Issue by john-yick** [oliver-moran/jimp#237]
It seems that the npm install command does not pull back the latest version of index.js as the convolution function is not present in it.

[2017-02-09 10:08:30.842] [ERROR] console - TypeError: img.crop(...).resize(...).autocrop(...).convolution is not a function

Can you please update the npm config. Copying the index.js from the git repo into the node_modules fixes things.

**Comment by oliver-moran** [comment]
John, I just made a publish to NPM just now. The `image.convolute()` method is there now (a slightly different version to the one you were working on).
