### ISSUE TITLE
Overwrite existing file not working

### ISSUE THREAD

**Issue by fdddk23** [oliver-moran/jimp#239]
Hi,

Anybody experiecing the problem that in an linux environment (Ubuntu 16.04.1 LTS) overwriting files doesn't work.
On my test environement (Windows 10) this works without any problem.
Also for other modules overwriting files isn't a problem - except JIMP.

I don't get any failure message or error reported - it just don't overwrite the file.
Writing is also in the linux environment no problem.

Is this a jimp problem, node or rights management problem?

    jimp.read(path).then(function(result){
      result.cover(250,250)
            .quality(60)
            .write(path);
    }).catch(function(err){
      return res.status(500).json({message:err});
      });

**Comment by thewizarodofoz** [comment]
It is probably a permission problem. To better understand it I recommend you pass a callback to `write`, then you can see the error you're getting (otherwise `write` failed silently - see #261 ).

**Comment by hipstersmoothie** [comment]
I can overwrite images. Open another issue if this persists
