### ISSUE TITLE
Facial Detection Enchanment

### ISSUE THREAD

**Issue by internetimagery** [oliver-moran/jimp#240]
Hi guys. Awesome work!

I noticed this project https://www.npmjs.com/package/face-detect that takes an existing pure javascript project (ccv) and makes it work with node canvas.

By looking through the project, in my naivety, it would appear as though canvas is merely used to scale / greyscale / crop the image, and to grab the raw data. All of which jimp seems capable already. Perhaps the only minor hangup being with jimp using buffers and canvas returning intarrays.

Perhaps it would be possible to add face detection to the library. A very welcome feature!

**Comment by aurium** [comment]
Nice to know @internetimagery! For sure there is many other high-level and specific image manipulation libs in the wild.
I believe there is not right to add this features to a generic image manipulation lib, however it is important to make sure both can work together.

Have you some information about how this libs can work together and how ca we improve this interaction?

**Comment by internetimagery** [comment]
I suppose the best way to interact would be to be able to express images as a Uint8ClampedArray. Which is what comes out of canvas.

Or even go all out and provide a canvas-like api wrapper to jimp. So any tool that uses canvas for image manipulation (rather than display) can be used with jimp.

That said, that would be more work than just adding the higher level function to jimp.   😉

**Comment by NoPinky** [comment]
I also don't think that adding face detection or facial recognition would fit in the intention of jimp. But you can use jimp for the image preprocessing (like converting image into grayscale, resize, adjust contrast and so on...) before relay the processed image to another module for the detection/recognition part. 
I use jimp to preprocess (resizing, color adjustments, bluring, rotation...) images before feeding it to a neural network (image recognition).

**Comment by aurium** [comment]
> Or even go all out and provide a canvas-like api wrapper to jimp. So any tool that uses canvas for image manipulation (rather than display) can be used with jimp.

That could be really a good thing!

> That said, that would be more work than just adding the higher level function to jimp.

For sure!
However, implement only the interface needed for `face-detect` may be a _not so hard job_. If you want to implement this, wold be nice! (If you want some help, plz, [contact me](http://telegram.me/aurium))

**Comment by hipstersmoothie** [comment]
This doesn't seem in the scope of jimp. Closing. If you need something specific to enable this feel free to open another issue.
