### ISSUE TITLE
image.getExtension() doesn't work

### ISSUE THREAD

**Issue by nfyfamr** [oliver-moran/jimp#241]
The document(https://github.com/oliver-moran/jimp#writing-to-files) says that use image.getExtension method to get file extension.
So I tried that, but get the error that image.getExtension isn't a function. See the following.

code:
```
	Jimp.read(imgURL).then( image => {
		console.log( image );
		let folderPath = './2017_01_02'
		let fileName = "origianl." + image.getExtension();
		let path = url.resolve(folderPath, fileName);
		...
	});
```

and result:
```
Jimp {
  _originalMime: 'image/jpeg',
  bitmap:
   { width: 1466,
     height: 1201,
     data: <Buffer db dc e4 ff d8 d9 e1 ff cd e2 e7 ff cd e2 e7 ff ca e0 e9 ff cb e1 ea ff ce de ea ff d0 e0 ec ff cc e1 ea ff cc e1 ea ff cc e1 ea ff cc e1 ea ff cf df ... > } }
TypeError: image.getExtension is not a function
    at Jimp.read.then.image (C:\Users\wrl\Desktop\weeklymenu\index.js:29:38)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

So, could you check the error and update the docment?

**Comment by thewizarodofoz** [comment]
I believe this is the same issue as #58 and others.

I verified this by replacing the content of `index.js` in my `node_modules` folder with the file from this repository, and it worked.

**Comment by Iwasawafag** [comment]
Never version was pusblished to NPM a week ago, this problem is now resolved.
Closing the issue
