### ISSUE TITLE
getting 'mime must be a string' error when loading image

### ISSUE THREAD

**Issue by strachenko** [oliver-moran/jimp#242]
Hi, 

I've encountered issue when loading and image. Error says 'mime must be a string'.
It's interesting because for 2 different images the same code works differently (works fine with one image and crashes when using the other. Both images are .png).

I'm using jimp for browsers.
Thanks.

**Comment by strachenko** [comment]
Figured out. My bad. Sorry:)

**Comment by Crise420WMT** [comment]
can you tell me why?possibly i encountered the same issue....

**Comment by andkhong** [comment]
i'm having similar issues as well

**Comment by BabakMN** [comment]
@Crise420WMT @andkhong that error comes from `getMIMEFromBuffer` function. Make sure you are passing correct image data to jimp. You may be passing an unsupported image type. I had the same issue when I was accidentally passing in an SVG file instead of PNG.
