### ISSUE TITLE
Does JIMP officially support Microsoft Edge?

### ISSUE THREAD

**Issue by ThisIsManta** [oliver-moran/jimp#244]
I'm asking this because I was running **browser/lib/jimp.min.js** inside a _web worker_ in **Microsoft Edge** and got an error `Cannot find module 'stream'`

Here is the screenshot: https://drive.google.com/file/d/0B8-tZt41ejcYUDNWNXJUQnJuYWs/view?usp=sharing

Note that, given the same code and environment, I _NEVER GOT THIS ERROR_ on Webkit-based browsers, such as **Chrome, Safari and Firefox**.

For Internet Explorer 11, I have found another error, but I will take a look later.

**Comment by NoPinky** [comment]
1st: as far as I know your question should be if MS Edge Javascript engine supports/implements all JavaScript features that jimp needs. Jimp is written purely in JavaScript and does not really care about what browser it runs on. And jimp is actually meant to be run primarily on the server side (nodejs).
2nd: the screenshot you shared needs permission to access.

**Comment by ThisIsManta** [comment]
Would you enlighten me how I could find `stream` module? The error must have been thrown when calling `require('stream')`, if I'm not mistaken.

I've updated the screenshot permission. Sorry.

**Comment by NoPinky** [comment]
I hardly code JS in/for browsers, so I'm not competent here. But I think this is what you need:
[http://browserify.org/](http://browserify.org/ )
this will give you the needed module file for the use in browser.
a tutorial is here:
[https://scotch.io/tutorials/getting-started-with-browserify](https://scotch.io/tutorials/getting-started-with-browserify)

hope this helps
