### ISSUE TITLE
Detecting rectangles

### ISSUE THREAD

**Issue by chungtinhlakho** [oliver-moran/jimp#246]
I'm trying to process images to find the scorebox of a game, football, basketball..., can this detect scorebox on the corners of the screen, sometimes top and sometimes botom?

thanks

**Comment by Disorrder** [comment]
+1 I need very similar feature. It will be very useful to find subimage in image

**Comment by NoPinky** [comment]
this is a framework that allows you to manipulate images with simple filters and also gives you access to pixel datas. But it does not do processing stuff in the means of computer vision or any kind of "smart" recognition. For those kind of things you have to do it yourself from the pixel data if you can, or you have to look elsewhere for another framework.
