### ISSUE TITLE
[Question] Best performance

### ISSUE THREAD

**Issue by scriptPilot** [oliver-moran/jimp#248]
Hi Oliver,

thank you for the great lib! I have a performance question.

Task: Create several canvas with icon on it - Canvas and icons have not the same ratio.

Ideas:
a) Loop icons, create canvas, resize icons, paste icons to canvas
b) Create canvas once / loop icons, resize canvas, paste icons to canvas
c) Create canvas once, paste icon once / loop icons, resize canvas, crop canvas

Which one should have the best performance?

Regards,

Dennis

**Comment by hipstersmoothie** [comment]
They will all have similar performance.
