### ISSUE TITLE
How to get curcu

### ISSUE THREAD

**Issue by sam4jips** [oliver-moran/jimp#249]
Why am I not getting circular profile picture using this code?

      Jimp.read('/profile_picture.png', function(err, profile_picture) {
        Jimp.read('/circle.png', function(err, circle) {
            profile_picture.mask(circle, 0, 0).getBase64(Jimp.MIME_JPEG, function (err, src) {
              var img = document.createElement("img");
              img.setAttribute("src", src);
              document.body.appendChild(img);
            });
          });
        });
      });

This is the circle image I am using and profile_picture is a square picture of the person... both are of the same size...
![circle](https://cloud.githubusercontent.com/assets/5034475/23831197/3e139a50-0742-11e7-9025-f1d27b0d1be8.png)

Why am I not getting circular profile picture using this code?
What I am getting is completely blacked out image...

I might be very wrong using this mask function but if somebody could explain to me how to use jimp to create circular profile picture?

**Comment by thewizarodofoz** [comment]
According to the docs here, what `Jimp.mask` does is: 
> masks the image with another Jimp image at x, y **using average pixel value**
So I believe this will not really give you what you want.

You can use simple CSS to achieve what you want, [here's an example](https://jsfiddle.net/thewizarodofoz/ok8g9vyu/).
