### ISSUE TITLE
Allow setting compression and filter for png files

### ISSUE THREAD

**Issue by selaux** [oliver-moran/jimp#25]
First time using your library and I have to say it's great.

Now to the point: As it's possible to set the quality of a jpg file, it would be cool if it's also possible to set some options for pngs, in my case the ```deflateLevel``` and ```filterType``` options if node-png would be required. You think that this would be a good addition?

If yes: What would the functions that implement this look like? I might take a shot at implementing if you'd like.

**Comment by oliver-moran** [comment]
Sounds like a great idea! And I see now that node-png supports it.

If you do a fork and follow a similar pattern used for JPEGs I'll pull in
your changes.

**Comment by neophob** [comment]
I think it make sense to create a separate function to define png specific encoding options - as there are two options. is that ok?

**Comment by oliver-moran** [comment]
Makes sense.

**Comment by oliver-moran** [comment]
This should be pretty simple now that we are using pngjs2: https://www.npmjs.com/package/pngjs2

**Comment by oliver-moran** [comment]
This is all done now. Thanks a lot!
