### ISSUE TITLE
Composite gets wrapped in latest build

### ISSUE THREAD

**Issue by Ratismal** [oliver-moran/jimp#251]
Salutations,

Installing Jimp from the github repo (`npm i oliver-moran/jimp`) causes composites to act in an unwanted manner.

I have a relatively [simplistic script](https://github.com/Ratismal/blargbot/blob/master/worker.js#L272-L330) that does the following:
1. Create an empty canvas `new Jimp(256, 256)`
2. Composites two images with slightly random coordinates (to create a 'jitter' effect)
3. Repeat the process several times
4. Turn them into a gif using GIFEncoder.

Output from NPM build:
![NPM build output](https://cdn.discordapp.com/attachments/197529405659021322/291300171076075520/triggered.gif)

Output from Github build:
![Github build output](https://cdn.discordapp.com/attachments/197529405659021322/291299770624901120/triggered.gif)

I do not want my composite outputs to wrap when portions go off the screen. Rather, I want them to be cropped to the canvas's size as they used to. Please either resolve this or implement as an optional parameter.

**Comment by hipstersmoothie** [comment]
@Ratismal does this still happen? What version did it work in?

**Comment by Ratismal** [comment]
I have no idea. I tried making a new script to test with (since the old one no longer exists), but after installing `npm i oliver-moran/jimp` I get the error `Cannot find module 'jimp'`. This doesn't happen when installing the NPM release.

**Comment by hipstersmoothie** [comment]
The builds are no longer hosted in the repo. Just rpm link the module and
run ‘NPM run build’

**Comment by Ratismal** [comment]
Can't get it to build, but wrote a script anyways for testing.
```js
const Jimp = require('jimp');

async function main() {
    let parent = new Jimp(100, 100, 0x000000FF);
    let child = await Jimp.read('https://i.imgur.com/S2TMaa9.jpg');

    parent.composite(child, -50, 0);

    parent.write('out.png');
}

main().then(() => {
    console.log('Finished');
}).catch(err => {
    console.error(err);
})
```
when run, this should be the resulting out.png file:
![out](https://user-images.githubusercontent.com/1059362/43436274-eac89caa-9440-11e8-9cd4-9439d755e955.png)

if the issue still exists, you'll get something like this:
![image](https://user-images.githubusercontent.com/1059362/43436288-0aef344e-9441-11e8-8794-9cd5c8ba386f.png)

**Comment by hipstersmoothie** [comment]
Thanks for the test case! I’m interested to see if you get build errors
though.

Steps to install:
npm i
npm run build

Do you get any errors?

**Comment by Ratismal** [comment]
```
D:\JS\jimp-test\node_modules\jimp>npm run build

> jimp@0.3.0 build D:\JS\jimp-test\node_modules\jimp
> npm run build:browser && npm run build:node:production && npm run build:module


> jimp@0.3.0 build:browser D:\JS\jimp-test\node_modules\jimp
> BABEL_ENV=production node tools/browser-build.js prepublish

'BABEL_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jimp@0.3.0 build:browser: `BABEL_ENV=production node tools/browser-build.js prepublish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jimp@0.3.0 build:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\AppData\Roaming\npm-cache\_logs\2018-07-31T03_32_24_285Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jimp@0.3.0 build: `npm run build:browser && npm run build:node:production && npm run build:module`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jimp@0.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\AppData\Roaming\npm-cache\_logs\2018-07-31T03_32_24_335Z-debug.log
```
Currently working off of a windows machine because my linux machine is at work, will try building on it tomorrow.

**Comment by hipstersmoothie** [comment]
Oh shit I don’t have a way windows machine. It looks like the environment
variables work differently on windows. Do you know how to set cli env bars
on windows? I thought it was a cross platform method

**Comment by hipstersmoothie** [comment]
Googling around a little I might have to put ‘set” in front of all the Babel envs. Can you try that out? Thanks for all the help!

**Comment by Ratismal** [comment]
was able to build after converting the scripts to windows-compatible calls. the scripts in question:
```json
  "scripts": {
    "lint": "npm run -s lint:src && npm run -s lint:tests && npm run -s lint:extra && echo Lint All Success",
    "lint:src": "xo src/*.js src/**/*.js !src/modules/*.js",
    "lint:tests": "xo test/*.js --global before",
    "lint:extra": "xo {tools,examples}/*.js",
    "test:browser": "set BABEL_ENV=test && set ENV=browser && set CHROME_BIN=\"$(which chrome || which chromium)\" && karma start --single-run",
    "test:browser:watch": "npm run -s test:browser start -- --auto-watch",
    "test:node": "set BABEL_ENV=test && mocha --require @babel/register",
    "test:node:watch": "npm run test:node -- --reporter min --watch",
    "test:node:coverage": "nyc npm run test:node",
    "test": "npm run -s test:node:coverage && npm run -s test:browser",
    "browser-build": "node tools/browser-build.js test",
    "build": "npm run build:browser && npm run build:node:production && npm run build:module",
    "build:debug": "npm run build:browser:debug && npm run build:node:debug",
    "build:module": "set BABEL_ENV=module && babel src -d es --source-maps",
    "build:node": "babel src -d dist/main --source-maps",
    "build:node:debug": "set BABEL_ENV=development && npm run build:node",
    "build:node:production": "set BABEL_ENV=production && npm run build:node",
    "build:browser": "set BABEL_ENV=production && node tools/browser-build.js prepublish",
    "build:browser:debug": "set BABEL_ENV=development && set ENV=browser && node tools/browser-build.js prepublish"
  },
```
in addition to using set, I had to separate calls with `&&`

im not sure how you'd make this compatible with both windows and linux

**Comment by hipstersmoothie** [comment]
Thanks! I’m not sure either but I’ll try tonight!

**Comment by hipstersmoothie** [comment]
Does the bug persist?

**Comment by hipstersmoothie** [comment]
I’ll be using the cross-env package. Now I know why we use it at work lol

**Comment by Ratismal** [comment]
the output looks fine, so i guess this bug is not longer occurring.

**Comment by hipstersmoothie** [comment]
Sweet!

**Comment by hipstersmoothie** [comment]
Thanks for all the responses and working with me 😁

**Comment by Ratismal** [comment]
no problem, was a pleasure
