### ISSUE TITLE
Write fails silently on errors if no callback provided

### ISSUE THREAD

**Issue by mikedaly** [oliver-moran/jimp#252]
If I pass a full path to the `.write` function but the directory doesn't exist, no exception is thrown, and no file is written.

I wouldn't expect `.write` to attempt to create the directory, but I would expect it to fail. The problem appears to be in the callback argument. I am calling write with no callback, but in that situation write is forcing there to be an empty callback (line 2301 of index.js). In the event of an error, the (empty) callback is called rather than throwing the error (line 83 of index.js).

If no callback is provided, then write should throw an exception. Instead, it just silently fails.

**Comment by mikedaly** [comment]
The problem appears to be in the callback argument. I am calling write with no callback, but in that situation write is forcing there to be an empty callback (line 2301 of index.js). In the event of an error, the (empty) callback is called rather than throwing the error (line 83 of index.js).

If no callback is provided, then write should throw an exception. As it stands, it just silently fails.

**Comment by oliver-moran** [comment]
Since 0.2.28 `image.write()` will attempt to create the directory. A little opinionated, sure, but also a literal interpretation of the developer instruction.

Can you check that this fixes your issue?

**Comment by Ojas-Gulati** [comment]
Should we close this?

**Comment by mikedaly** [comment]
Sorry I haven't gotten to testing the latest version. The code we previously had that triggered the previous bad behavior has since been refactored, so I can't just drop in the new version to verify.

I'm fine closing.
