### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [oliver-moran/jimp#253]
Hi @oliver-moran  , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We are going to host this library.

I know that after v0.2.22, we should add the files under `browser/lib`.
But before v0.2.21 include v0.2.21, what the files need to be added in cdnjs?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#10855

**Comment by oliver-moran** [comment]
Hi, @sufuf3. The only file needing hosting is https://github.com/oliver-moran/jimp/blob/master/browser/lib/jimp.min.js. Unfortunately, the latest build is broken. I'll ping you when all is working again.

**Comment by extend1994** [comment]
Hi @oliver-moran I saw there is 0.2.28 tag since four month ago. Was the problem solved? If it was solved, we can add this to CDNJS soon 😄

**Comment by hipstersmoothie** [comment]
@extend1994 @sufuf3 we now have a working version on npm 💯

we have:

* a browserified version under `browser`
* a babeled to es5 version under `main` in `dist`
* and esmodules version under `es`

**Comment by extend1994** [comment]
@hipstersmoothie Thanks a lot! 👍

**Comment by sufuf3** [comment]
Thank you.
