### ISSUE TITLE
does print function support hebrew? 

### ISSUE THREAD

**Issue by evfr** [oliver-moran/jimp#258]
Hi.
Does anybody know if the
"print" function supports hebrew? 

It seems that only the ascii text is written. Or i have to use another font?

Thank you 

Evgeny

**Comment by oliver-moran** [comment]
The default font files only contain ASCII. Other font files can be created using tools like this one: http://kvazars.com/littera/

Hope this helps.

**Comment by jacobggman** [comment]
@evfr Did you succeed to write in Hebrew on an image?
