### ISSUE TITLE
Rotate image on composite

### ISSUE THREAD

**Issue by houtwolf** [oliver-moran/jimp#259]
Hi, i have this code, how can i rotate the second image in the composite?

```javascript
    var i1 = Jimp.read("8L3NoJyT.jpg");
    var i2 = Jimp.read("SpHwyGBs.jpg");

    Promise.all([i1, i2]).then(images => {
        images[0].composite(images[1], Xpos, Ypos)
                       .write("output.jpg");
    });
```

**Comment by thewizarodofoz** [comment]
Do you mean rotating images[1] before compositing it over images[0]? 
If so, why not just do images[1].rotate(degrees) and then do images[0].composite?

**Comment by houtwolf** [comment]
@thewizarodofoz thanks for your help, but i already fixed it and i never closed this.

**Comment by k1ker** [comment]
Why this code is not working for me? I need to composite 2 imgs, but I don't know how :(
