### ISSUE TITLE
Revertable functions

### ISSUE THREAD

**Issue by octameter** [oliver-moran/jimp#26]
Currently, changes applied to a jimp object are not revertable. If you want to extract multiple sections from an image or something alike, this might help:
```
Jimp.prototype.save = function (cb) {
    this.oldBitmap = {}
    this.oldBitmap.height = this.bitmap.height + 0;
    this.oldBitmap.width = this.bitmap.width + 0;
    this.oldBitmap.data = new Buffer(this.bitmap.data);
    
    if (isNodePattern(cb)) return cb.call(this, null, this);
    else return this;
};

Jimp.prototype.revert = function (cb) {
    console.log(this)
    this.bitmap = _.extend(this.oldBitmap, {});
    
    if (isNodePattern(cb)) return cb.call(this, null, this);
    else return this;
};
```
Of course one has to keep an eye on the memory...

**Comment by oliver-moran** [comment]
You can use the clone method to create "save points", as follows:

    var image = new Jimp("./path/to/image.jpg", function (err, image) {
        var original = image.clone(); // clone "image"
        image.greyscale(); // makes "image" grey scale but "original" is unchanged
        image = original; // revert to "original"
    });

You can also use the clone method to make changes without affecting the original:

    var image = new Jimp("./path/to/image.jpg", function (err, image) {
        var alteredImage = image.clone().greyscale().invert(); // original "image" is unaffected
    });
