### ISSUE TITLE
write not writing 

### ISSUE THREAD

**Issue by lakamsani** [oliver-moran/jimp#261]
Hi, somehow this very simple test isn't working in my environment (jimp 0.2.27, node.js 7.9.0 on macOS Sierra 10.12.4 ). `newFile2` does not exist nor an error is printed after this code is run. 

```javascript

var Jimp = require("jimp");
Jimp.read('https://graph.facebook.com/10207748578225773/picture?type=large').then(function (lenna) {
  //let newFile = "/tmp/lena-small-bw" + lenna.getExtension()
  let newFile2 = "/tmp/lena-small-bw"
  lenna.resize(256, 256)            // resize
    .quality(60)                 // set JPEG quality
    .greyscale()                 // set greyscale
    .write(newFile2); // save
}).catch(function (err) {
  console.error(err);
});
```
The commented out line fails as it is unable to get the extension ( same issue as reported in  https://github.com/oliver-moran/jimp/issues/241). 

Debugger seems to show that the  URL was read ok. 
<img width="293" alt="screen shot 2017-04-22 at 7 32 40 pm" src="https://cloud.githubusercontent.com/assets/3322496/25310183/9bcef7d6-2793-11e7-8027-d7dab7e610f2.png">

Tried with a local file `Jimp.read('/Users/vamsee/Pictures/vamsee.jpg').then(function (lenna) {` and same problem.

**Comment by lakamsani** [comment]
When I use https://www.npmjs.com/package/node-thumbnail (which is built on top of Jimp) saving works. But `node-thumbnail` does not allow URLs. I hacked it to work with URLs while I try to analyze why it works via that that library but not via the above simple direct Jimp code.

**Comment by thewizarodofoz** [comment]
the `write` method accepts Node-style callback. If you pass the callback you could log the error:
`.write(newFile2, err => console.error('write error: ', err));`

When I ran your code the error I got was permissions error (because I didn't have a tmp folder - do you have that folder?).

**Comment by lakamsani** [comment]
@thewizarodofoz  thanks for checking out this issue as well. Adding that node style call back to write gave more info. 

```bash
write error:  Error: Unsupported MIME type: application/octet-stream
    at Jimp.throwError (/Users/vamsee/Development/OnKore/onkore-node/node_modules/jimp/index.js:82:43)
    at Jimp.<anonymous> (/Users/vamsee/Development/OnKore/onkore-node/node_modules/jimp/index.js:2309:36)
    at Jimp.getBuffer (/Users/vamsee/Development/OnKore/onkore-node/node_modules/jimp/index.js:2037:23)
    at Jimp.write (/Users/vamsee/Development/OnKore/onkore-node/node_modules/jimp/index.js:2308:10)
```

**Comment by lakamsani** [comment]
The problem in this case was the lack of a file suffix. It work with this change `let newFile2 = "/tmp/lena-small-bw.png"`
