### ISSUE TITLE
catching errors when reading  bad images

### ISSUE THREAD

**Issue by lakamsani** [oliver-moran/jimp#262]
Jimp is unable to read this image due to some problem with it. I was expecting the catch part of the promise to get executed but it does not causing the node process to simply exit. 
```javascript
let twImage = 'https://pbs.twimg.com/profile_images/716460168939044864/5VHBN3-i_normal.jpg'
Jimp.read(twImage).then(function (lenna) {
  console.log("image read")
}).catch(function (err) {
  console.error(err);
});
```

Here is the error from that code causing node process exit. The image URL does not give a 404 in the browser. 
```bash
Error: Could not find MIME for Buffer <https://pbs.twimg.com/profile_images/716460168939044864/5VHBN3-i_normal.jpg> (HTTP: 404)
    at Jimp.throwError (/Users/vamsee/Development/OnKore/onkore-node/node_modules/jimp/index.js:82:43)
```

**Comment by thewizarodofoz** [comment]
@lakamsani Not sure if I understood your issue, but I made this [RunKit playground](https://runkit.com/thewizarodofoz/jimp-catch-error) page to demonstrate that the catch clause **is** being executed.

**Comment by lakamsani** [comment]
@thewizarodofoz didn't know about RunKit playgrounds, thanks. And thanks for checking my issue out. I think I misinterpreted the exception printout as process exist as that was last the last piece of code in my test. Adding a non exception printout in the catch clause is helpful. We can close this.

**Comment by turakvlad** [comment]
@thewizarodofoz, hey. It looks like it works great for `0.2.27` (as I can see from [your RunKit playground](https://runkit.com/thewizarodofoz/jimp-catch-error)). But it doesn't work for `0.2.28` - [my RunKit playground](https://runkit.com/turakvlad/5aa826267420c8001256077c). Thanks for help!
