### ISSUE TITLE
html /special characters

### ISSUE THREAD

**Issue by tsabbay** [oliver-moran/jimp#266]
hi,
first: nice LIB!
my question is about special chars and hebrew..

did any one try to use any special characters, for example:
http://www.fileformat.info/info/unicode/char/2713/index.htm

also about Hebrew/arabic chars
and make it worked ?

any one (: ?

**Comment by vernondegoede** [comment]
I tried inserting the Euro symbol yesterday. Doesn't work though. When entering special (Unicode) characters Jimp simply ignores them.

**Comment by amitgur** [comment]
Just did it in Hebrew
Go to http://kvazars.com/littera/ create fnt and png file from your font.  Open the fnt font
replace this
 </chars>
</font>

with this
 </chars>
  <kernings count="0">
   </kernings>
</font>

Use that file as the font. On Hebrew, you will have to write the text from end to start.

**Comment by tsabbay** [comment]
tx amit, already found a different approache for our problem.

**Comment by vernondegoede** [comment]
@tsabbay What was your solution to this problem?

**Comment by tsabbay** [comment]
we rendered HTML and merge it as img on top if the original image..

**Comment by oliver-moran** [comment]
The standard font files are only basic ASCII. Additional fonts can be created online using tools like this: http://kvazars.com/littera/
