### ISSUE TITLE
read from url with custom headers

### ISSUE THREAD

**Issue by rwpino** [oliver-moran/jimp#267]
Hello, I want to use your library to load my image from a remote server thru http with custom headers and converted into base64 string,It is possible do it  right now?. if no will be super good if the method allow pass configurations headers

**Comment by syzer** [comment]
👍

**Comment by syzer** [comment]
you can workaround by 
send plain request with headers
get the buffer and mime type
and then jimp.read(buffer, mimetype)

**Comment by hipstersmoothie** [comment]
@rwpino @syzer v0.5.2 has a new constructor option that allows you to pass the headers. Can you try it out for me?

```js
await Jimp.read({ url: '...', headers: { ... } })
```

**Comment by hipstersmoothie** [comment]
confirmed that v0.5.2 solve this issue. Feel free to open another PR if you have further issues.
