### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by oliver-moran** [oliver-moran/jimp#276]
@aurium great work with all of those tests and getting the browser version working again. Thank you.

One important question: What version of node should we support? Features like `let` and destructuring assignment are supported in Node 4.x, which is still in maintenance support and used on a lot of servers: https://github.com/nodejs/LTS#lts-schedule1

Any suggestion on the best way to go about moving forward with this? Perhaps Babel? https://babeljs.io/

**Comment by thisconnect** [comment]
I would drop node v4 but create a nee major version of jimp. if one still uses node v4 or needs to support older browsers they can either use the last major version or use babel to transpile to es5.

**Comment by Iwasawafag** [comment]
Transpiling will be needed for browser version anyway, so why not to offer this for node too?

**Comment by thisconnect** [comment]
somewhat related
- https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/
- https://medium.com/@Rich_Harris/small-modules-it-s-not-quite-that-simple-3ca532d65de4

**Comment by aurium** [comment]
> Transpiling will be needed for browser version anyway, so why not to offer this for node too?
I was thinking on this, however that will be a problem for testing and a dependence reuse problem, as all modules are packed on the browser version. :-/

I believe the @thisconnect option is the best one.
> drop node v4 but create a nee major version of jimp.

**Comment by thisconnect** [comment]
I always forget about jimp in browser although modern browser understand let and const. these can not be polyfilled and have to be transpiled with babel and checked into git so it can be on a cdn, see #253

What browser/version should be supported?

**Comment by aurium** [comment]
About `let` and `const`, no problem... babel is [transpiling it](https://raw.githubusercontent.com/oliver-moran/jimp/master/browser/lib/jimp.js).

> What browser/version should be supported?

I want say _"the last year current"_, so we give one year to users to update without problems. If some service want more time it can freeze in some Jimp version.
(however i can't be sure if this is the best strategy)

**Comment by hipstersmoothie** [comment]
Since babel is transpiling it I beleive that supporting old node is really no problem. #473 should close this as it exposes the babeled version as "Main"
