### ISSUE TITLE
question: has anyone tested this in a react-native app?

### ISSUE THREAD

**Issue by npomfret** [oliver-moran/jimp#277]
Sorry, this isn't an issue but a question (wasn't sure where else I could ask)...

I'm thinking of implementing this in a react native app.  I'm concerned that some mobile devices that don't have a lot of memory might struggle with this library.  I'm making this assumption because I presume that the binary image gets converted to base64, which I understand takes up more memory than the binary would have.

Has anyone tried using using this api this on a mobile device?  Specifically cheap / low spec android devices.  

Are there operations to be avoided because they are more memory hungry?

**Comment by Iwasawafag** [comment]
Mobile devices will struggle for sure, I expect it to be painfully slow. UI of your app will likely remain responsive but event loop of javascript controlling it will be blocked for quite some time. Consider using native means of working with images if possible, those should be much faster. 

> I'm making this assumption because I presume that the binary image gets converted to base64

Not quite. Actually, not at all. There's no need to convert image to Base64, instead image is being read, decoded and stored in memory as array of pixels to allow you perform any operations on it. Once you finished it has to be encoded back to one of the formats, like JPEG or PNG. Encoding and decoding are computationally expensive and there's no avoiding it. Also javascript can't take advantage of multiple CPU cores while native code can. And it's just slower than native in general.

> Are there operations to be avoided because they are more memory hungry?

Currently JPEG in PNG image decoding uses more memory that it should. Operations like `Jimp#flip`, `Jimp#rotate` and `Jimp#resize` and possibly some others temporally allocate additional `width * height * 4` bytes of memory. But in case of handheld devices it's likely that CPU will be a bigger bottleneck.

**Comment by npomfret** [comment]
thank you!

**Comment by fxfactorial** [comment]
@Iwasawafag but will it work on RN in principle or does it assume existence of node APIs

**Comment by awreese** [comment]
Seconded... I'm also working on developing a RN app that renders elements into a SVG canvas and I'm looking for an image pre-processor that can allow me to crop sections of a base image into SVG Image elements.  So far this module has been the best (most complete and trustworthy) looking option.  Since it is pure JS I suspect it will be able to to do the job, albeit as you say, a little slower than something running natively.

**Comment by linjunshi** [comment]
Hi, 

When I try to use it in my react-native app it throws an error "Node's Buffer() not available", anyone know how to resolve this?

Thanks a lot

**Comment by fxfactorial** [comment]
The error is clear, you can’t use this package in a non node environment

**Comment by Xdabier** [comment]
as a previews experience I face no issues while implementing it in an ionic 3 app and worked perfectly on mobile, but while trying to use it in a react native app, it throws this error : `.../node_modules/jimp/index.js`: Module `fs` does not exist in the Haste module map
...`

**Comment by jdanbrown** [comment]
- @linjunshi Try https://github.com/parshap/node-libs-react-native to polyfill `Buffer` for react-native?
- @Xdabier Try one of the fs libs mentioned at https://github.com/parshap/node-libs-react-native to polyfill the node `fs` module?

**Comment by Xdabier** [comment]
@jdanbrown I'll try that, an comment the results as soon as possible!

**Comment by jasan-s** [comment]
@Xdabier  did you figure it out? I m trying to do something like this and it wont work in react-native(the other option is to add Jimp to my server and make API request but multiple API calls seems slower. I wanted to saeToCameraRoll rightaway:
```
     Jimp.read(buff).then(image => {
          image.pixelate(
            Math.floor(faceHeight * pixelationSize),
            faceLeft,
             faceTop,
             faceWidth,
            faceHeight,
          )
      })
```

**Comment by Xdabier** [comment]
@jasan-s as I found jimp requires too many node libraries to function, which I won't need across the app only for jimp to work, I got rid of it to use some already built for react-native image editing packages, such as react-native-image-cropper etc..
