### ISSUE TITLE
loadFont() doesn't work?

### ISSUE THREAD

**Issue by afterl1ght** [oliver-moran/jimp#283]
So I'm using npm version of jimp, and I just want to say, thank you for creating such a great image manipulation library! :+1: 

But, I'd like to ask that, about printing text to the image. I've used `Jimp.loadFont()` to load a Bitmap font so that it can write the text into the specified image (In this case I'm using PNG), and it does not work. Instead of exports an image with written text in it, it returns an image - Without text.

Here's the code:
```js
const Jimp = require("jimp");

Jimp.read("http://i.imgur.com/I3CrIh5.png").then(function (delimg) {
         Jimp.read(msg.author.avatarURL).then(function(dimg) {
             dimg.resize(114, 107);
             delimg.composite(dimg, 82, 86);
             Jimp.loadFont(Jimp.FONT_SANS_32_BLACK).then(function (font) {
                  delimg.print(font, 265, 89, "Test string");
             });
             delimg.write("./im/deloutput.png")
         })
         //Send the saved image
        msg.channel.send({file: "./im/deloutput.png"});
}).catch(err => {
          msg.channel.send("An error occured!~\n```js\n" + err + "```");
          console.error(err);
})
```
If this is a bug, or if I've done something wrong in this raw, please tell me. I'm still not experienced at this much. Welp, thanks for helping me!

**Comment by Iwasawafag** [comment]
You're trying to send file before it's finished writing to disk. Actually, even before avatar image is read and composited on top of background. Also you're not returning a promise from `.then()` callback, so only errors of the first operations will be catched there at the bottom.

I've answered to a _very_ similar question yesterday https://github.com/oliver-moran/jimp/issues/284#issuecomment-304537935, maybe you will find that comment useful

**Comment by NikoMasumi** [comment]
I will check it out. Thanks!

**Comment by hipstersmoothie** [comment]
change this 

```js
Jimp.loadFont(Jimp.FONT_SANS_32_BLACK).then(function (font) {
	delimg.print(font, 265, 89, "Test string");
});
delimg.write("./im/deloutput.png")
```

to this 

```js
Jimp.loadFont(Jimp.FONT_SANS_32_BLACK).then(function (font) {
	delimg.print(font, 265, 89, "Test string");
	delimg.write("./im/deloutput.png")
});
```
