### ISSUE TITLE
Is it possible to add a transparent mask to an image?

### ISSUE THREAD

**Issue by disordinary** [oliver-moran/jimp#29]
If I wanted an image to be a circle for instance I would do something like blit a png with a transparent middle and black outline, I would then blit a png or jpeg with a black middle and white outline using the OR Boolean operation.

**Comment by disordinary** [comment]
I've done it - really simple library you have there. Will send through a pull request.

**Comment by oliver-moran** [comment]
Sounds great. Sent it on.

**Comment by oliver-moran** [comment]
Will be available in next release.
