### ISSUE TITLE
Random noise in imported .gif file

### ISSUE THREAD

**Issue by Anagmate** [oliver-moran/jimp#290]
I tried reading a .gif image on the following URL: http://etesty2.mdcr.cz/Vestnik/GetImageQuestion/P2_6328164310901.gif

When I try to export it to any supported format (.png, .jpg, .bmp), I get a thin strip on the top of the image with randomly colored pixels. Problem is, everytime I reload and export the image, the pattern changes randomly.
When I try to export multiple types from same image object, the pattern is same in all of them, which leads me to believe that it's more of an import problem than export one (maybe some issue with omggif library?).

**Comment by jtlapp** [comment]
I've created a library ([`gifwrap`](https://github.com/jtlapp/gifwrap)) for working with GIFs that allows you to manipulate the images with Jimp. When I load your GIF into that library and write it out as a new GIF, I see no such artifacts.

You might try loading the image with `gifwrap` and saving it with Jimp to see if you still have the problem.

**Comment by hipstersmoothie** [comment]
I have tested the gif and it works find in jijmp exporting to png. I'm gonna assume omggif fixed something. Feel free to open another issue if the problem persists
