### ISSUE TITLE
Jimp compression is causing wrong colors

### ISSUE THREAD

**Issue by bennyn** [oliver-moran/jimp#292]
In [Wire's web application](https://github.com/wireapp/wire-webapp) we are using Jimp to compress images:

```js
Jimp.read('./img/image.jpg').then((image) => {
  if ((image.bitmap.width > MAX_SIZE) || (image.bitmap.height > MAX_SIZE)) {
    image.scaleToFit(MAX_SIZE, MAX_SIZE);
  }

  if (image.bitmap.data.length > MAX_FILE_SIZE) {
    image.quality(COMPRESSION);
  }

  return image.getBuffer(Jimp.AUTO, (error, data) => {
    const blob = new Blob([data], {'type': 'image/png'});
    const url = URL.createObjectURL(blob);
  });
});
```

One of our user's realized (https://github.com/wireapp/wire-webapp/issues/1272) that [his image](http://imgur.com/dhfszaG) gets strange colors when we compress it with Jimp.

I built a demo that showcases the problem: https://bennyn.github.io/jimp-issue/index.html

Test code is available here: https://github.com/bennyn/jimp-issue

**Comment by DoomTay** [comment]
This might be related to #243

The problem seems to lie with jpeg-js. There are a few more test cases [here](eugeneware/jpeg-js#23)

**Comment by hipstersmoothie** [comment]
closing in favor of #243
