### ISSUE TITLE
Using custom characters doesn't seem to work

### ISSUE THREAD

**Issue by ThuverX** [oliver-moran/jimp#295]
I'm still not sure if this has something to do with Jimp but, I'm trying to display my username (₮ҤЏѴΞ₹Ӿ).
When i check if the username is not empty (By console.log() -ing it and checking it). Its not empty but when using bg.print(font1, 16, 13, username); It does not work. I also checked if it was the font, It was not trying a custom font in Jimp resulted in empty. But in photoshop it was fine (mostly). I even checked using just normal text (ThuverX) and it worked. Is this a bug or something I can fix myself.

```javascript
function sendProfile(username,userimage,maxXP,xp,background,lv,callback){
    console.log(username); //₮ҤЏѴΞ₹Ӿ
    Jimp.read("template.png", function (err, template) {
        Jimp.read(userimage, function (err, userImage) {
            Jimp.loadFont(Jimp.FONT_SANS_32_BLACK).then(function (font1) {
                Jimp.read("xp.png", function (err, xpBar) {
                    Jimp.loadFont(Jimp.FONT_SANS_16_WHITE).then(function (font) {
                        Jimp.read("bg/" + background + ".jpg", function (err, bg) {
                            userImage.resize(120,120);
                            bg.cover(400,176);
                            bg.composite(template,0,0);
                            bg.print(font1, 16, 13, username); //empty 
                            bg.composite(userImage,267,13);
                            xpBar.color([
                                { apply: 'hue', params: [ 0 ] }
                            ]);
                            bg.blit(xpBar,267,133,0,0,120/maxXP*xp,16);
                            bg.print(font, 269, 132, "LEVEL " + lv);
                            bg.crop(0,0,400,176).write("profile.png",function(){
                                callback();
                            });
                        });
                    });
                });
            });
        });
    });
}
```

Very bad code I know, but just so you can see

**Comment by ThuverX** [comment]
Nevermind already found the problem

**Comment by t2krew** [comment]
@ThuverX how do u solve this problem? I also wanna to write the custom characters but was failed :-(

**Comment by ThuverX** [comment]
@t2krew, someone else said this and i followed it.
The standard font files are only basic ASCII. Additional fonts can be created online using tools like this: http://kvazars.com/littera/.

So grab your font put it in there, make sure you select all characters. And ofcourse tweak it to your liking. Then download it and just load it via `jimp.loadfont` . Hope this helpes.
