### ISSUE TITLE
Support to compare image against a database of hashes?

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#299]
I need to compare an image to a list of pre.calculated images hashes (`Jimp.hash()`).
I would like to use both `Jimp.distance()` and `Jimp.diff()`.
I.e: Is there any support to match an image against a (potentially BIG) list of saved images, without having to read every image in the list (and recalculate it's hash) again?

**Comment by DoomTay** [comment]
You could have the hash of each image stored in a list and read that.

**Comment by marcolino** [comment]
Of course. But - I mean - I need methods like Jimp.distanceFromHash(hash) and Jimp.diffFromHash(hash), which are now unavailable... :-(

**Comment by hipstersmoothie** [comment]
`diff` doesn't use phash so you can use a phash to calculate it.

**Comment by hipstersmoothie** [comment]
Released in [v0.4.0](https://github.com/oliver-moran/jimp/releases/tag/v0.4.0)
