### ISSUE TITLE
work synchronously ?

### ISSUE THREAD

**Issue by yoyoy** [oliver-moran/jimp#3]
Hello
is it possible to wait the end of my job to continue my script ? 
there is a callback function ? 

thanks a lot !

**Comment by oliver-moran** [comment]
Sure. You can do this now like this:
    
    var lenna = new Jimp("lenna.png", function () {
        this.flip(true, false).write("lenna-flip.jpg");
        done();
    });

    function done(){
        console.log("Done!");
    }

Does this satisfy your needs?
