### ISSUE TITLE
choose the padding (letter box) color when using `image.contain`

### ISSUE THREAD

**Issue by akhoury** [oliver-moran/jimp#304]
is there a way to do that today?
```javascript
// something like 
image.contain( w, h[, alignBits || mode, mode, {color: 'blue'}] );  

```
thanks

**Comment by ChenYuHo** [comment]
You could find the following description in README.md:
`image.background( hex );          // set the default new pixel colour (e.g. 0xFFFFFFFF or 0x00000000) for some operations (e.g. image.contain)`

**Comment by hipstersmoothie** [comment]
@ChenYuHo that is the solution. Thanks for this answer!
