### ISSUE TITLE
Jimp.create instead of new Jimp for clearer syntax [Feature request] [Breaking change]

### ISSUE THREAD

**Issue by Haocen** [oliver-moran/jimp#308]
Currently, in order to create new image, one need to do:
```
var newImage = new Jimp(256, 256, function (err, image) {
    // this image is 256 x 256, every pixel is set to 0x00000000 
});
```
but this code is horrible, the `newImage` itself is undefined forever, not even a promise. I propose to change to following:
```
Jimp.create(256, 256),then((img) => {
    img.write(path);
    // this image is 256 x 256, every pixel is set to 0x00000000
}).catch(err => console.dir(err));
```

Update:

I think sync version can still stay this way:
```
var newImage = new Jimp(256, 256);
// this image is 256 x 256, every pixel is set to 0x00000000 
```
but async version should be deprecated and removed from doc as the reason I described above.

**Comment by Ojas-Gulati** [comment]
hmmm, I'll see if I can do something about that.

That would be a much cleaner syntax.....

**Comment by Haocen** [comment]
For now, I think fixing the doc and deprecate the async version(by adding a warning whenever called) would be suffice.

**Comment by tamminh** [comment]
You can wrap the current "new Jimp" function with Q.defer() to create a promise!
