### ISSUE TITLE
How to create a transparent image

### ISSUE THREAD

**Issue by mikehchuck** [oliver-moran/jimp#310]
Hello,

I'm trying to create a blank transparent Jimp image, but it always has a color value. I tried using the opacity method, but it doesn't seem to work.

Here is my code: 

```
var mainImage = new Jimp(caseWidth, caseHeight, function (err, image) {
     image.opacity(0, function(err, image) {
          image.write(caseImage);
     });
});
```

It creates the new image, but it is all black and will not become transparent.
I have tried using both the mainImage and reading the caseImage again, but they are both all black.

Is there something I am missing?

Thanks.

**Comment by Netox005** [comment]
You can add an optional background color argument to the Jimp constructor:
```js
var mainImage = new Jimp(caseWidth, caseHeight, 0x0, function (err, image) {
    // do stuff with image
});
```

(`0x0 = 0 = rgba(0, 0, 0, 0)`)

**Comment by mikehchuck** [comment]
@Netox005 , thanks! I have found the real problem though. After I create the image I composite some other images over it, everything is fine (the background is still transparent), but when I resize the image, the background turns black. Here's my code:

`image.resize(generate.settings.params.resize_large, Jimp.AUTO).quality(100).write(fullLargeCase, function() { //Some other stuff goes here});`

**Comment by mikehchuck** [comment]
Turns out you can't have a transparent jpg... Thanks!

**Comment by Ojas-Gulati** [comment]
Close this?

(sorry for my nagging cleanup posts :/)

**Comment by mikehchuck** [comment]
Yes you can close this. Thanks!

**Comment by ashadnasim52** [comment]
Any way to turn it transparent
