### ISSUE TITLE
how can i get more fonts like japanese or chinese?

### ISSUE THREAD

**Issue by x1911** [oliver-moran/jimp#323]
do you guys have some link to download?
i cant find it anywhere,  thanks for your help...

**Comment by Ojas-Gulati** [comment]
Jimp uses bitmap fonts.

I found these japanese fonts - http://openlab.ring.gr.jp/efont/japanese/index.html.en

Load them into jimp with `jimp.loadFont`

**Comment by Ojas-Gulati** [comment]
</close>

**Comment by x1911** [comment]
thank you very much, thats very helpful,and anywhere i cant find chinese,Jimp can load another font format in next version?or use canvas make font is allow?

 

    Ojas-Gulati <notifications@github.com> schrieb am 16:24 Mittwoch, 16.August 2017:
 

 Jimp uses bitmap fonts.I found these japanese fonts - http://openlab.ring.gr.jp/efont/japanese/index.html.enLoad them into jimp with jimp.loadFont—
