### ISSUE TITLE
Monochromatic Plugin

### ISSUE THREAD

**Issue by eptaccio** [oliver-moran/jimp#324]
is it possible to change an image to monochromatic using jimp?

**Comment by Ojas-Gulati** [comment]
Yes, use image.greyscale()

**Comment by hipstersmoothie** [comment]
I was gonna make this into a plugin. But I found I could do it in one line. If you first convert the image to greyscale you can then uses the `color` function to mix in whatever color your want.

```js
const Jimp = require('jimp');

test();

async function test() {
    const image = await Jimp.read('./exampleImages/cops.jpg');

    image.greyscale().color([{ apply: 'mix', params: ['#90b6ff'] }]);

    image
         .greyscale()
         .color([{ apply: 'mix', params: ['#90b6ff'] }]);
         .writeAsync('test.png');
}
```
