### ISSUE TITLE
Should increment version number & resubmit to npm 

### ISSUE THREAD

**Issue by kenning** [oliver-moran/jimp#326]
The version I downloaded from NPM has the same version number as this github repository, but on github there are extra features. The one that impacted me was here: https://github.com/oliver-moran/jimp/blob/master/index.js#L2639 In the version of jimp on npm, you can't align text horizontally (a really awesome feature!)

I just forked this repo to use in my project, but you should consider simply incrementing the version number and resubmitting to npm.

BTW, this seems like a great library and does everything I wanted it to very easily, and the source code is very easy to read. Thanks

**Comment by itslenny** [comment]
I noticed the same thing. There is no text alignment in the NPM version despite having the same version.

**Comment by hipstersmoothie** [comment]
closing as there are many other issues covering this
