### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by chrishawn** [oliver-moran/jimp#33]
I would love to have .cover and .contain features like lwip has which mimic the CSS cover and contain image size settings

**Comment by oliver-moran** [comment]
Sounds good. Can whip that up.

**Comment by numtel** [comment]
Here's a work around for how to do "cover" with the current features:

In the following code, `options.width` and `options.height` contain the final size.

```javascript
new Jimp(input, function(error, image) {
  if(error) throw error;
  // Crop image to same ratio as output
  var ratio  = Math.min(
    image.bitmap.width / options.width,
    image.bitmap.height / options.height);
  var offsetX = (image.bitmap.width - (options.width * ratio)) / 2;
  var offsetY = (image.bitmap.height - (options.height * ratio)) / 2;  
  image.crop(offsetX, offsetY,
    image.bitmap.width - (offsetX * 2),
    image.bitmap.height - (offsetY * 2)
  );
  image.resize(options.width, options.height);
      
  // image is now covering the new dimensions
});
```

I'm not 100% sure but I would think "contain" would simply be a matter of switching `Math.min` with `Math.max`.

**Comment by oliver-moran** [comment]
Done. Added `image.cover(w, h)` and `image.contain(w, h)`. Thanks for the suggestion.
