### ISSUE TITLE
'Access-Control-Allow-Origin' when fetching the image

### ISSUE THREAD

**Issue by nitin42** [oliver-moran/jimp#331]
I am getting this error 'Access-Control-Allow-Origin' when fetching an image with `Jimp.read(url)` in browser. Any idea how I can resolve this ?

**Comment by Ojas-Gulati** [comment]
This isn't a problem with Jimp - this is network error with the page that you are trying to access - take a look at https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

/close

**Comment by jakubladra** [comment]
Hi @nitin42. How did you fix this? It's likely that it truly doesn't relate to Jimp itself but I've faced this CORS error from AWS S3 and I'm running out of ideas on how to fix it. Thanks!
