### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by kolbma** [oliver-moran/jimp#336]
There is no commit since June and there are pull requests which don't get any comments.

**Comment by maqboolkhan** [comment]
I guess not 😄 but Jimp needs contributor see this post of oliver https://github.com/oliver-moran/jimp/issues/219 after that @aurium and @Iwasawafag was actively taking care of this project but as they are also contributors so we seen last activity on Jan 17 so don't if u can help you should take initiative.
Best

**Comment by Ojas-Gulati** [comment]
I agree with @kolbma 
Pull requests is a barren wasteland and I would *like* to see the issues to be smaller.

:(

**Comment by me-12** [comment]
I fear you are right. I can't even bring myself to write a pull request since I know, no one is going to review it anyways.

**Comment by Tiendq** [comment]
So, is there any active fork? where at least others could contribute to fix bugs :)

**Comment by Ojas-Gulati** [comment]
hmmmm.......
Someone should make that - I'll see if I can put together something

**Comment by hipstersmoothie** [comment]
We're still alive! I just took over the project so PR til your heart's content.  @kolbma @maqboolkhan @Ojas-Gulati @me-12 @tiendq
