### ISSUE TITLE
Image will auto rotate while write to disk

### ISSUE THREAD

**Issue by koiszzz** [oliver-moran/jimp#339]
code:
>`Jimp.read(file),then(function(image){`
`           image.write(newfile)`
>`})`

while I call this function to rewrite image, some pictures will auto rotate . What should I do to keep the origin orientation of the images. Help , Thanks .

**Comment by BoussonNicolas** [comment]
I have the same weird problem

**Comment by BoussonNicolas** [comment]
I found a solution which is to make a exifRotate before the write:
image.exifRotate(function(err, image){
    image.write(dirname, function(err){

**Comment by hipstersmoothie** [comment]
closing in favor of #214. Whats happening is your image has exif orientation encoded into it and jimp autorotates your image according to that orientation
