### ISSUE TITLE
Can use font file oft?

### ISSUE THREAD

**Issue by vominhtam** [oliver-moran/jimp#341]
Hi all,

Now I want to use a new font extension .oft. But when I use function Jimp.loadFont() it displat error.

(node:13472) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: no named row at line 4
(node:13472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I not sure I can use file .oft.

thank all so much

**Comment by Ojas-Gulati** [comment]
Jimp only supports bitmap fonts with the extension .fnt

/close
