### ISSUE TITLE
Error Writing Image to File

### ISSUE THREAD

**Issue by chpoulio** [oliver-moran/jimp#343]
Hello,

I am attempting to use Jimp to perform simple edits to an image and then write that image out to a new file on a file system.  I took the "example1.html" file that comes with the Jimp library and modified it slightly so that it writes to a file.  The code can be found attached.  I think it is able to read the image, but it breaks on the ".write" function stating "Uncaught TypeError: lenna.write is not a function".  Am I doing something wrong?  I'm using Chrome and version v0.2.27 of jimp.

[example1.txt](https://github.com/oliver-moran/jimp/files/1297122/example1.txt)

**Comment by sylvery** [comment]
Hi @chpoulio try this:
`        	Jimp.read("lenna.png").then(function (err, lenna) {
    			if (err) throw err;
    			lenna.write("lena-small-bw.jpg"); // save
			});
`

**Comment by chpoulio** [comment]
Thanks for the response.  I ended up going a different direction though.
