### ISSUE TITLE
Error: There are some read requests waiting on finished stream

### ISSUE THREAD

**Issue by super9user** [oliver-moran/jimp#344]
Steps to reproduce: 
I am reading a image from a buffer -> cropping it -> getBuffer() on cropped image -> reading image from that buffer (at this point I get this error).

I tried upgrading to `pngjs2` dependency locally, but that doesn't seem to help.

Is there anyway around this?

**Comment by super9user** [comment]
Too soon to create an issue, a mistake from my side.

**Comment by callmekatootie** [comment]
@super9user What was the mistake?
