### ISSUE TITLE
Source must be a Jimp image

### ISSUE THREAD

**Issue by sahil505** [oliver-moran/jimp#351]
I'm trying to use the `image.composite()` function like this -

`Jimp.read("assets/img/image1.jpg").then(function (image) {
    // do stuff with the image
    image.composite("assets/img/image2.png", 20, 20);
	}).catch(function (err) {
	    // handle an exception
	    console.log(err);
	});`

But I get an error saying that source must be a Jimp image.
Can anyone help me with this?

Thanks.

**Comment by sahil505** [comment]
Even if I do this -
`Jimp.read("assets/img/image1.jpg").then(function (image) {
var jimpImage = Jimp.read("assets/img/image2.png");
    // do stuff with the image
    image.composite(jimpImage, 20, 20);
	}).catch(function (err) {
	    // handle an exception
	    console.log(err);
	});`

It still shows the same error. 
Can anyone help?

**Comment by tamminh** [comment]
Please use nested promise chain!

**Comment by sylvery** [comment]
@sahil505 I ran into the same problem a few months back and I managed to solve it by simply declaring my composite file as a variable within app.js. So in my app.js file for example, I have this:
`
...
var logo = new jimp('public/tmp/my_watermark.png', function (err, img) {
	err ? console.log('logo err' + err) : console.log('logo created and ready for use');
	return img.opacity(0.3);
});
...
`
And then somewhere down the line where I have an API exposed to handle and process uploaded images, I have something like this:
`
...
	jimp.read(__dirname + '/public/tmp/' + filename) // where filename comes from the api call i.e.: '/api/watermark/:filename'
			.then((image)=>{
				image.clone()
					.resize(805,jimp.AUTO)
					.crop(0,0,805,450)
					.composite(logo, 25, 20)
					.write(__dirname + '/public/tmp/slider-01.jpg', (err, success)=>{ err ? console.log(err) : console.log('image resized and saved successfully\n'+success)});
			});
...
`
hope this helps
