### ISSUE TITLE
Jimp stucking at a corrupted GIF file

### ISSUE THREAD

**Issue by nodegin** [oliver-moran/jimp#353]
I found this GIF file will cause Jimp stuck forever (right click to save):

![1](https://user-images.githubusercontent.com/8536244/31270690-f313f558-aab7-11e7-9d3a-7eaeb1cfb307.gif)

Code snippet for reproducing this issue:
```js
const Jimp = require('jimp')

Jimp.read(`1.gif`, (err, image) => {
  console.log(image, err)
})
```

**Comment by jtlapp** [comment]
Thanks for this. I'm writing a package that adds GIF support to Jimp by wrapping it, will see if I can fix it in my wrapping module.

**Comment by jtlapp** [comment]
omggif.js is hanging. The GIF appears to be ill-formed, but the decoder shouldn't be hanging. I think it's fair to simply reject the image. I'll look into it.

No one is maintaining Jimp any more, but I'll be able to fix it from my GIF wrapper. You don't want to be using Jimp directly for GIFs anyway.

**Comment by nodegin** [comment]
@jtlapp Nice work for finding out what the problem is.

**Comment by jtlapp** [comment]
I've provided GIF support and a working decoder in [`gifwrap`](https://github.com/jtlapp/gifwrap). Thanks for finding the bug and providing a test case.

**Comment by hipstersmoothie** [comment]
@jtlapp any reason why you didn't try to add GIF support directly to jimp?
