### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by SevenZark** [oliver-moran/jimp#354]
I am using Meteor with React. I installed Jimp, didn't change any of my code, and just launched the app. I get the error below. The error stack references line 3 of image-upload-input.jsx in my app, which is just this:

> var Jimp = require('jimp')

The error:

> Uncaught ReferenceError: Buffer is not defined
>     at is-binary.js (modules.js?hash=83298c5e1461c12daca6f8d97176a62c787877f1:130202)
>     at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
>     at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
>     at browser.js (modules.js?hash=83298c5e1461c12daca6f8d97176a62c787877f1:130098)
>     at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
>     at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
>     at index.js (modules.js?hash=83298c5e1461c12daca6f8d97176a62c787877f1:80101)
>     at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
>     at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
>     at image-upload-input.jsx (image-upload-input.jsx:3)

**Comment by derekaug** [comment]
Believe this is an issue with the current release of jimp, if you install the the previous version I don't think this will happen.

**Comment by skddc** [comment]
Confirmed that this is not an issue in `0.2.27`, but it is in `0.2.28`.

**Comment by hipstersmoothie** [comment]
closing in favor of #280
