### ISSUE TITLE
PNG quality is effecting

### ISSUE THREAD

**Issue by ali-abbas-10p** [oliver-moran/jimp#357]
![firebase_snapshot](https://user-images.githubusercontent.com/27349017/31702892-39086960-b3f3-11e7-95bb-91ec39220dc4.png)
This the original image, after resizing it to 640x410 I am getting below image.
![firebase_snapshot](https://user-images.githubusercontent.com/27349017/31702913-5dd20ec2-b3f3-11e7-9850-c2ed50f32f74.png)

I can see my image getting pixelated.
Can you please help?

Below is the code that I have written.
```javascript
var wh = imageHelper.getWidthAndHeight(aspectRatio,_widthDp,_heightDp,screenType);
orignalImage.quality(100).resize(wh.width,wh.height,imageResizedCallback);
```

**Comment by aadunn** [comment]
Have you tried resizing with a different resizing algorithm? The following are supported:
```
Jimp.RESIZE_NEAREST_NEIGHBOR;
Jimp.RESIZE_BILINEAR;
Jimp.RESIZE_BICUBIC;
Jimp.RESIZE_HERMITE;
Jimp.RESIZE_BEZIER;
```

**Comment by bruno-serfe** [comment]
Same issue here, after resize my jpg image is blurred and pixelated with some other options... What's the issue?

**Comment by ali-abbas-10p** [comment]
Actually, it was not the issue with the library. I was stretching image larger than its resolutions in the preview of that image.
I replaced <img style="width=100%/> with <img style="width=auto/>.
It solved my issue.

**Comment by bruno-serfe** [comment]
@ali-abbas-10p The generated image from a good quality image is blurred and pixelated doesn't matter the option I use, always is generated in that way.. In my case I'm just opening the generated image with a viewer not html yet.

**Comment by hipstersmoothie** [comment]
I you resize an image too much smaller it will be blurry/pixelated no matter what. A smaller bitmap can only represent so many pixels, so you are bound to loose on image quality a little.  

Using the example image above I got the best result using RESIZE_BILINEAR.
