### ISSUE TITLE
async but no .then?

### ISSUE THREAD

**Issue by SuperOP535** [oliver-moran/jimp#360]
when I .write my image to a file and I try to send it to a channel instantly after that it doesn't work, when I try to .write(etc.).then(etc.) it says image.rotate(...).write(...).then is not a function and when I do setTimeout(etc.,5000) it works but I don't want 5 second delay, I want to send instantly after file is created

**Comment by SuperOP535** [comment]
I also tried .write(etc., etc.) but it crashed

**Comment by SuperOP535** [comment]
never mind I used function(){ etc. } and it worked.. BTW, any variables in the function? like image name etc.

**Comment by clusteratlas** [comment]
.write(etc., function(){ 
console.log(arguments) 
 })

cheers
