### ISSUE TITLE
JPEG Quality doesn't work

### ISSUE THREAD

**Issue by ElijahZAwesome** [oliver-moran/jimp#364]
When I try to edit the JPEG quality it doesnt do anything, no matter if the input is a jpeg or png. It outputs fine but the quality is the same

**Comment by tobyfee** [comment]
Hi @ElijahZAwesome this appears to be working for me, when calling `image.quality(100, function(image){write})` I get very different results when using a quaility of 5, 50, or 100. 

![radicalgardener1471805970](https://user-images.githubusercontent.com/585019/32400335-0d33e7d0-c0bc-11e7-8995-7907a5d17a64.jpg)
![radicalgardener1419017808](https://user-images.githubusercontent.com/585019/32400336-0d4ccd5e-c0bc-11e7-9625-f8c9ad80b455.jpg)
![radicalgardener1430687202](https://user-images.githubusercontent.com/585019/32400338-0d6b317c-c0bc-11e7-9893-dc8ba3e2d454.jpg)

See attached results

**Comment by ElijahZAwesome** [comment]
Yeah, im sorry about that lol, turns out you have to export as JP_E_G and not JPG, I didn't realize that... sorry lol
