### ISSUE TITLE
Support for EMF format ?

### ISSUE THREAD

**Issue by edi9999** [oliver-moran/jimp#366]
Would it be possible to add support for the [EMF format](https://en.wikipedia.org/wiki/Windows_Metafile) ?

**Comment by hipstersmoothie** [comment]
@edi9999 this would be a good candidate for a plugin that isn't included in the default jimp. Do you know of any npm packages the are emf encoder/decoders?

**Comment by edi9999** [comment]
There seems to be a beginning of conversion from emf to canvas : https://github.com/g21589/wmf2canvas/blob/master/js/wmf.js

I'm closing this since probably nobody else is going to want this feature and I don't particulary need it anymore.
