### ISSUE TITLE
how to create rounded images 

### ISSUE THREAD

**Issue by sol0matrix** [oliver-moran/jimp#369]
Excellent module currently i am unable to figure out how to create rounded images using this however  
 with sharp overlayWith method i can create rounder corners with the code snippet from sharp Example below. 

`const roundedCorners = new Buffer(
  '<svg><rect x="0" y="0" width="200" height="200" rx="50" ry="50"/></svg>'
);

const roundedCornerResizer =
  sharp()
    .resize(200, 200)
    .overlayWith(roundedCorners, { cutout: true })
    .png();`

How can i achieve the same results ?
My use case is for user notifications thanks in advance
![notification-demo](https://user-images.githubusercontent.com/32850265/33391667-b9856aea-d507-11e7-96fd-dd4cfe57f5fd.png)

**Comment by hipstersmoothie** [comment]
```js
const Jimp = require('jimp');

test();

async function test() {
  const image = await Jimp.read('./exampleImages/image.jpg');
  const mask = await Jimp.read('./exampleImages/circle-mask.png');

  image.mask(mask, 0, 0).write('masked.png', console.log);
}

```

**Comment by sol0matrix** [comment]
Thanks for pointing me in the right direction however im currently using node v6.12.0  async is not able for that version so the code below was my workaround. 

Thanks again :) 

```
``
var content = Jimp.read('/images/content.png');
var circle = Jimp.read('/images/mask.png');

Promise.all([content, circle]).then(function(images) {
    var mainPhoto = images[0];
    var mask = images[1];
    // Important ! resize to match mask image size w512 h512
    mainPhoto.resize(512, 512);
    mainPhoto.mask(mask, 0, 0).write('/images/masked.png');
});
```

**Comment by Pradnya136** [comment]
Hi, how can we round corners of an image using jimp as we do in HTML by setting border-radius. Any idea or help is really appreciated.
The output should be like below:
![image](https://user-images.githubusercontent.com/43560888/66984087-acd84400-f0d7-11e9-973a-8566d4ccfb3b.png)

**Comment by lucyyyyyyy** [comment]
The above rounded corners (similar to border-radius) is possible now or is it still not? From my quick look at the circles plugin it seems like that is not how it works, and while a mask will work for fixed size images, it does not work with variable size images.
