### ISSUE TITLE
support promises

### ISSUE THREAD

**Issue by aeosynth** [oliver-moran/jimp#37]
if a callback is not passed where expected, return a promise. this way both node-style callbacks and promises are supported.

edit: at least for the constructor

**Comment by oliver-moran** [comment]
I agree the constructor is awkward, though. I'm just not sure what a promise would add.

For example, this is what we have at present:

```js
var lenna = new Jimp("lenna.png", function (err, image) {
    this.resize(256, 256).quality(60).write("lenna-small.jpg");
});
```

With a promise would it look like:

```js
var lenna = new Jimp("lenna.png").then(function (err, image) {
    this.resize(256, 256).quality(60).write("lenna-small.jpg");
});
```

There's probably not an awful lot of gain in that.

The library already supports chaining or callbacks. If promises were added across the board, I think we'd have to drop chaining (is that right?). I don't think that would be desirable.

A little known fact too is that in some circumstances the constructor is actually synchronous e.g. if creating a new image manually or if you are cloning an existing image.

I'm open to any practical suggestions though.

**Comment by aeosynth** [comment]
for me, the gain comes when mapping paths:

```js
const promises = paths.map(path => new Jimp(path))
Promise.all(promises).then(jimps => ...)
```

although, this turns out to be impractical, since the bitmap is stored in memory

i'm currently using [sharp](https://github.com/lovell/sharp), and it has a nice [api](http://sharp.dimens.io/en/stable/api/):

```js
const lenna = sharp('lenna.png')
  .resize(256, 256)
  .quality(60)
  .toFile('lenna-small.jpg')

lenna.then(()=> console.log('done'))
```

**Comment by oliver-moran** [comment]
Agree.

My ideal API was something like this:

```js
var lenna = new Jimp("lenna.png").resize(256, 256).quality(60).write("lenna-small.jpg");
```

That doesn't seem possible because the some parts of the constructor are asynchronous. Nevertheless, I agree we should aim for something like that or like Sharp's.

This is probably a v0.3.0 release change. Let's think about what we could do to improve the constructor and see what we can do over the coming months.

**Comment by dbkaplun** [comment]
+1 promises

**Comment by aeosynth** [comment]
with chainable constructors, your example would be

```js
var lenna = new Jimp('lenna.png')
lenna.getImage((err, image) => ...)
```

making the constructor chainable is separate from supporting promises

**Comment by iamstarkov** [comment]
its quite easy to use Bluebird’s [`Promise.promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html) to use Promises with any lib you want. just for me this issue can be safely closed

**Comment by lukesneeringer** [comment]
> With a promise would it look like:
> 
> ```javascript
var lenna = new Jimp("lenna.png").then(function (err, image) {
    this.resize(256, 256).quality(60).write("lenna-small.jpg");
});
```

Actually, the syntax would be:

```javascript
new Jimp('lenna.png').then(function(image) { ... }).catch(function(err) { ... });
```

The gains of using promises are:

1. If you're using a library like bluebird, you can omit the `.catch(err)` boilerplate, because it will yell at you if an uncaught issue runs. That means a ton less of this in your code:

```javascript
if (err) {
   // ...do something boring
}
```

It also means a lot easier debugging when you _don't do that at all_, which is incredibly common.

2. Promises can be combined with things like `Promise.all`. So, instead of doing this:

```javascript
funcRequiringCallback(function(err, data) {
  nextFuncRequiringCallback(function(err, data2) {
    yetAnotherFuncRequiringCallback(function(err, data3) {
      ...
    });
  });
};
```

You can do the much cleaner:

```javascript
Promise.all([promise, promise2, promise3]).then(function(data) {
  ...
});
```

**Comment by lukesneeringer** [comment]
I'm also confused by the huge amount of example code that looks like

```javascript
var image = new Jimp('lenna.png', function(err, image) {
  ...
});
```

Either image is saved as the variable result or used in the callback. It should not be both.
From experimenting, I've determined it's the latter. You should get rid of `var image =` in your documentation.

**Comment by iamstarkov** [comment]
you described good part of promises but still you will got them for free with bluebird promisify

**Comment by iamstarkov** [comment]
point about confusin var part is valid though

**Comment by lukesneeringer** [comment]
> you described good part of promises but still you will got them for free with bluebird promisify

That's what I am doing in my code. It doesn't make the philosophical request less valid.

**Comment by oliver-moran** [comment]
OK. Promises will be in the next major release.

**Comment by dbkaplun** [comment]
Nice one @oliver-moran!

**Comment by oliver-moran** [comment]
OK. Promises are in. Everything all works the same except you can now do:

```js
Jimp.read("lenna.png").then(function (lenna) {
    lenna.resize(512, 512)           // resize
         .quality(60)                // set JPEG quality
         .greyscale()                // set greyscale
         .write("lena-small-bw.jpg") // save again
}).catch(function (err) {
    console.error(err);
});
```

This is available on the main but not published to NPM yet. If you could download it and see what you think, I'd appreciate that. All comments welcome.

**Comment by oliver-moran** [comment]
I've released this now because of https://github.com/oliver-moran/jimp/issues/58.
