### ISSUE TITLE
Multiple Line Breaks & Detecting Rollover

### ISSUE THREAD

**Issue by FireController1847** [oliver-moran/jimp#370]
When creating a Jimp and adding text, I want to add multiple lines like so:
```js
async function modifyImage() {
  const img = await global.jimp.read("red_black_bg.png");
  const font = await global.jimp.loadFont("font.fnt");
  img.print(font, 10, 380, 'I Know What You Did Last Summer', 1920); // text 1
  img.print(font, 10, 500, 'Shawn Mendes & Camila Cabello', 1920); // text 2
  img.getBuffer(global.jimp.MIME_PNG, function(err, buffer) {
    if (err) throw new Error(error);
    else m.channel.send({files: [buffer]});
  });
}
```
The issue is, when text 1 wraps, it overlaps with text 2. Is it possible to detect this at all? I've tried inserting line-breaks into the first text but that doesn't seem to work.

Here's an example:
```js
async function modifyImage() {
  const img = await global.jimp.read("red_black_bg.png");
  const font = await global.jimp.loadFont("font.fnt");
  img.print(font, 10, 380, 'I Know What You Did Last Summer ABCDEFGHIJKLMNOP', 1920); // text 1
  img.print(font, 10, 500, 'Shawn Mendes & Camila Cabello', 1920); // text 2
  img.getBuffer(global.jimp.MIME_PNG, function(err, buffer) {
    if (err) throw new Error(error);
    else m.channel.send({files: [buffer]});
  });
}
```
In the example above, the "ABCDEFGHIJKLMNOP" overlaps the text 2 as seen in the result:
![](https://cdn.discordapp.com/attachments/318926432099106817/385668136197685258/file.jpg)

I've pulled this off using Node.js `v9.2.0` using npm `5.5.1`. I don't know any other languages so.. that's all I can give you.

**Comment by atwoodjer** [comment]
It seems Jimp is very common with people using Discord.js.

**Comment by FireController1847** [comment]
That makes sense, but would it be possible to have something that, say, detected how long the text would be (in pixels), and then rollover if a word/letter goes past the specified size?

**Comment by atwoodjer** [comment]
IT does do that, hence the rollover in the first place. You're defining the position of the second text with an X value, and if it decided arbitrarily to put something NOT where you said to put it, it's unreliable.

**Comment by atwoodjer** [comment]
(close this please)

**Comment by hipstersmoothie** [comment]
@FireController1847 can you provide an example of putting all the text in one line and it going off the screen? Line wrapping seems to be working in your above example.

**Comment by hipstersmoothie** [comment]
Closing:

* You are expicitely telling jimp where to put this. #506 asks for a way to know how many lines a block of text will be
* text wrapping is working. if @FireController1847 can provide an example please file a new issue

**Comment by FireController1847** [comment]
apologies for not responding, honestly it's been so long I forgot about the issue and I'm not even attempting this anymore lol

**Comment by johnxy84** [comment]
I have an issue with the text wrapping not still working with latest jimp version. I have an open issue here,
https://github.com/oliver-moran/jimp/issues/710 but no feedback on it yet
