### ISSUE TITLE
GIF not working ?

### ISSUE THREAD

**Issue by turshija** [oliver-moran/jimp#372]
Hello,
I'm trying this library with GIF images, but I'm receiving this error:
`Unsupported MIME type: image/gif`

From readme I don't see anything related to GIFs, but after inspecting code and this PR - https://github.com/oliver-moran/jimp/pull/247
I see that library should have basic support for gifs.

Am I doing something wrong ?
Thanks

**Comment by jtlapp** [comment]
Jimp doesn't support GIFs, but [`gifwrap`](https://github.com/jtlapp/gifwrap) does and allows you to leverage Jimp for image manipulation.
