### ISSUE TITLE
Load Custom Font Error

### ISSUE THREAD

**Issue by fatihturgut** [oliver-moran/jimp#375]
Hi Everyone!

When i try to load custom font (font.fnt), it gives me an error like "no such file or directory, ... font.png". Even if it is not a .png file, error says it is an .png file.

Could anyone help me to overcome this problem please?

**CODE**
```
Jimp.loadFont('font.fnt').then(function (font) {
    baseImage.print(font, 10, 10, "Hello World!");
    baseImage.write("output.png");
});
```

**ERROR**
(node:6476) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\Users\USERNAME\Desktop\jimp-ex\font.png'
(node:6476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Pistou2** [comment]
+1, I have the exact same problem

**Comment by kadiks** [comment]
It's coming from your .fnt generator, not the library.

Where did you generate your .fnt?
You should have received a .png with it.

If you open your .fnt file with your text editor, you'll notice there is a reference to the `font.png` file that contains all the glyphs.

**Comment by Gaboik** [comment]
Documenting this in the hope of helping someone in the future.

If you're using [BMFont generator from angelcode](http://www.angelcode.com/products/bmfont/), go into the 'Export options' menu via _Options_ -> _Export Options_ or by pretting `T`.

Then:
 - Set the font description to XML
 - Set the textures to PNG

And all should be good!

**Comment by Adron55** [comment]
**Future Jimp users .** 
Don't use BMFont generator cuz that i converted my ttf and otf fonts with it and result was not good . Font converted but with black background frame . 

**İnstead of BMFont generator use [Hiero converter ](https://libgdx.badlogicgames.com/tools.html) it is much better .**
- U can change color of font 
- U can change size of font 
- and etc. what i haven't used yet

**Comment by jrcmadushanka** [comment]
> **Future Jimp users .** Don't use BMFont generator cuz that i converted my ttf and otf fonts with it and result was not good . Font converted but with black background frame .
> 
> **İnstead of BMFont generator use [Hiero converter ](https://libgdx.badlogicgames.com/tools.html) it is much better .**
> 
> * U can change color of font
> * U can change size of font
> * and etc. what i haven't used yet

The new working link to Hiero converter

https://github.com/libgdx/libgdx/wiki/Hiero

**Comment by JaverHumberto** [comment]
Hi, on jimp docs i saw that loadFont function can read a URL, so my question is, what about PNG file? shoul I pass two URLs? one for FNT file, and other for PNG file. Thanks.
