### ISSUE TITLE
quality of image bad when resize

### ISSUE THREAD

**Issue by 2pay** [oliver-moran/jimp#377]
I have code for resize with multer upload:

     productThumb(files) {
        let promises = [];
        let thumbs = [];
        _.forEach(files, (file) => {
            let promise = new Promise((resolve, reject) => {
                var jimpThumb = pathUpload + file.filename;

                new Jimp(jimpThumb, (err, jimpImage) => {
                    if (err) {
                        reject(err);
                        return;
                    }

                    var productImgSize = settings.productImgSize;
                    productImgSize.forEach(function(thumbSize) {
                        var sizeThumb = thumbSize.width + "x" + thumbSize.height;
                        var nameThumb = thumbSize.size + "-" + common.transString(common.removeExtension(file.filename)) + "-" + Date.now() + "-" + sizeThumb + "." + common.getExtension(file.filename);
                        var pathThumb = pathUpload + nameThumb;

                        jimpImage
                            .resize(thumbSize.width, thumbSize.height, Jimp.RESIZE_BEZIER)
                            .quality(thumbSize.quality) //thumbSize.quality
                            .write(pathThumb);
                        thumbs.push(nameThumb);

                    });

                    fs.unlink(jimpThumb);
                    resolve(thumbs);

                });

            });
            promises.push(promise);
        });
        return Promise.all(promises);
    }

When resize:

Before:
![before resize image](https://i.imgur.com/9zIi152.jpg)

After:
![after resize image](https://i.imgur.com/DxkW3Hn.jpg)

thankyou any help.

UPDATE:

I try remove `productImgSize.forEach(function(thumbSize) {` and `jimpImage.resize(500, 500, Jimp.RESIZE_BEZIER)`  set quality `.quality(100) ` then return good quality image.

Why? `resize` place in `forEach` return bad quality images

UPDATE: i change order array `productImgSize`:

500 -> 350 -> 66 return good quality and 66 -> 350 -> 500 return bad quality.

Good quality:

    productImgSize: [{
            size: 'large',
            width: 500,
            height: 500,
            quality: 100
        },
        {
            size: 'medium',
            width: 350,
            height: 350,
            quality: 100
        },
        {
            size: 'small',
            width: 66,
            height: 66,
            quality: 100
        }
    ]

Bad quality:

    productImgSize: [{
            size: 'small',
            width: 66,
            height: 66,
            quality: 100
        },
        {
            size: 'medium',
            width: 350,
            height: 350,
            quality: 100
        },
        {
            size: 'large',
            width: 500,
            height: 500,
            quality: 100
        }
    ]

**Comment by coyotte508** [comment]
Because you don't resize a copy, you resize the image itself.

If you resize it to a small size, save it, and then resize it to a bigger size, it won't be the original image you resized but the smaller one (containing a lot less data). So the blur is normal.

**Comment by Miguel-Lara** [comment]
> Because you don't resize a copy, you resize the image itself.
> 
> If you resize it to a small size, save it, and then resize it to a bigger size, it won't be the original image you resized but the smaller one (containing a lot less data). So the blur is normal.

I faced the same problem, I solved it resizing first to the big size, then to the mid size, and finally to the smal (thumbnail).

**Comment by slenderfigure** [comment]
> > Because you don't resize a copy, you resize the image itself.
> > If you resize it to a small size, save it, and then resize it to a bigger size, it won't be the original image you resized but the smaller one (containing a lot less data). So the blur is normal.
> 
> I faced the same problem, I solved it resizing first to the big size, then to the mid size, and finally to the smal (thumbnail).

Yep. That's the best approach

**Comment by andychicken** [comment]
> Because you don't resize a copy, you resize the image itself.
> 
> If you resize it to a small size, save it, and then resize it to a bigger size, it won't be the original image you resized but the smaller one (containing a lot less data). So the blur is normal.

thank a lot
