### ISSUE TITLE
Is a command line interface out of scope for this project?

### ISSUE THREAD

**Issue by Maximilianos** [oliver-moran/jimp#38]
I really want to be able to do something like this:
```
npm i jimp -g
```
and then
```
jimp resize --crop image.jpg 420x130 600x240 1024x600
```

Is this something other people want?

**Comment by oliver-moran** [comment]
Definitely not out of scope! My original use case was a build script. A CLI sounds like a great idea.

**Comment by Maximilianos** [comment]
Awesome, will try and get it started this week.

**Comment by oliver-moran** [comment]
Cool. Let me know when you have the smallest publishable piece done. I'll push that and we can start building from there.

**Comment by Maximilianos** [comment]
Ok

**Comment by riyadhalnur** [comment]
:+1: to a CLI version. @Maximilianos would be more than happy to help out if you want

**Comment by oliver-moran** [comment]
I've pulled the CLI into the main branch but will leave it undocumented while underdevelopment.

What say we develop it like that and when we're happy with the API we can begin developing documenting it as "beta"?

**Comment by Maximilianos** [comment]
Sure. will try to work on it a bit more this week, I want to add properly handling resizing/rotating/etc.. a whole dir of images. currently it only handles commands on single images

**Comment by iamstarkov** [comment]
Sindre Sorhus started separate module itself from its cli tool, basically because not all module consumers need cli.

**Comment by iamstarkov** [comment]
I also think its a good idea

**Comment by Maximilianos** [comment]
That makes sense, I also think it is a good idea to separate them

**Comment by oliver-moran** [comment]
So do you think a new project is the way to go? That would make sense IMHO too.

**Comment by Maximilianos** [comment]
Yeah, adding `-cli` is the typical thing done. So a new project `jimp-cli` v. 0.1.0 would probably be the way to go.

**Comment by oliver-moran** [comment]
OK. Do you want me to make a new project here (as a central location) and give you read/write access? Or do you want to start a new project elsewhere?

**Comment by oliver-moran** [comment]
I'll pull the CLI stuff into a separate project over the weekend.

**Comment by oliver-moran** [comment]
Split into a separate project here: https://github.com/oliver-moran/jimp-cli

NPM project is here: https://www.npmjs.com/package/jimp-cli

I've added @Maximilianos as a collaborator here. I presume it's possible to do the same on NPM.

**Comment by iamstarkov** [comment]
@oliver-moran on the right side under the secttion "Collaborators" will "+" icon. Use it
![screen shot 2015-11-09 at 01 17 21](https://cloud.githubusercontent.com/assets/559321/11023668/cd7489b0-867f-11e5-9b87-28a6829779f1.png)
