### ISSUE TITLE
Is it possible to make collage ?

### ISSUE THREAD

**Issue by easikoglu** [oliver-moran/jimp#381]
What I want to do is creating a collage image from 72 different images. Is it possible and what about the memory usage?

**Comment by coyotte508** [comment]
It's possible. Create an image the size you want:

```js
var image = new Jimp(256, 256, function (err, image) {
    // this image is 256 x 256, every pixel is set to 0x00000000
});
```

Then use `.blit` or `.composite` to paste other images. You can limit memory usage by pasting images one at a time and deleting the references to them after pasting.

**Comment by edi9999** [comment]
Thanks for the contribution @coyotte508 !

**Comment by easikoglu** [comment]
actually my question is lack of some information, sorry about that, what exactly i want to do is read images from http ( aws s3)  then paste them to one big background image according to their orders.  

Thank you for your support i will try to paste one by one.

**Comment by edi9999** [comment]
Please open another issue for this question, one issue per topic makes it easier for other users to search for things !
