### ISSUE TITLE
Could not find MIME for Buffer <....> (HTTP: 403) in Jimp.read

### ISSUE THREAD

**Issue by denghauser** [oliver-moran/jimp#389]
Hi All,

I just found an issue where the read command tells the MIMI type can't be read.
The link where this happens is the following
https://www.grillsportverein.de/forum/attachments/dscf3928-jpg.519985/

What could this be? The trailing / or ...

Thanks

**Comment by edi9999** [comment]
Did you pass the URL as the data ? 

Jimp won't read the URLs for you, you have to pass it a Buffer (already loaded data)

**Comment by dreki** [comment]
I've been using Jimp for months and months and I always pass it a URL and it reads it just fine.

I've also run into this issue. It happens with GIFs (non-animated) like this: https://static1.squarespace.com/static/57ed984e9de4bbb0f817ec59/t/5b6741388a922d428420c474/1533493573475/basic180815.gif

**Comment by hipstersmoothie** [comment]
@dreki this seems to be a problem with omggif. It seems like it only reads 89a gifs (whatever that is). That gif you provided is a type that doesn't seems to be supported. 

Maybe file an issue here? 

https://github.com/deanm/omggif
