### ISSUE TITLE
extract metadata without reading entire file

### ISSUE THREAD

**Issue by aeosynth** [oliver-moran/jimp#39]
this would involve asking the decoder libraries for this api, or using standalone libraries, such as [exif-parser](https://github.com/bwindels/exif-parser)

**Comment by oliver-moran** [comment]
I'm not sure if this is out of scope. As you say, exif-parser already exists. I'll leave the thread open and see if others +1 the idea though.

**Comment by iamstarkov** [comment]
-1 we already have `exif-parser` so maybe a better idea to create `exif-parser-chunk` or smth and not add this feature to this project. what do you think?

**Comment by oliver-moran** [comment]
I'm going to close this for the reasons @iamstarkov said. If it is really desired people can still +1 it.

**Comment by MikeKovarik** [comment]
Hello, I'm the author of the library [exifr](https://github.com/MikeKovarik/exifr). I initially wrote it with this exact idea - there's no need to read the whole image to get its exif metadata.

With that, exifr is able to parse hundreds of photos in the browser without crashing it.

I already suggested I'd be happy to work with you and do a PR in https://github.com/oliver-moran/jimp/issues/493, but that issue tries to decrease bundle size whereas using the chunked reading feature of exifr would require loading more code and more kb.

<img src="https://raw.githubusercontent.com/MikeKovarik/exifr/master/logo/readme-gif.gif" width="240">
