### ISSUE TITLE
Custom font imports are broken

### ISSUE THREAD

**Issue by dkimot** [oliver-moran/jimp#397]
I am unable to load any font except for the Jimp.FONT_NAME constants.

Whenever I try to import a font, after fixing any errors with the .fnt file, such as no kernings, I get the error:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid file signature`

I wanted to figure out if my fonts were the root of the problem so I copied the Jimp default fonts out of the `node_modules/jimp/fonts/open-sans-8-black` directory to test a jimp font and I got the exact same error.

Then I started tracing the error. It is coming from pngjs which is trying to parse the png file(s) found in the fnt xml files `pages` attribute. PNGjs is what is reading the file signature incorrectly. I solved that problem after verifying the file signature is correct I then got an error related to the IHDR (PNG header). After a few hours of debugging and testing and reading 3 or 4 different packages I'm stuck.

**Comment by Viral-Inc** [comment]
+1, or I just don't understand .fnt

**Comment by dkimot** [comment]
And they work again. I honestly don't know what happened. I do have to constantly add a kernings key to the .fnt file, but only on some fonts.
