### ISSUE TITLE
How do I center the text applied to an image?

### ISSUE THREAD

**Issue by tutyamxx** [oliver-moran/jimp#398]
I have tried this var

` GetXCoord = image.bitmap.width;`

`image.print(font, Math.floor(GetXCoord / 2)`

Indeed it does print on the middle of the image, but I want to format the text to be something like this. 

[---------------TEXT HERE---------------]

but currently outputs

[-------------------TEXT HERE-----------]

which literally is annoying.

**Comment by TylerBeutel** [comment]
Can you find the width of the font? If so, you could subtracting it from what you've found to offset it and center it properly:
`x position = floor ( (half the image width) - (half the font width) )`

**Comment by hipstersmoothie** [comment]
look at #449 closing in favor of
