### ISSUE TITLE
Jimp callback doesn't finish in AWS lambda

### ISSUE THREAD

**Issue by SomeNerdNamedSteve** [oliver-moran/jimp#400]
I have been trying to get Jimp to run in a lambda function.  When I try to push it to a lambda function, I don't get the Jimp image.  I get `<Jimp pending... >`.  My guess is the callback never finished.  Why does a callback finish im a local machine for this library and not AWS lambda?

**Comment by edi9999** [comment]
How long do you let your lambda functions run ? Lambda functions are usually limited to 500ms, and Jimp might take longer than that.

**Comment by steffkelsey** [comment]
Why use this in AWS Lambda? Would be easier to either use ImageMagick or OpenCV, depending on what image processing you need to do. There's quite a bit more support for those libs and they are much much more mature.

**Comment by dcworldwide** [comment]
My motivation is because there are no native reps. That makes lambda deployments easier.

**Comment by hipstersmoothie** [comment]
@SomeNerdNamedSteve Any updates?

**Comment by hipstersmoothie** [comment]
Closed due to inactivity.
