### ISSUE TITLE
jimp.read() hangs on await/async

### ISSUE THREAD

**Issue by asweers** [oliver-moran/jimp#404]
The following code block appears to hang for me.
```
await jimp.read(req.file.buffer, () => {});
```

**Comment by czycha** [comment]
Jimp in its current, published state has a weird mixture of Promises and callbacks. In your example, you are using both. `await` is to be used with Promises, but you also use the callback capability for the function. Specifically, your callback is a no-op which doesn't `resolve` or `reject` so when paired with `await`, it never finishes.

The easiest fix is to remove the callback like this:

```js
(async function() {
  await jimp.read(req.file.buffer);
  // Do something after reading
})();
```

It should be noted that the current HEAD version of Jimp does not use callbacks for the `read` function so this confusion will eventually not be a factor.

**Comment by ahmadawais** [comment]
Also remember there are two ways to write the files:

https://github.com/oliver-moran/jimp/tree/master/packages/jimp#writing-to-files
