### ISSUE TITLE
How to make auto-adjustments (brightness and contrast) for image

### ISSUE THREAD

**Issue by marinoaldi** [oliver-moran/jimp#405]
I would like to know, how to make image correction (auto adjustments of brightness / contrast) for image.
I don't know if the library  have any feature similar to OpenCV see example: http://answers.opencv.org/question/75510/how-to-make-auto-adjustmentsbrightness-and-contrast-for-image-android-opencv-image-correction/

Brightness and contrast is linear operator with parameter alpha and beta. The question here is how to calculate alpha and beta automatically ?

Thanks in advance

**Comment by steffkelsey** [comment]
If you use the `normalize()` command, it will get you most of the way there. It is a basic contrast-stretch. You might not need to get heavy like those openCV commands.

**Comment by hipstersmoothie** [comment]
@marcolino is @steffkelsey's answer sufficient?
