### ISSUE TITLE
Reading a non-image buffer prints weird error into console but returns a resolved promise

### ISSUE THREAD

**Issue by raine** [oliver-moran/jimp#408]
```
> require('jimp').read(new Buffer('foo')).then((x) => console.log('image', x))
mime must be a string
Promise { <pending> }
> image undefined
```

It should not print anything as a side effect. Instead the error should contained in the promise.

**Comment by turakvlad** [comment]
Have the same issue with `0.2.28`. Take a look at this - https://github.com/oliver-moran/jimp/issues/262.
