### ISSUE TITLE
Jimp with http-proxy-middleware

### ISSUE THREAD

**Issue by mfaheemakhtar** [oliver-moran/jimp#418]
Hi, 

Is it possible to use Jimp with http-proxy-middleware to process image?

This is what I'm looking for:

Browser (Image -> POST) ---> Proxy (Process image - Jimp) ---> Server (processed image) ----> save on disk.

Any help will be appreciated.

**Comment by hipstersmoothie** [comment]
@mfaheemakhtar I would say it is. But I have no experience with that technology. If you have a specific example where the code does not work feel free to open an issue. 

And if you publish a module with jimp In it add it to the reader!
