### ISSUE TITLE
[v0.2.28] package.json from github differs from the npmjs one

### ISSUE THREAD

**Issue by svewag** [oliver-moran/jimp#421]
I noticed that the [package.json](https://github.com/oliver-moran/jimp/blob/master/package.json) differs from the one on [npmjs](https://registry.npmjs.org/jimp/-/jimp-0.2.28.tgz).

For example the dependency 'request' is not in the github repo but in the npmjs code

Can you fix this?

**Comment by czycha** [comment]
The repo is currently several commits ahead of the 0.2.28 release (about 77 at the time of writing this). There were some issues with the 0.2.28 release related to browser compatibility and I think the idea is to get those sorted out before releasing the next version. Progress has unfortunately been stalled at that process so the next version won't be out for a while.

If you need the repo to be at 0.2.28, checkout the appropriate tag: `git checkout tags/0.2.28 -b 0.2.28` (creates a new branch called 0.2.28 and reverts to that tag).

**Comment by svewag** [comment]
Ok, thanks!
