### ISSUE TITLE
Output image to grayscale array.

### ISSUE THREAD

**Issue by cashlionjp** [oliver-moran/jimp#426]
A common need for Nueral Networks is to have an image flattened into an array after it has been grayscaled.

Is this an option already or worthy of being a feature?

**Comment by HanKruiger** [comment]
I was also looking for this feature, but for a different purpose. (I want to load a matrix with numeric values from an image, and use those to set terrain types of cells in a video game.)

Did you find an alternative solution?

**Comment by HanKruiger** [comment]
What I ended up using for now:
```js
const flattendGrayscaleArray = (await Jimp.read('image.png'))
    .bitmap.data.filter((_, i) => i % 4 == 0)
```
This concatenates every fourth pixel's R-value in a `Uint8Array`.
