### ISSUE TITLE
Jimp.loadFont() Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by mnoleto** [oliver-moran/jimp#431]
When I try to load a font from a `.fnt` file generate by [Littera](http://kvazars.com/littera/) I get the error:
```
{ Error: ENOENT: no such file or directory, open 'https://s3-us-west-2.amazonaws.com/botecofc/fonts/black64/font.fnt'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'https://s3-us-west-2.amazonaws.com/botecofc/fonts/black64/font.fnt' }
Error: ENOENT: no such file or directory, open 'https://s3-us-west-2.amazonaws.com/botecofc/fonts/black64/font.fnt'
```

I tried to load from a S3 bucket with public permission and also from a local folder using the following:
`Jimp.loadFont('https://s3-us-west-2.amazonaws.com/botecofc/fonts/black64/font.fnt');`

When I use the default font `Jimp.FONT_SANS_64_WHITE` everything works. I don't know if the problem is on the converted file or on the library. Is there a way to test the converted `fnt` and see if it's right?

**Comment by devdemi** [comment]
I solved my problem I put to directory only fnt file. When I generate BMFont you should get fnt and png file. I put png to directory with fnt file and now it works well. Please look at source code https://github.com/oliver-moran/jimp/blob/master/index.js#L2578

**Comment by hipstersmoothie** [comment]
`loadFont` does not currently load fonts from a url. This enhancement is tracked in #448. closing
