### ISSUE TITLE
Jimp read bmp to base64 results in wrong colours

### ISSUE THREAD

**Issue by Smiley01987** [oliver-moran/jimp#432]
Hi,

When reading a BMP file using the .read method and then converting the image to a base64 string using the getBase64 method the image is not the same as the original image anymore. The weird thing is that it does not happen to all BMP's i'm converting, only a few.

Original BMP: 
![screen shot 2018-04-18 at 13 38 55](https://user-images.githubusercontent.com/14977493/38954080-05f908c0-4351-11e8-9785-e91786fa7a7a.png)

Converted BMP:
![screen shot 2018-04-18 at 21 38 06](https://user-images.githubusercontent.com/14977493/38954098-11fb4854-4351-11e8-8751-d6742e3f43a0.png)

Code:
```
const image = await Jimp.read("path/to/image.bmp");
image.getBase64(Jimp.MIME_BMP, (err, data) => { // Assigning data to image element });
```

Version: browser v0.2.27

Thanks in advance,
Smaïl

**Comment by hipstersmoothie** [comment]
@Smiley01987 Can you try again with latest master?
