### ISSUE TITLE
huge packfile

### ISSUE THREAD

**Issue by DanielRuf** [oliver-moran/jimp#433]
The repo is around ~430 MB in size and mainly consists of one large packfile in .git.

**Comment by hipstersmoothie** [comment]
It seems like the built versions of the code have been committed to the repo. I think we should remove then and only generate them for publishes.

**Comment by DanielRuf** [comment]
But keep in mind that changing past commits is not ideal as then all forks are out of sync due to new commit hashes (in most cases).

**Comment by hipstersmoothie** [comment]
I wouldnt change past commits. Unless that's what git rm does. Plan is to `git rm` them and add them to the gitignore. Is that ok?

**Comment by hipstersmoothie** [comment]
Would you mind submitting a PR for that?

**Comment by DanielRuf** [comment]
I can try to invest some time next week.

**Comment by hipstersmoothie** [comment]
Yeah i just tried to do it real quick and it was for sure harder than I though! In your PR it would be awesome if you could include steps other contributors should take once the cleansing is done in the main fork.

**Comment by hipstersmoothie** [comment]
@DanielRuf any progress on this?

**Comment by DanielRuf** [comment]
Not yet, other things have and had a higher priority.
