### ISSUE TITLE
Font Rotate

### ISSUE THREAD

**Issue by ETLegacyy** [oliver-moran/jimp#439]
Is there a way i can rotate a font?

**Comment by glyphCezilleSantillan** [comment]
I would like this option too. For now, I create a blank image, print my text, and then rotate that image before compositing it onto my main image. It isn't perfect; the placeholder might be too small, for instance; you have to check the output or manage the string length.

**Comment by hipstersmoothie** [comment]
@ETLegacyy @glyphCezilleSantillan #388 seems to have a working way to rotate the font. similar to what @glyphCezilleSantillan describes.

@glyphCezilleSantillan "It isn't perfect; the placeholder might be too small, for instance; you have to check the output or manage the string length." - this is true regardless of rotation. if your string goes off the page it's on you to manage a correct maxWidth

There is still some issues with the rotation of text, detailed in #388. I don't know how possible it will be to correct this though.
