### ISSUE TITLE
compile with WebpackEncore

### ISSUE THREAD

**Issue by etshy** [oliver-moran/jimp#440]
Hi.
I work with webpackEncore and when I want to require jimp with `var Jimp = require("jimp");` I got the following error
```
his dependency was not found:

* fs in ./node_modules/jimp/index.js, ./node_modules/mime/mime.js and 1 other

To install it, you can run: npm install --save fs
```

I installed `fs` with `npm install --save fs` but still have the error.

I don't really understand how to include jimp in my browser JS?
I have to set the path manually in my require, like `var Jimp = require("../../node_modules/jimp/browser/lib/jimp.min");` ?

**Comment by ganeshgummani** [comment]
Hi etshy, 
I have the similar issue, can you please tell me how did you resolve this?

**Comment by etshy** [comment]
I didnt't find any way to make it work so I stopped trying to use it for now.
I didn't take a look at this since I closes the issue.

Sorry I couldn't help.

**Comment by ganeshgummani** [comment]
Thanks for the response!
I was able to get rid of this error by using older version (0.2.28, 2 year old) as I'm using React15 (2 year old) it worked for me.
