### ISSUE TITLE
Possible to use Jimp with mock-fs?

### ISSUE THREAD

**Issue by edsilv** [oliver-moran/jimp#441]
I'm using mock-fs to test my project and if I try to include a serialised image byte array as a fixture:

https://github.com/edsilv/biiif/blob/thumbs/test/top.js#L159

`Jimp.read` throws this error:

```
Error: ENOENT, no such file or directory '\\?\c:\Users\edsilv\github\edsilv\biiif\generate-thumbs-manifest\_canvas-without-thumb\file.jpg'
Utils.js:140
unable to generate thumbnail for: c:\generate-thumbs-manifest\_canvas-without-thumb
```

Other yml fixtures are being read by js-yaml's `safeLoad`. Is Jimp able to work with a mocked filesystem?

**Comment by hipstersmoothie** [comment]
will close within the month if no example code is given @edsilv

**Comment by edsilv** [comment]
Hi, sorry for the delay. Here's an example project:

https://github.com/edsilv/jimp-mock-fs-error-demo

Annoyingly I can't install Jimp to test this locally right now because of https://status.npmjs.org/incidents/v22ffls5cd6h - but it _should_ be what you need.

**Comment by hipstersmoothie** [comment]
I installed jimp v0.4.0 to the provided repo and ran `npm run test`. The test passed with no errors so I think this is fixed.

**Comment by edsilv** [comment]
Hi, just having another look at this.

`/cat/cat.jpg` passes.

`c:\cat\cat.jpg` throws 

> ENOENT, no such file or directory '\\?\c:\Users\edsilv\github\edsilv\jimp-mock-fs-error-demo\catcat.jpg'

"catcat.jpg" - It was to do with using windows backslashes in file paths. Once I normalised these to using forward slashes it started working :-)
