### ISSUE TITLE
new Jimp as promise

### ISSUE THREAD

**Issue by Favna** [oliver-moran/jimp#445]
I see quite a bit of chatter about promises across various issues on the repo but no where do I see a mention about making the `new Jimp()` work with promises so I'm creating an issue addressing that. Currently the only way to create a new Jimp image appears to be as follows, adopted from the docs:

```js
new Jimp(256, 256, function (err, image) {
  if(!err) {
    // this image is 256 x 256, every pixel is set to 0x00000000
    return console.log(image);
  }
  return console.error(err);
});
```

but with promises this could be enhanced to:

```js
new Jimp(256, 256).then((img) => {
  // this image is 256 x 256, every pixel is set to 0x00000000
  return console.log(image);
}).catch((err) => {
  return console.error(err);
});
```

This currently throws the error message `"(intermediate value).then is not a function"`.
***

Also an example when using async/await

```js
asyc run () {
  try {
    var image = await new Jimp(256, 256);
    return console.log(image);
  } catch (err) {
    return console.error(err);
  }
}
```

**Comment by Nilegfx** [comment]
@Favna this workaround works for for me.

```js
import { default as Promise } from 'bluebird';

const createImage = ( ...args ) => new Promise( ( res, rej ) => {
  try {
    new Jimp( ...args, ( error, image ) => {
      if ( error ) rej( error );
      res( Promise.promisifyAll( image ) );
    } );
  } catch ( error ) {
    console.log( error );
  }
} );
```

**Comment by Nilegfx** [comment]
@Favna this workaround works for for me.

```js
import { default as Promise } from 'bluebird';

const createImage = ( ...args ) => new Promise( ( res, rej ) => {
  try {
    new Jimp( ...args, ( error, image ) => {
      if ( error ) rej( error );
      res( Promise.promisifyAll( image ) );
    } );
  } catch ( error ) {
    rej( error );
  }
} );
```

**Comment by Favna** [comment]
The workaround I personally applied is instead of creating a blank new Jimp I now use Jimp.read, reading a fully transparant image. It's essentially the same effect but it's not as nice as just using new Jimp (although nicer than your version i'd say)

**Comment by brunolm** [comment]
Maybe `jimp.new` or `jimp.create` would be better, more compatible with TypeScript.

Also, `new Jimp` doesn't seem to be working for me, I get the global object in the callback (I'm running with `ts-node`)

**Comment by brunolm** [comment]
I got it working by doing

```
const Jimp = jimp as any;
const foo = new Jimp(w, h);
```
