### ISSUE TITLE
How to align text to center?

### ISSUE THREAD

**Issue by v7s** [oliver-moran/jimp#449]
I have a 500px by 167px image and I want to add 2 lines of text but those need to be centered, how can I do it? I'm using node.js and the jimp package, the last line will always be changing length as in a different username!

```
Jimp.read("./imgs/background.png").then(function (image) {
        image.resize(500, Jimp.AUTO)
        .quality(100);
        image.write("./imgs/background-test.png");

      Jimp.loadFont(Jimp.FONT_SANS_32_WHITE).then(function (font) {

        //What do I do here? image.print(font, x, y, "Welcome Username", 7)

        image.getBuffer(Jimp.MIME_PNG, (err, buffer) => {
          image.write("./imgs/background-test.png");
        })
      });

      }).catch(function (err) {
        console.error(err);
      });
```

**Comment by Cherry** [comment]
I've been poking at this today and it appears that this functionality was added in https://github.com/oliver-moran/jimp/pull/285 but never really documented. It also appears as if the changes haven't landed in npm yet.

If you install from the git master, `git://github.com/oliver-moran/jimp` and then use the following code, it appears to work as expected:

```javascript
image.print(font, x, y, {
	text: "Hello world!",
	alignmentX: jimp.HORIZONTAL_ALIGN_CENTER
}, maxWidth);
```

**Comment by hipstersmoothie** [comment]
@Cherry wanna take a stab at documenting this? thanks!

**Comment by Cherry** [comment]
@Acituanbus Try including the `maxWidth` and `maxHeight` options. Logically, it makes sense that these are required to center anything.

Here's a snippet of what we're using in production and it's working without issue:
```js
image.print(font, pos.x, pos.y, {
	text: "Example test",
	alignmentX: jimp.HORIZONTAL_ALIGN_CENTER,
	alignmentY: jimp.VERTICAL_ALIGN_CENTER
}, pos.maxX, pos.maxY);
```

**Comment by Ashishisdonorlon** [comment]
mmm this sud work fine 
image.print(font, image.bitmap.width/2, image.bitmap.height/2, 'Your text');

**Comment by Ashishisdonorlon** [comment]
`Hey`

**Comment by SimonRijn** [comment]
> ```js
> alignmentY: jimp.VERTICAL_ALIGN_CENTER
> ```

It looks logical, but I can't get it done. My text is still not in the middle after your adjustment ...

**Comment by Cherry** [comment]
> > ```js
> 
> > alignmentY: jimp.VERTICAL_ALIGN_CENTER
> 
> > ```
> 
> @Cherry 
> 
> It looks logical, but I can't get it done. My text is still not in the middle after your adjustment ...

Can you share a full code sample to replicate the issue? We’re still using this pretty successfully.
