### ISSUE TITLE
Keep perspective when re-sizing

### ISSUE THREAD

**Issue by brutyke** [oliver-moran/jimp#45]
Very first time using GitHub, so apologies if this suggestion is in the wrong place.
Is there, can there be, an option to keep perspective when re-sizing ?
e.g. instead of :  this.resize(512, 512)
this.resize(512, auto) - resize width, keep height perspective
this.resize(auto, 512) - resize height, keep width perspective

Thanks

**Comment by oliver-moran** [comment]
Sounds great.  The next release will allow `this.resize(512, Jimp.AUTO)`. Thanks for the suggestion.

**Comment by brutyke** [comment]
Great! Looking forward to it.

**Comment by oliver-moran** [comment]
Published now. Thanks again.
