### ISSUE TITLE
How to process image without reading file

### ISSUE THREAD

**Issue by Ovilia** [oliver-moran/jimp#451]
Say that I have an image 
```
var img = new Image();
...
```

How can I use jimp to process it?

**Comment by DContra** [comment]
Are you trying to create a new image? If so that's clearly laid out in the docs

**Comment by PorterK** [comment]
`new Image()` is a frontend function. It is not an image, it is a functional representation of `<img />`. You would still need to add a src attribute to the image.

From the MDN Web Docs:

```
The Image() constructor creates a new HTMLImageElement instance.

It is functionally equivalent to document.createElement('img').
```

You _can_ however read a buffer using Jimp according to the docs/README.

**Comment by hipstersmoothie** [comment]
Thanks for helping out @PorterK! Closing. Just use jimp to transform a buffer, output it to base64, and load it into `img.src`.
