### ISSUE TITLE
Error: Node's Buffer() not available

### ISSUE THREAD

**Issue by robertgon97** [oliver-moran/jimp#453]
![captura de pantalla 2018-06-12 a la s 2 44 27 p m](https://user-images.githubusercontent.com/22420571/41310325-2c1be468-6e4f-11e8-9afb-84d2b491e0c8.png)

**Comment by Cherry** [comment]
Revert to version 0.2.27. The browser version was broken in 0.2.28.

**Comment by konsumer** [comment]
related to #280

**Comment by hipstersmoothie** [comment]
It looks like the current version of master solves this issue. look for my comment for example code. closing in favor of #280
