### ISSUE TITLE
How to catch error 404

### ISSUE THREAD

**Issue by Antecer** [oliver-moran/jimp#454]
if i use Jimp.read("error url"), it will print error in console
 `Could not find MIME for Buffer <http://*/233> (HTTP: 404)`
i want catch it, then i can do another thing with it!

**Comment by francois06** [comment]
bump

**Comment by lukepighetti** [comment]
Hey guys, I cannot catch SOI or 403 or 404 error with Jimp. I've tried putting .read() and .writeAsync() in async try/catch, and I've tried .catch(). I'm at a loss. This thing just keeps crashing when the image isn't valid during web scraping and I can usually pad these problems with try/catch blocks.
