### ISSUE TITLE
Current NPM repo does not have Jimp.loadFont and Jimp.prototype.print in jimp.d.ts

### ISSUE THREAD

**Issue by thib92** [oliver-moran/jimp#455]
The current repository in NPM seems to miss the `print` method, as well as the `static loadFont` method, even though it is the same version as the GitHub repo, and checking the file on this repo, it does have those to typings. Maybe the NPM repo isn't updated properly ?
Using the master branch of the GitHub repo as a dependency in my package.json file does the trick.
I used version `^0.2.28` in my dependencies.

**Comment by Antecer** [comment]
Yes, i get the error info : 
`UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined`

**Comment by hipstersmoothie** [comment]
closing in favor of #484
