### ISSUE TITLE
Angular Cannot find name 'Buffer'

### ISSUE THREAD

**Issue by JonathanBouligny** [oliver-moran/jimp#459]
Hi, Jimp cant seem to find the node types. I read around the issues and found that there were issues with buffer in version .28. I downgraded to .27 and this didn't help. I was wondering if this was still an issue or if I incorrectly imported the files.

    ERROR in node_modules/jimp/jimp.d.ts(18,24): error TS2304: Cannot find name 'Buffer'.

I think this may be an error with the .d.ts file because I'm not using buffer in the code.

I have imported the type for Jimp into my dev dependencies (npm i --save-dev @types/node), but the new version of Jimp says it doesnt need these types it has its own. I have also put "types":["node"] into my tsconfig.json file.

Code
```
    import { Component, OnInit } from '@angular/core';
    import * as jimp from 'jimp';
    
    @Component({
      selector: 'app-jimp-test',
      templateUrl: './jimp-test.component.html',
      styleUrls: ['./jimp-test.component.css']
    })
    export class JimpTestComponent implements OnInit {
    
      constructor() { }
    
      ngOnInit() {
        this.testJimp();
      }
    
      testJimp() {
        jimp.read('assets/testInput.jpg').then( (img) => {
          img.clone().blur(1).write('assets/testOutput.jpg');
        });
      }
    
    }
```

Dependencies

```
    {
      "name": "my-playground",
      "version": "0.0.0",
      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
      },
      "private": true,
      "dependencies": {
        "@angular/animations": "^6.0.3",
        "@angular/common": "^6.0.3",
        "@angular/compiler": "^6.0.3",
        "@angular/core": "^6.0.3",
        "@angular/forms": "^6.0.3",
        "@angular/http": "^6.0.3",
        "@angular/platform-browser": "^6.0.3",
        "@angular/platform-browser-dynamic": "^6.0.3",
        "@angular/router": "^6.0.3",
        "core-js": "^2.5.4",
        "jimp": "^0.2.28",
        "rxjs": "^6.0.0",
        "zone.js": "^0.8.26"
      },
      "devDependencies": {
        "@angular-devkit/build-angular": "~0.6.8",
        "@angular/cli": "~6.0.8",
        "@angular/compiler-cli": "^6.0.3",
        "@angular/language-service": "^6.0.3",
        "@types/jasmine": "~2.8.6",
        "@types/jasminewd2": "~2.0.3",
        "@types/jimp": "^0.2.28",
        "@types/node": "^8.9.5",
        "codelyzer": "~4.2.1",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~1.7.1",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.0",
        "karma-jasmine": "~1.1.1",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.3.0",
        "ts-node": "~5.0.1",
        "tslint": "~5.9.1",
        "typescript": "~2.7.2"
      }
    }
```

Angular Versions

```
    @angular-devkit/architect         0.6.8
    @angular-devkit/build-angular     0.6.8
    @angular-devkit/build-optimizer   0.6.8
    @angular-devkit/core              0.6.8
    @angular-devkit/schematics        0.6.8
    @angular/cli                      6.0.8
    @ngtools/webpack                  6.0.8
    @schematics/angular               0.6.8
    @schematics/update                0.6.8
    rxjs                              6.2.1
    typescript                        2.7.2
    webpack                           4.8.3
```

Jimp Version

`    0.2.28`

_Thanks_

Sorry for the edits..more information

**Comment by david476** [comment]
I think I was having this problem a couple of days ago but I'm not sure what ended up fixing it. Right now I'm using [this NPM package](https://www.npmjs.com/package/arraybuffer-to-buffer) to be able to read a file into JIMP with a [`FileReader`](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) but its worth trying to read from something that is explicitly a URL (e.g. `http://`) first.

**Comment by david476** [comment]
Whoops, I think #453 did the trick actually.

**Comment by JonathanBouligny** [comment]
I reverted and still got nothing :/

**Comment by david476** [comment]
If you can share your environment I'd be happy to try poking around in it but otherwise I don't know, sorry.

**Comment by JonathanBouligny** [comment]
I actually got it to#453! I needed to put types : [node] in my tsconfig.app.json file not my tsconfig.json file. A little confusing. Now when I run import * j from 'jimp' i get the error cannot find definition file but I downloaded the @types/jimp file.

How do I share my environment just zip up all my files?

**Comment by david476** [comment]
Sorry, I think this is beyond me, I'm pretty new to Typescript. For my project I've just switched to using the [version](https://unpkg.com/jimp@0.2.27/browser/lib/jimp.min.js) actually built for web, it generally seems to work better (less other buffer type related issues for me) and might be easier to get working for you.

**Comment by hipstersmoothie** [comment]
@JonathanBouligny did you get this working?

**Comment by hipstersmoothie** [comment]
Solution posted here https://stackoverflow.com/questions/51256473/angular-cannot-find-name-buffer

```sh
yarn add -D  @types/node       
```

```json
{
  "types": [
    "node"
  ]
}
```

**Comment by Jobin-S** [comment]
> I actually got it to #453! I needed to put types : [node] in my tsconfig.app.json file not my tsconfig.json file. A little confusing. Now when I run import * j from 'jimp' i get the error cannot find definition file but I downloaded the @types/jimp file.
> 
> It says `Cannot find type definition file for 'jimp' `I put `"types" : ["node","jimp"] `in my tsconfig.app.json file Theres no typescript file in the @types/jimp folder does this mean I cant use Jimp for angular or should i put in the new typescript file from the updated version?
> 
> How do I share my environment just zip up all my files?

Thanks this works
