### ISSUE TITLE
Comparison with other tools

### ISSUE THREAD

**Issue by mathpere** [oliver-moran/jimp#46]
Hello,

Could you provide some comparison / benchmarks with other tools like GraphicsMagick?

Best regards,

Mathieu

**Comment by brutyke** [comment]
Sorry,
I’m new to all this and haven’t used any other tools.
I’m looking for something to auto-resize photos uploaded via website by (logged in) visitors, otherwise I’ll end up with 50MB photos ! And, I have to use something compatible with Classic ASP on a Windows server ;-((
 
Regards
Dave

**Comment by oliver-moran** [comment]
@mathpere, a related question is here:

https://github.com/oliver-moran/jimp/issues/35

Performance isn't the primary goal of the library. Rather portability is. The goal of the project is to develop a production image library with no native dependencies.

ImageMagick, etc. require native applications to do the actual image processing. Jimp has no native dependencies. That means Jimp is easier installed and wholly portable. ImageMagick or another native-dependant library will be more performant but at a cost of ease of installation and portability.

Whether you go for Jimp or a native-dependent library will depend on your requirements.

Sharp added Jimp to their benchmark tests last week. They have yet to publish the results but from initial testing it looks like Jimp is comparable to lwip (native-based) library:

https://github.com/lovell/sharp/issues/275#issuecomment-143526723

If that's the case then the fastest native-dependant library is 14 times faster and ImageMigick is about 4-6 times faster than Jimp:

http://sharp.dimens.io/en/stable/performance/

**Comment by mathpere** [comment]
Yes, I did understand the philosophy of Jimp. I'd like to know at what price is portability.

Thanks for pointing me these links.

**Comment by lovell** [comment]
Hello, the performance results for a `JPEG decode > bilinear resize > JPEG encode` round-trip have now been updated to include `jimp` - see http://sharp.dimens.io/en/latest/performance/#results

In summary, the JavaScript `jimp` demonstrates performance comparable with the C++ [CImg](https://github.com/dtschump/CImg) (via the `lwip` wrapper).

**Comment by oliver-moran** [comment]
@lovell thanks so much. Those are really interesting results.

**Comment by grantcarthew** [comment]
Hi @lovell , These performance links should be on your README. Everyone who investigates this library are going to want to know the cost of choosing Jimp over other native options.

**Comment by lovell** [comment]
@grantcarthew If "your README" refers to sharp then did you see the "benchmark tests" link in https://github.com/lovell/sharp/blob/master/README.md#documentation ?

**Comment by grantcarthew** [comment]
This one mate: https://github.com/oliver-moran/jimp/blob/master/README.md
At least a link to the sharp documentation.
I had to search and find this closed issue to get performance details.

**Comment by lovell** [comment]
@grantcarthew I don't maintain jimp. Perhaps you could submit a PR to jimp with the change you suggest?
