### ISSUE TITLE
Hue, Saturation, Lightness

### ISSUE THREAD

**Issue by rustamli** [oliver-moran/jimp#47]
Is there a way to change Hue, Saturation, Lightness with jimp?

**Comment by oliver-moran** [comment]
No specific methods at present - but it's an obvious gap.

You can roll your own using the `image.scan` method. If you do please send on your code and I'll add it. Or if you know of an open source (preferably MIT licensed) package that has these methods, or just link to the algorithms, then I can add them here.

**Comment by rustamli** [comment]
Thanks for your reply @oliver-moran 

Having `image.scan` all we need to manipulate *H*, *S* and *L* are `rgbToHsl` and `hslToRgb` functions.

Then increasing hue by 50 would look somewhat like this: 

```javascript
var red = this.bitmap.data[idx];
var green = this.bitmap.data[idx+1];
var blue = this.bitmap.data[idx+2];

var out = utils._rgbToHsl(red, green, blue);
out.h += 50;

var cvrBack = utils._hslToRgb(out.h, out.s, out.l);

this.bitmap.data[idx] = cvrBack.r;
this.bitmap.data[idx+1] = cvrBack.g;
this.bitmap.data[idx+2] = cvrBack.b;
```

I have implemented `rgbToHsl` and `hslToRgb` functions and was able to achieve this: 

**BEFORE:** https://dl.dropboxusercontent.com/u/6434207/other/jimp/lx-cozy--large.png
**AFTER:** https://dl.dropboxusercontent.com/u/6434207/other/jimp/lx-cozy--large--512.png

I need to test my code more before sharing, I will make a pull request as soon as I put it all together. 

P. S. great library btw!

**Comment by oliver-moran** [comment]
Thanks! If you write it, I'll pull it in.

**Comment by rustamli** [comment]
See https://github.com/oliver-moran/jimp/pull/50
