### ISSUE TITLE
New Minor Release

### ISSUE THREAD

**Issue by oliver-moran** [oliver-moran/jimp#484]
@hipstersmoothie, thanks for all this. If you walk me through what's changed in this release and I'll put it live on NPM.

Since this is a change to ES version, I think we should jump major version number. So this would be 0.3.0. What do you think?

**Comment by hipstersmoothie** [comment]
Changes in 0.2.29:

* Lots of docs updates
* TIFF support
* Lots of tiny bug fixes
* Browser version was fixed somewhere in the past year. This PR #482  makes the following work in browser again. 

```js
const Jimp = require('jimp')
```

**Comment by hipstersmoothie** [comment]
the babel configuration targets ie8. so it should be quite compatible with many browsers.

**Comment by hipstersmoothie** [comment]
I'd also like to get promise based returns into this release. I'm gonna do a backwards compatible implementation real quick.

**Comment by hipstersmoothie** [comment]
Promises implemented in #486

**Comment by oliver-moran** [comment]
Looks brilliant, Andrew. Thank you.

I've hit a speed bump on my side making the release to NPM. But I've teed up for a new release and will make it ASAP.

About future releases: release early and release often (I know, I know, we haven't released for over a year!). If you're in the mood for making additions, I'm happy to facilitate.

**Comment by hipstersmoothie** [comment]
If we set up circleCI and https://github.com/ericclemmons/github-semantic-version we can make a release on every merge to master. Then we will never have to worry about communicating over an ocean to get a release going 😉 

All you have to do is label the PR with patch, minor, or major and a github/npm release is made on commits to master! If you are uncomfortable giving me the npm token to set up on circleCI, you can do it and I will never have to see the key.

#486 is ready to be merged if you wanna. I can help you set up circle too if you need me to.

**Comment by hipstersmoothie** [comment]
@oliver-moran all merges have happened! (btw 0.X.0 is a minor release)

**Comment by oliver-moran** [comment]
@hipstersmoothie Thank you enormously for all of this work. I've put 0.3.0 live. (Yes, I'm counting 0.X.0 releases as major releases because I'm not going to bump past an actual version 0.)

Sorry for the delay in doing this but I had difficulty accessing NPM. Now that that's fixed, let me know whenever you want to do a release and I'll review the code for malware and push it up.

Apologies for wanting to review. But the package is used by a lot of people/companies and I don't want to put anyone at risk through recklessness on my part.

My eventual intention is to hand this project over to a community. That has been stop-start for 18 months now. The approach I've been taking is to grant commit access to anyone, but for now hold back on opening up NPM rights. If a community starts to develop – or someone starts to show genuine and positive ownership over the project – then I'll happily hand over release tokens, etc.

You look like you're doing some stellar stuff – that's a great inroad into the project being moved out of my hands. Thank you!

**Comment by hipstersmoothie** [comment]
Thank you for letting me do it! I'm excited to see where the future of jimp goes. Once web assembly is more accepted (years) we'll really be cooking 😉 

Looking into bugs and fixing error handling is my next task. 

Really excited that we got a release out 🎉 🎉

**Comment by hipstersmoothie** [comment]
@oliver-moran it seems like you did not publish master. I just tried to install 0.3.0 and it has none of the work from the past 2 weeks. was this intentional? It seems like you might not have pulled master in a while

Commands needed to release:
```
npm run build
# then run your usual release commands
```

`npm run build` will build the browser, es5 and esm versions of jimp.

**Comment by hipstersmoothie** [comment]
Okay now it's good!
