### ISSUE TITLE
rotation seems not to resize correctly

### ISSUE THREAD

**Issue by speediro** [oliver-moran/jimp#49]
When rotating an image where the width is considerably larger than the height over an arbitrary number of degrees, JIMP returns a largely empty rotated image where the new height and width are switched and the image looks correctly rotated. I already tried just switching h and w in the advancedRotate function, but then rotate seems to crop first after this do the rotate so you end up with a cropped result anyway.

```javascript
var Jimp = require("jimp");

// open a file called "hb.png"
var hb = new Jimp("message.png", function (err) {
    if (err) throw err;
    
    this.clone().rotate(13).write("./output/msg-rotate-13.png")
});
```

![message](https://cloud.githubusercontent.com/assets/14186431/10445468/71380968-7173-11e5-8d32-3fb0bc75d60c.png)

![msg-rotate-13](https://cloud.githubusercontent.com/assets/14186431/10445487/c53ebcaa-7173-11e5-8a0b-8be5cdfa89a0.png)

**Comment by oliver-moran** [comment]
@speediro - I'm not sure if I understand you correctly but does this answer your question:

When we were developing the rotate function there were two approaches:

1. We could rotate and resize the image accordingly
2. We could rotate the image but not resize it

The first approach is non-destructive: all of your original image is still visible but the dimensions of the image will stretch to accommodate the rotation.

The second approach is destructive: the width and height of the image will not have change but after rotation some of your image will outside of the image bounds.

The default behavior is 1. The way to call behavior 2 is to pass `false` as a second argument to the rotate method:

```js
image.rotate( 13 ); // rotate by 13 degrees and resize accordingly
image.rotate( 13, false ); // rotate by 13 degrees don't resize
```

Does that answer your issue?

**Comment by speediro** [comment]
@oliver-moran - not really.
The examples I posted show the result I get when doing the first.
As you can see, it does not really keep everything of the image. It created a very high image yet rotates over the correct angle.
Can you try my code with the first image I posted?
You should get the second image...

**Comment by oliver-moran** [comment]
OK. Sounds like a bug so.

I'll be able to test it (and probably fix it) tonight.

**Comment by oliver-moran** [comment]
Fixed. Will do a release tonight with this fix. Thanks for spotting it.

**Comment by oliver-moran** [comment]
This is published on NPM. Thanks for spotting it.

**Comment by speediro** [comment]
@oliver-moran, nice, looks like it behaves correctly now.And thanks for JIMP and the quick resolution.

**Comment by speediro** [comment]
@oliver-moran , might have found another issue with rotation...
Can you check the following test? Is it possible that there are remnants of the first blitting op?

```javascript
var lenna = new Jimp("lenna.png", function (err) {
    if (err) throw err;
    this.crop(0,200,512,200).write("./output/lenna-cropped.png").rotate(33).write("./output/lenna-rotate-33.png")
});
```

**Comment by oliver-moran** [comment]
Nice! Yes, do a pull request and I'll pull it in.

**Comment by oliver-moran** [comment]
The fix for this has been pulled in. Will appear in the next release. Thanks!
