### ISSUE TITLE
Expose y position in print callback

### ISSUE THREAD

**Issue by Zyberg** [oliver-moran/jimp#506]
I have to print 2 text blocks onto an image and the second one needs to be separated by exactly 100px after the first.

What I am doing right now is simply looping through the text and by using `measureText` function trying to find the number of lines that my text block has, then finding the max y value of each line of the text (which turns out to be 2px higher for every line than `font.common.lineHeight`, so I suppose there's some padding or something? Is it consistent?)
It's all kind of nice logically, BUT the way the text is being drawn on an image in the library itself is exactly by looping through all the text, counting the number of lines etc. So, I am doing practically same loop twice and increase the running time of my function twice :/

Is there a good way around this?

**Comment by hipstersmoothie** [comment]
You could expose this the line counting functionality. IDK of any current way to get what you want. PRs are welcome! All the printing code is found in `src/image-manipulation/text.js`

**Comment by hipstersmoothie** [comment]
Exposing the function would accomplish the same thing though. Calling the measureText function twice...

**Comment by Zyberg** [comment]
@hipstersmoothie this would work without calling the same function twice, so it looks like a great solution.

**Comment by hipstersmoothie** [comment]
Released in [v0.4.0](https://github.com/oliver-moran/jimp/releases/tag/v0.4.0)
