### ISSUE TITLE
Can't install v0.3.1

### ISSUE THREAD

**Issue by seantw** [oliver-moran/jimp#507]
Why need git binary?
the error message is as follows:

npm -g install jimp
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/makr28/jpgjs.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by hipstersmoothie** [comment]
Thats a dep for UTIF.js. How are you installing jimp? I just reinstalled it on my test project with no problems

**Comment by seantw** [comment]
- OS: Window 10 (x64)
- Install via node-v8.11.3-x64.msi
- Run "npm install -g jimp" on Command Prompt

[install-debug.log](https://github.com/oliver-moran/jimp/files/2259222/install-debug.log)

**Comment by hipstersmoothie** [comment]
can you check out this https://github.com/npm/npm/issues/10729? I am on a mac and am having trouble reproducing this. I installed the node version but it still installs fine.

If you could post an issue on https://github.com/photopea/UTIF.js/ too that would be cool. I've been trying to get the guy to switch to something that's on the registry

**Comment by seantw** [comment]
UTIF.js  author said  that he has never used NPM :cry:

**Comment by hipstersmoothie** [comment]
closing in favor of #560
