### ISSUE TITLE
Resize with width or height as Jimp.AUTO throwing error

### ISSUE THREAD

**Issue by shanebo** [oliver-moran/jimp#51]
I'm trying to follow your API docs and use Jimp.AUTO for the width, however, I'm getting this error:

> Error: w and h must be numbers

I've tried the instance of the image.AUTO, tried 'Jimp.AUTO' as a string and Jimp.AUTO and none of them work. Any ideas?

Great package by the way. Thank you.

**Comment by oliver-moran** [comment]
It works like this:

```js
var lenna = new Jimp("lenna.png", function (err, image) {
    this.resize(Jimp.AUTO, 100) // resize 
        .write("lenna-small.png") // save 
});
```

If that doesn't work for you, check your version number. It was added in v0.2.8.

Let me know, that works.

**Comment by shanebo** [comment]
I was on 0.2.5. That was the problem. Thank you.
