### ISSUE TITLE
Wrong font path in NPM package

### ISSUE THREAD

**Issue by tylerlong** [oliver-moran/jimp#516]
``` 
Error: ENOENT: no such file or directory, open '...\node_modules\jimp\dist\fonts\open-sans\open-sans-16-white\open-sans-16-white.fnt'
```

I checked the content of the NPM package, the physical  path is `\node_modules\jimp\fonts\open-sans\open-sans-16-white\open-sans-16-white.fnt`

So either we change the path, or we change where the font is placed physically.

**Comment by hipstersmoothie** [comment]
should go out in next release!

**Comment by hipstersmoothie** [comment]
@oliver-moran
