### ISSUE TITLE
Error with exifRotate function

### ISSUE THREAD

**Issue by gsalvo** [oliver-moran/jimp#519]
Hello:

![image](https://user-images.githubusercontent.com/4744433/43740533-76225554-9999-11e8-8294-957cd131ec03.png)

throws the following error:

Error to get image: TypeError: image.exifRotate is not a function

Thanks!

**Comment by hipstersmoothie** [comment]
exifRotate was mistakenly put in the type file. Use .rotate instead

**Comment by gsalvo** [comment]
Hi.
I have a question. ¿How can i rotate automatically an image based on its EXIF data with .rotate?

Thanks!

**Comment by CepheiA** [comment]
+1

**Comment by hipstersmoothie** [comment]
the image should be exif rotated automatically when loading the image. you don't have to do anything


also @CepheiA please no '+1's use the reactions

**Comment by gsalvo** [comment]
Ok thanks!!
