### ISSUE TITLE
Exporting PNG to BMP makes everything red

### ISSUE THREAD

**Issue by finneganh** [oliver-moran/jimp#521]
I'm trying to load a PNG, tweak it, and export it to a BMP.

When I do so, everything ends up very red.

My guess is that Jimp is passing an RGBA buffer to js-bmp, which is interpreting it as ABGR, which ends up throwing out the red, swapping blue and green, and using the alpha (0xFF) for all red pixels.

<img width="216" alt="screen shot 2018-08-06 at 5 52 55 pm" src="https://user-images.githubusercontent.com/260837/43742899-935049e4-99a1-11e8-85b1-72cebfc18b9c.png">

**Comment by hipstersmoothie** [comment]
can i get the input png?

**Comment by finneganh** [comment]
![itemframe_background](https://user-images.githubusercontent.com/260837/43746900-e116519c-99b4-11e8-94d3-b630385ad316.png)

Exporting to JPEG seemed fine.

I added the following hack code to my export and it seems to have solved my issues:
```
    .scan(0, 0, 20, 20, function(_x, _y, idx) {
      const red = this.bitmap.data[idx + 0];
      const green = this.bitmap.data[idx + 1];
      const blue = this.bitmap.data[idx + 2];
      const alpha = this.bitmap.data[idx + 3];

      this.bitmap.data[idx + 0] = alpha;
      this.bitmap.data[idx + 1] = blue;
      this.bitmap.data[idx + 2] = green;
      this.bitmap.data[idx + 3] = red;
    })
```

(This is after cropping the image down to 20x20.)

**Comment by hipstersmoothie** [comment]
Cool! I hope i can integrate your code. Still need the original source image. Or make a PR if you can

**Comment by hipstersmoothie** [comment]
unless that little thing is the source

**Comment by finneganh** [comment]
Yeah, that's the source. It's a Minecraft texture I was working with.

Is it also worth checking that BMPs are the right color order on the way in to Jimp?

**Comment by finneganh** [comment]
Yay! Thanks so much!

**Comment by hipstersmoothie** [comment]
thanks for the code 👍

**Comment by spidgorny** [comment]
> ![itemframe_background](https://user-images.githubusercontent.com/260837/43746900-e116519c-99b4-11e8-94d3-b630385ad316.png)
> 
> Exporting to JPEG seemed fine.
> 
> I added the following hack code to my export and it seems to have solved my issues:
> 
> ```
>     .scan(0, 0, 20, 20, function(_x, _y, idx) {
>       const red = this.bitmap.data[idx + 0];
>       const green = this.bitmap.data[idx + 1];
>       const blue = this.bitmap.data[idx + 2];
>       const alpha = this.bitmap.data[idx + 3];
> 
>       this.bitmap.data[idx + 0] = alpha;
>       this.bitmap.data[idx + 1] = blue;
>       this.bitmap.data[idx + 2] = green;
>       this.bitmap.data[idx + 3] = red;
>     })
> ```
> 
> (This is after cropping the image down to 20x20.)

This should be in README.me next to ```getBufferAsync``` documentation. Thank you.
Now I can convert from https://github.com/Automattic/node-canvas#canvastobuffer to PNG.
