### ISSUE TITLE
Could not find MIME for Buffer <File.PNG>

### ISSUE THREAD

**Issue by rorbla** [oliver-moran/jimp#525]
I'm trying to resize a file that i get from an <input  type="file">
`Jimp.read(params.file.name, (err, file) => {
        if (err) throw err;
             file
            .resize(256, 256) // resize
     );`

But i have this error:  Could not find MIME for Buffer <File.PNG>
I've tried using 'blob-to-buffer' library too
`const responseBlob = await fetch(`${params.file.preview}`);
    const blob = await responseBlob.blob();
    let result;
    toBuffer(blob, function (err, buffer) {
        result = buffer;
    })
Jimp.read(result ...
`
but same error

**Comment by rorbla** [comment]
Rubén Ordieres

2018-08-08 19:23 GMT+02:00 Andrew Lisowski <notifications@github.com>:

**Comment by hipstersmoothie** [comment]
@rorbla No image was attached!

**Comment by rorbla** [comment]
<img width="1027" alt="research" src="https://user-images.githubusercontent.com/26737610/43894216-b283ffa4-9bd1-11e8-959e-be4b11063156.PNG">
Uncaught Error: Could not find MIME for Buffer <research.PNG>

![canyon](https://user-images.githubusercontent.com/26737610/43894242-d0ef9930-9bd1-11e8-945f-c90496fe1325.png)
Uncaught Error: Invalid file signature with the 2nd

![09-posterization-opt](https://user-images.githubusercontent.com/26737610/43894372-2039164c-9bd2-11e8-9716-70a29c3202db.jpg)
Uncaught Error: SOI not found

**Comment by hipstersmoothie** [comment]
running this code I cannot reproduce the issues. First I right clicked the images and just saved them.

```
node tests. 
```

test.js:
```js
const jimp = require('jimp');

jimp.read('./exampleImages/canyons.png', (err, file) => { 
  if (err) throw err; 
  file.getBuffer(jimp.AUTO, (err, res) => console.log(res))  
});

jimp.read('./exampleImages/tiger.jpg', (err, file) => { 
  if (err) throw err; 
  file.getBuffer(jimp.AUTO, (err, res) => console.log(res))  
});
```

Both buffers print fine

**Comment by dhavalsojitra8866** [comment]
If i use facebook url then it shows below error.
var url='https://graph.facebook.com/890843584382401/picture?type=large&width=200&height=200'
var url1 = url.replace('?height=90&width=90', '?type=large&width=200&height=200')
jimp.read(url1, function(err, image) {
    console.log("image ------>", image)


image ------> undefined
jimp Error :  { Error: Could not find MIME for Buffer <null>
    at Jimp.parseBitmap (/home/game/teenpatti-dev/node_modules/@jimp/core/dist/utils/image-bitmap.js:108:15)
    at Jimp.parseBitmap (/home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:498:32)
    at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:440:15
    at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/index.js:168:14
    at /home/game/teenpatti-dev/node_modules/@jimp/core/dist/request.js:56:9
    at IncomingMessage.<anonymous> (/home/game/teenpatti-dev/node_modules/phin/lib/phin.compiled.js:1:2162)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11) methodName: 'constructor' }
