### ISSUE TITLE
Fix chaining

### ISSUE THREAD

**Issue by hipstersmoothie** [oliver-moran/jimp#527]
we take an optional callback but return it. this make it impossible to chain off of the this value. I propose changing all of these:

```js
    if (isNodePattern(cb)) {
        return cb.call(this, null, this);
    }
```

To this:

```js
    if (isNodePattern(cb)) {
       cb.call(this, null, this);
    }
```

which will allow the callback to be called but still allow chaining.

@edi9999 What do you think?

**Comment by edi9999** [comment]
Yes, what you propose seems good to me, I don't see a good reason for returning the callback return value.

**Comment by hipstersmoothie** [comment]
Nice I'll get a PR together
