### ISSUE TITLE
Are .rotate() and  .getBase64() method lossless

### ISSUE THREAD

**Issue by jagsarai** [oliver-moran/jimp#528]
I have a question regarding the rotate() and getBase64() methods. Wasn't able to find much information on it. Are manipulated images ( using either of the two methods above) lossless? The original image is .jpeg and the resulting image type is not being changed.

**Comment by hipstersmoothie** [comment]
Jimp will do not 'compression' during transformations. It just takes the bitmap and does the specified transform. The resulting image may be bigger because the JS libraries we use to encode images aren't perfect.
