### ISSUE TITLE
All tests could also be running in the browser

### ISSUE THREAD

**Issue by edi9999** [oliver-moran/jimp#532]
Some of the tests are not runned in browser environment : 

For example : https://github.com/oliver-moran/jimp/blob/master/test/filetypes.test.js#L13

I think it would be possible to have a function that can read from the disk using one of : 

`fs.readFile(path)`

`fetch(path).then(function(response) {return response.text()})` with a static webserver running

What do you think of that @hipstersmoothie ?

I do what I describe in an other open-source library that I maintain : https://github.com/open-xml-templating/docxtemplater/blob/master/es6/tests/utils.js#L386 and it has been working quite well.

**Comment by edi9999** [comment]
Maybe instead of having a condition detecting if the build is in the browser we could even use a webpack-loader to load the pngs using require.

**Comment by hipstersmoothie** [comment]
I think we have something similar `getJimpDir` gets images and fonts served in the browser. The test you cite writes back to the filesystem, something I don't think we can do.

**Comment by hipstersmoothie** [comment]
A combination of 

https://github.com/oliver-moran/jimp/blob/5294ae92c0cb3c6a757b732eb0822200ee71f8a2/src/constants.js#L50

and

https://github.com/oliver-moran/jimp/blob/master/karma.conf.js#L26

serve files to the browser.

**Comment by edi9999** [comment]
Some of the other tests could run in the browser too I think : https://github.com/oliver-moran/jimp/blob/master/test/async.test.js#L44

**Comment by hipstersmoothie** [comment]
Also I don't believe we should be doing any webpacking in jimp. Libraries like jimp should not be webpacked I beleive.

https://twitter.com/HipsterSmoothie/status/1023034485749637120

**Comment by hipstersmoothie** [comment]
I am ES6ing the tests right now. I'll unblock the `getBuffer` and `getAync` in the browser.

**Comment by hipstersmoothie** [comment]
async/await make the tests so much more readable

**Comment by edi9999** [comment]
Ok, good !
