### ISSUE TITLE
Version 0.3.3 should be pushed to NPM registry

### ISSUE THREAD

**Issue by maxdanilov** [oliver-moran/jimp#538]
Here the latest published one is 0.3.2: https://www.npmjs.com/package/jimp

**Comment by hipstersmoothie** [comment]
Should be published within the day. @oliver-moran holds the keys

**Comment by maxdanilov** [comment]
Still not there. @oliver-moran do you have ETA on the package publication?

**Comment by hipstersmoothie** [comment]
It could happen today. It all depends on @oliver-moran getting around to it and the tests passing. Right now they pass so I'm hoping for 12pm-4pm PST. But again I don't hold the keys
