### ISSUE TITLE
Image quality getting bad

### ISSUE THREAD

**Issue by canvas-manik** [oliver-moran/jimp#54]
Hi,

I am new to image optimization. I just want to optimize my images tomake them small in size and dimension, but maintaining quality. I used the following code:

```js
new Jimp("img.jpg", function (err, image) {
        if(!err){
            var origImageDim = {width:this.bitmap.width,height:this.bitmap.height};
            var dimensions = calculateImageDimensions(origImageDim.width,origImageDim.height,600,400);//Get proportionate dimensions
            var imageClone = image.clone();
            image.cover(dimensions.width, dimensions.height).write("destFolder/img.jpg", function(err, image){
                    if(!err){
                        console.log("Image optimised successfully");
                    }
                    else{
                        console.log(err);
                    }
                }
            )
		}
	}
	
	function calculateImageDimensions(width,height,maxWidth,maxHeight){
    // calculate the width and height, constraining the proportions
    if (width > height) {
        if (width > maxWidth) {
            height = Math.round(height *= maxWidth / width);
            width = maxWidth;
        }
    }
    else {
        if (height > maxHeight) {
            width = Math.round(width *= maxHeight / height);
            height = maxHeight;
        }
    }
    return {width:width,height:height};
}
```
The problem i am facing is that the quality of the resultant image is getting bad and the size (KB's) is  getting bigger. Can you please help? Am I doing anything wrong?

![orig-image](https://cloud.githubusercontent.com/assets/11735090/10535342/cb2c2cb8-73ff-11e5-8188-a5d6cb3528a2.jpg)
![resultant-image](https://cloud.githubusercontent.com/assets/11735090/10535343/cb309a6e-73ff-11e5-9add-4d2bb0502018.jpg)

**Comment by oliver-moran** [comment]
Hi, @canvas-manik. A lot of these methods are provided for you:

```js
new Jimp("img.jpg", function (err, image) {
	// resize the image to 400px high, set JPEG quality to 60, and save
	image.resize(Jimp.AUTO, 400).quality(60).write("img-small.jpg");
}
```

Let me know if this works for you.

**Comment by canvas-manik** [comment]
Yeah, I tried that as well. the quality is getting very bad. Even though the size might get okay. Is there some way to retain the same quality reducing the dimensions and KBs. PFA the images with 60%, 80%, 90% quality.

![sujatha-4kqxh0gy-60](https://cloud.githubusercontent.com/assets/11735090/10539520/a6ee0a60-741d-11e5-9866-01ba71e42456.jpg)
![sujatha-4kqxh0gy-80](https://cloud.githubusercontent.com/assets/11735090/10539523/b00b7862-741d-11e5-99f8-676690422ebc.jpg)
![sujatha-4kqxh0gy-90](https://cloud.githubusercontent.com/assets/11735090/10539528/b70a3856-741d-11e5-8f70-9f5aee7c6250.jpg)

**Comment by oliver-moran** [comment]
There's a couple of possible issues.

The first thing is that it's a pretty low quality image to begin with. It looks like its been through the JPEG rinse a few times. For example, look at the artifacts in the original around the saddle, pedal and handlebars.

Secondly, resizing will mess with your pixels. You can't retake the photograph only smaller. The scaling algorithm will do its best but, by definition, if you half the size of the image, you're trying to squeeze four pixels into one. You will lose some detail in doing so. Different techniques do that differently with different outcomes but none can do the impossible.

Lastly, you're saving it again as a JPEG. That's lossy and will further will further reduce the quality:

http://petapixel.com/2010/02/04/saving-jpeg-photos-hundreds-of-times/

Taking all that into account I performed the same operation in Gimp. I compared that to the output of Jimp using PNG, JPEG, and BMP. See the output below.

**Original**

![original](https://cloud.githubusercontent.com/assets/414918/10541190/feaf708e-7406-11e5-826f-6e81fd9694d4.jpg)

**Gimp (JPEG)**

![small-gimp](https://cloud.githubusercontent.com/assets/414918/10541194/09aad398-7407-11e5-9d10-bf1f771cd81e.jpg)

**Jimp (JPEG)**

![small-jimp](https://cloud.githubusercontent.com/assets/414918/10541202/15676192-7407-11e5-8ee3-837d1cb22cb8.jpg)

**Jimp (PNG)**

![small-jimp](https://cloud.githubusercontent.com/assets/414918/10541210/20eae4ee-7407-11e5-88a9-42df6f5fa53b.png)

**Comment by canvas-manik** [comment]
Thanks a lot Oliver for your response. Yes, you are right, while uploading the images from the browser, I am using HTML Canvas object to optimize /EXIF rotate the images before sending them to server. I am not sure what are the best practices for that. Can you share something out of your experiences?
My goal is to upload the images to my site, while doing so, I want:

1. To reduce the size on client when the image is uploaded, to save bandwidth for user
2. Retain quality of the images
3. Reduce the page footprint, for that I want to make the uploaded images to smaller sizes, say a thumbnail (80*80)/card(400*400) and load the smaller sizes of images initially. Load the full size images (1000*700) only when required.

I am using NodeJS on the backend, and angular js on the front-end.

Any help is deeply appreciated.

Regards,
Manik Mittal

**Comment by canvas-manik** [comment]
Thanks a lot Oliver,

After uploading the original images, it looks like it is working fine.

Thanks,
Manik Mittal

**Comment by iamstarkov** [comment]
@canvas-manik can this issue be closed then?

**Comment by canvas-manik** [comment]
Closing this issue, as issue is resolved.

**Comment by canvas-manik** [comment]
Thanks Vladimir,

I have closed the issue.

Regards,
Manik Mittal

**Comment by lovell** [comment]
> "Jimp uses a bi-cubic two-pass scaling algorithm"

@oliver-moran Hello, has `jimp` switched from bilinear to bicubic interpolation recently? I'll be updating `sharp`'s [performance test results](http://sharp.dimens.io/en/stable/performance/) soon and want to ensure I'm correctly categorising it.

**Comment by oliver-moran** [comment]
@lovell - No, it hasn't changed. It was the only one I could find!

I had it in my head ([since Day 1](http://stackoverflow.com/questions/25816236/pure-javascript-image-manipulation)) that it was bi-cubic but I may be wrong. The original project I pulled it from has been taken down and it's beyond my knowledge to tell the difference by looking at the code.

If you can tell, here's the resizer: https://github.com/oliver-moran/jimp/blob/master/resize.js

**Comment by lovell** [comment]
@oliver-moran Thanks for the quick reply. https://github.com/taisel/JS-Image-Resizer looks like the (resuscitated) project you're referring to. If so, @taisel should be able to answer the bilinear vs bicubic question.

**Comment by taisel** [comment]
There's two modes of scaling if you refer to the demo presented at http://taisel.github.io/JS-Image-Resizer/

One is bilinear, another is neither, but results in preserving the image crispness (it looks like nearest neighbor integer upscale+bilinear for a comparable end result). Downscaling is *always* the custom algorithm, since the algorithm is equivalent to multiple passes of bilinear limited to 2x downscaling in each pass, so it doesn't miss a source input pixel. That's emphasized in the demo with one of the images shown (context2d uses bilinear usually). If you downscaled with context2d (presuming bilinear) multiple times in a ratio of no more than 2x to get the same final image size, you'd get the same result as the custom algorithm.

I hope I explained the peculiarities here.

**Comment by taisel** [comment]
If you all want bicubic as an upscaling algorithm, or want to propose another downscaling mode of operation, feel free to chime in. That resizing project is ancient and in need of update.

**Comment by taisel** [comment]
Looking at JIMP's code, bilinear is being used instead of the custom algorithm for upscaling.

**Comment by lovell** [comment]
Thanks for the detailed information @taisel!
