### ISSUE TITLE
getBufferAsync() returns Promise<Jimp> and not Promise<Buffer>

### ISSUE THREAD

**Issue by AtaS** [oliver-moran/jimp#540]
These below are from `jimp.d.ts` file. By using `getBuffer()` method we can obtain the `buffer` object in the callback.

```js
getBuffer(mime: string, cb: (err: Error, buffer: Buffer) => any): this;
getBufferAsync(mime: string): Promise<Jimp>;
```

How can we do the same with `await getBufferAsync()` as it returns a type of `Promise<Jimp>` rather than a type of `Promise<Buffer>`?

**Comment by hipstersmoothie** [comment]
fixed in master https://github.com/oliver-moran/jimp/blob/master/jimp.d.ts#L252

**Comment by AtaS** [comment]
Great, thanks!
