### ISSUE TITLE
0.3.3 : Cannot find module 'core-js/modules/es6.array.is-array'

### ISSUE THREAD

**Issue by lonix1** [oliver-moran/jimp#543]
jimp 0.3.3
ubuntu 18

`package.json`:
````json
{
  "name": "foo",
  "version": "0.0.1",
  "devDependencies": {
    "jimp": "0.3.3"
  }
}
````

`app.js`:
````node
"use strict";
const jimp = require("jimp");
````

run it:
`node app.js`

result is an error with:
`Error: Cannot find module 'core-js/modules/es6.array.is-array'`

**Comment by termax** [comment]
same here

**Comment by lonix1** [comment]
@hipstersmoothie I should have mentioned I'm on LTS of everything, so
ubuntu 18.04
`npm -v` = 3.5.2
`node -v` = 8.10.0
Maybe you're on bleeding edge?

**Comment by hipstersmoothie** [comment]
Did my above fix help until a release can get out?

**Comment by lonix1** [comment]
@hipstersmoothie I don't use yarn, so don't know if that works, sorry. But I downgraded to 0.3.2 which works for me.

**Comment by hipstersmoothie** [comment]
Can you verify the babel polyfill? you can instead just

```
npm i @babel/polyfill
```

npm i and yarn add are the same thing

**Comment by lonix1** [comment]
@hipstersmoothie I tried that and it works. Might be useful for those using those tools, thanks.

I'll wait for the next version though.

**Comment by hipstersmoothie** [comment]
I'm gonna keep this open til a release happens

**Comment by RumbleFrog** [comment]
Thought my node installation was broken, was going insane. Thanks for the quick release.

**Comment by hipstersmoothie** [comment]
I'm trying to get it release ASAP. But I don't have the key yet. In the meantime please install @babel/polyfill and jimp should work as expected

**Comment by oliver-moran** [comment]
I've published the release but the problem seems to be still there in 0.3.4.

![screen shot 2018-08-11 at 21 39 11](https://user-images.githubusercontent.com/414918/43995900-d27d2710-9daf-11e8-8f3e-971d579008bd.png)

This is from my smoke test as follows:

```js
var Jimp = require("jimp");
 
// open a file called "lenna.png"
Jimp.read("lenna.png", function (err, lenna) {
    if (err) throw err;
    lenna.resize(256, 256)            // resize
         .quality(60)                 // set JPEG quality
         .greyscale()                 // set greyscale
         .write("lena-small-bw.jpg"); // save
});
```

**Comment by oliver-moran** [comment]
I've published the release but the problem seems to be still there in 0.3.4.

![screen shot 2018-08-11 at 21 39 11](https://user-images.githubusercontent.com/414918/43995971-38890014-9db1-11e8-9057-bea2edf7fa43.png)

This is from my smoke test as follows:

```js
var Jimp = require("jimp");
 
// open a file called "lenna.png"
Jimp.read("lenna.png", function (err, lenna) {
    if (err) throw err;
    lenna.resize(256, 256)            // resize
         .quality(60)                 // set JPEG quality
         .greyscale()                 // set greyscale
         .write("lena-small-bw.jpg"); // save
});
```

**Comment by hipstersmoothie** [comment]
It got added as a dev dep so it wasn't installed 😢

**Comment by johnnykramer** [comment]
still `Error: Cannot find module 'core-js/modules/es6.array.is-array'`...

**Comment by hipstersmoothie** [comment]
I just pushed a commit that should resolve the issue. https://github.com/oliver-moran/jimp/commit/97ed2a524ea4263af2581dd20578f166d714fd34 @oliver-moran

**Comment by johnnykramer** [comment]
@hipstersmoothie sorry but still `Error: Cannot find module 'core-js/modules/es6.array.is-array'`

**Comment by johnnykramer** [comment]
@hipstersmoothie unfortunately, last commit didn't...

**Comment by hipstersmoothie** [comment]
My branch here seems to work. I ran

```
yarn add hipstersmoothie/jimp#test
```

and running the above code yields no errors.

**Comment by johnnykramer** [comment]
```
npm uninstall --save jimp
npm install --save hipstersmoothie/jimp#test
```
And still `Error: Cannot find module 'core-js/modules/es6.array.is-array'`

**Comment by hipstersmoothie** [comment]
did you `rm -rf node_modules/`

**Comment by hipstersmoothie** [comment]
@johnnykramer what version of node are you using?

**Comment by johnnykramer** [comment]
@hipstersmoothie 
```
> node -v
> v8.11.3
```
yes, i've done `rm -rf node_modules/`

**Comment by oliver-moran** [comment]
I've published 0.3.5. Smoke test works again from my end.

I'm also using v8.11.3.

**Comment by hipstersmoothie** [comment]
I just tested with v8.11.3 also and it seems to work

**Comment by hipstersmoothie** [comment]
@johnnykramer can you test with v0.3.5 ?

**Comment by johnnykramer** [comment]
@oliver-moran @hipstersmoothie 
node v10.8.0 also `Error: Cannot find module 'core-js/modules/es6.array.is-array'`

**Comment by hipstersmoothie** [comment]
I can no longer reproduce the issue on any version of node. Could you throw a sample project together. 

this is my setup right now:

```json
{
  "name": "jimp-testing-project",
  "version": "1.0.0",
  "main": "src/index.js",
  "dependencies": {
    "jimp": "^0.3.5"
  }
}
```

```js
var Jimp = require("jimp");
 
// open a file called "lenna.png"
Jimp.read("./exampleImages/lenna.png", function (err, lenna) {
    if (err) throw err;
    lenna.resize(256, 256)            // resize
         .quality(60)                 // set JPEG quality
         .greyscale()                 // set greyscale
         .write("lena-small-bw.jpg"); // save
});
```

```sh
```

**Comment by hipstersmoothie** [comment]
maybe its a lock file problem? try deleting any of those if you have them

**Comment by johnnykramer** [comment]
@hipstersmoothie yes, `@babel/polyfill` present in the jimp's dependencies

**Comment by hipstersmoothie** [comment]
<img width="893" alt="screen shot 2018-08-11 at 3 28 51 pm" src="https://user-images.githubusercontent.com/1192452/43996604-58518762-9d7b-11e8-9549-4bd12161d1ea.png">

**Comment by hipstersmoothie** [comment]
can i see the full stack trace?

**Comment by hipstersmoothie** [comment]
core-js is in node modules too?

**Comment by johnnykramer** [comment]
```
> test-app@1.0.0 start /home/ec2-user/environment/test-app
> node index.js

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es6.array.is-array'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ec2-user/environment/test-app/node_modules/jimp/dist/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-app@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2018-08-11T22_41_35_169Z-debug.log
```
`core-js` also installed.
@hipstersmoothie

**Comment by hipstersmoothie** [comment]
Okay I'm a little baffled. I can't reproduce this at all. Is this within a AWS instance?

**Comment by hipstersmoothie** [comment]
The dependancies are installed so I don't know why it can't resolve them...

**Comment by hipstersmoothie** [comment]
does it work if you add `@babel/polyfill` or `core-js` directly?

**Comment by hipstersmoothie** [comment]
How about what npm version are you using?

**Comment by hipstersmoothie** [comment]
If you are on npm@2 it could be a problem https://github.com/babel/babel-preset-env/issues/162

**Comment by johnnykramer** [comment]
it is cloud9 on the aws ec2 instance.
npm v6.2.0

**Comment by johnnykramer** [comment]
And i've installed `@babel/polyfill` and `core-js` manually — still not working! :(

**Comment by hipstersmoothie** [comment]
I have no experience with aws. You have any ideas? I'll search around for similar issues

**Comment by hipstersmoothie** [comment]
you definitely have `core-js/modules/es6.array.is-array` installed and babel is for sure trying to include it. maybe you could globally install it on the instance? (I'm just taking guesses at this point)

**Comment by hipstersmoothie** [comment]
Awesome!

**Comment by hipstersmoothie** [comment]
now to figure out why core-js 3 was being installed

**Comment by hipstersmoothie** [comment]
I'm looking at the lock file and see no reference to core-js v3

**Comment by hipstersmoothie** [comment]
So on a clean install it defaults to core-js@3-ish?

**Comment by hipstersmoothie** [comment]
These are my only entries for core-js in my yarn.lock

```
"@babel/polyfill@^7.0.0-rc.1":
  version "7.0.0-rc.1"
  resolved "https://registry.yarnpkg.com/@babel/polyfill/-/polyfill-7.0.0-rc.1.tgz#c78e17e64c42cd6a2f5d8edf0f20e18213c0d74d"
  dependencies:
    core-js "^2.5.7"
    regenerator-runtime "^0.11.1"
```

and in the package-lock.json

```
    "@babel/polyfill": {
      "version": "7.0.0-rc.1",
      "resolved": "https://registry.npmjs.org/@babel/polyfill/-/polyfill-7.0.0-rc.1.tgz",
      "integrity": "sha512-x6s1nu32T0Ayzh/d0SXB4UPIZNcK7Oc01tmZQEhBVwFeOF+ynUlyS4b+zKX1kfbjD7o4qF6PXvDXLRX6i28hsA==",
      "requires": {
        "core-js": "2.5.7",
        "regenerator-runtime": "0.11.1"
      }
    },
```

what does your lock file look like?

**Comment by lonix1** [comment]
@hipstersmoothie Thanks for fixing this.

Off topic, what terminal are you using [in that image](https://github.com/oliver-moran/jimp/issues/543#issuecomment-412305512)?

**Comment by hipstersmoothie** [comment]
@lonix1 Integrated vscode terminal, oh-my-zsh, with my custom theme https://github.com/hipstersmoothie/PowerlevelHipstersmoothie

**Comment by hipstersmoothie** [comment]
🤘 Weed leafs and flames 🤘

**Comment by salmanwaheed** [comment]
@johnnykramer `npm i -s core-js@2.5.7` works for me :)

Thanks man
