### ISSUE TITLE
Can't load open-sans-32-white.fnt 

### ISSUE THREAD

**Issue by chancein007** [oliver-moran/jimp#548]
After installing the jimp by the below command:
npm install jimp --save
and I tried to run the below source code 
----------------------------------------------------------------
var Jimp = require('jimp');
Jimp.read('test.png', (err, image) => {
    if (err) throw err;
    Jimp.loadFont(Jimp.FONT_SANS_32_WHITE).then(function(font) {
        image.print(font, 10, 10, 'Hello World!')
        .fade(0.5)
        .write('modified.jpg');
    });
});
----------------------------------------------------------------
It throws the below exception:

(node:6760) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'C:\nodejs\node_modules\jimp\dist\fonts\open-sans\open-sans-32-white\open-sans-32-white.fnt'

After exploring the C:\nodejs\node_modules\jimp\dist folder, I found that the fonts folder didn't located at C:\nodejs\node_modules\jimp\dist\fonts\ but at  C:\nodejs\node_modules\jimp\fonts out of box. 

Is there any solution that can fix this issue? Any help is much appreciated.

**Comment by hipstersmoothie** [comment]
@chancein007 What version are you using? This should be fixed

**Comment by chancein007** [comment]
The version is   "jimp": "^0.3.2"

**Comment by hipstersmoothie** [comment]
This should be fixed in v0.3.3. But you should install latest (v0.3.4)

**Comment by chancein007** [comment]
many thanks
