### ISSUE TITLE
Can Jimp provide more size types of white color as black color?

### ISSUE THREAD

**Issue by chancein007** [oliver-moran/jimp#552]
Jimp  is great library.

As we known that Jimp default provide open-sans fonts with white color as below:
open-sans-8-white
open-sans-16-white
open-sans-32-white
open-sans-64-white
open-sans-128-white

Can Jimp provide more size types of white color as black color? For example, 
open-sans-10-white
open-sans-12-white
open-sans-14-white
open-sans-18-white

Thanks in advance

**Comment by hipstersmoothie** [comment]
It's pretty easy to make your own fonts. Try out the tools linked in the README

⭐️ http://kvazars.com/littera/

⭐️ https://github.com/libgdx/libgdx/wiki/Hiero

**Comment by chancein007** [comment]
many thanks
