### ISSUE TITLE
make jimp supporting otf font files

### ISSUE THREAD

**Issue by MLiranG** [oliver-moran/jimp#554]
please make jimp supporting otf font files, its making me go crazy becuase there isn't any otf to fnt font converters.

please, send me a online converter or make jimp support otf font files

**Comment by hipstersmoothie** [comment]
@MLiranG i just used hiero (linked in the readme) to convert an otf font with ease. I'll look into supporting those font types but it might not be possible

**Comment by hipstersmoothie** [comment]
I just looked into it more. this requires canvas to be available for jimp to render the text chars. 

To do this we would have to:

1. load font.
2. render chars to canvas
3. convert canvas to RGBA data

All the canvas for node implementations I have found require OS specific dependancies. This breaks the core rule of jimp "full javascript image manipulation". 

If you can find a good way to convert ttf and otf fonts to bitmap data we can go forward with this. Soon I am gonna make a plugin system available and you could make your own way to load and print these font type. Otherwise I do not think this should be in jimp core.

**Comment by luco** [comment]
+1 on this

**Comment by sops21** [comment]
> Hey @MLiranG, I know I'm really late to this, but using [BMFont by AngelCode](http://www.angelcode.com/products/bmfont/) I was able to convert an OTF font to .fnt - the software is a bit fiddly but it works great :)

@mattnotmitt Do you have settings that you are using for MBFont by AngleCode? I keep getting buffer errors when I try and use it.

**Comment by mattnotmitt** [comment]
@sops21 I used it to convert an entire CJK font so I'm not sure how you've managed to do that 😅 - if you could give me a link to it I'll take a look for you!

**Comment by freezegr** [comment]
I don't have pc and i can't use BMFont by AngelCode

**Comment by MLiranG** [comment]
> Hey @MLiranG, I know I'm really late to this, but using [BMFont by AngelCode](http://www.angelcode.com/products/bmfont/) I was able to convert an OTF font to .fnt - the software is a bit fiddly but it works great :)

_only_ 2 years and 1 month thats ok

**Comment by chahatbahl** [comment]
Go to website https://ttf2fnt.com/
Upload your font in ttf format
Choose color, size, ... and click convert
You will get fnt format which works is bitmap format

It works !!!

**Comment by freezegr** [comment]
> Go to website https://ttf2fnt.com/
> Upload your font in ttf format
> Choose color, size, ... and click convert
> You will get fnt format which works is bitmap format
> 
> It works !!!

Thanks

**Comment by NickBeukema** [comment]
If you're looking to do this from command line, I believe ttf2fnt uses [fontbm](https://github.com/vladimirgamalyan/fontbm) under the hood.

**Comment by xeoshow** [comment]
Hello, 
Is there any plugin for jimp to convert ttf to bmfont on the fly via API? 
We will need to use Chinese, which got many words(10000 or so), and for one API call, maybe only 10 words needed...

**Comment by jfederer** [comment]
> Hey @MLiranG, I know I'm really late to this, but using [BMFont by AngelCode](http://www.angelcode.com/products/bmfont/) I was able to convert an OTF font to .fnt - the software is a bit fiddly but it works great :)

How?

I have not had ANY success (from ttf font) using the BMFont from angelcode.  Are there settings I'm missing?  When I try to load the font using Jimp.loadfont I get "The source must be a Jimp image" error.
