### ISSUE TITLE
mimeType = "video/mp4" doesn't work 

### ISSUE THREAD

**Issue by ahmed-sharief5** [oliver-moran/jimp#557]
Hi, I am trying to create a thumbnail from video using your npm  but unfortunately its showing me the error mentioned in the title. Does not this package supports video format?? Please help me to resolve this issue

**Comment by hipstersmoothie** [comment]
Nope, jimp is for manipulating images, not videos. maybe try https://www.npmjs.com/package/quicklook-thumbnail

**Comment by ahmed-sharief5** [comment]
Ok thank you
