### ISSUE TITLE
[Bug] Composite Losing Saturation on Alpha Pixels

### ISSUE THREAD

**Issue by webcaetano** [oliver-moran/jimp#56]
Hi, First of all , i want to congratutions @oliver-moran for this awesome module. 
This is stuning awesome. :+1: 

-------------------------------------------
The bug. Png Alpha pixes are losing quality and saturation when the background is alpha.
But if the background is solid the alpha pixels are render 100% correct.

* In composite images*

Original 
![](https://raw.githubusercontent.com/webcaetano/image-scramble/master/test/1.png)

Write in Jimp
![](https://raw.githubusercontent.com/webcaetano/image-scramble/cecc51f1442621f6f17b2d3885f89c54fd603912/test/1_crop.png)

The yellow and green have 58% alpha... The stroke of this evil goblin have a bit glow alpha pixels. 

**Edit:
The problem happens when you make an image as new Jimp and use as composite.**

**Comment by webcaetano** [comment]
[Personal Fix] 

Buged Code 

```javascript
new Jimp(100,100,function(err, image){
```

Fix
```javascript
new Jimp('./test/emptyPixel.png',function(err, image){ 
// emptyPixel.png = image with 1x1pixels of 100% alpha
```
Unforntunatly it not accept the empty pixel image as Base64 like that.
```
new Jimp(new Buffer('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVQI12P4zwAAAgEBAKrChTYAAAAASUVORK5CYII=', 'base64'),function(err, image){ 
```

**Comment by webcaetano** [comment]
Change the background color from 
0x00000000
to 
0xffffff00

Make it brighter than normal.

**Comment by oliver-moran** [comment]
Thanks for catching this. It will be fixed in a new release over the weekend. The problem was down to a naive compositing algorithm. I've implemented a proper algorithm using the standard formula.

**Comment by webcaetano** [comment]
I saw. I tried to without success fix on jimp.scan myself. 
Fortunatly jimp.blit is all i need for my project.
I really enjoy code in jimp.

Jimp > All others.
