### ISSUE TITLE
Jimp UTIF dependency breaking elasticbeanstalk/AWS deploys

### ISSUE THREAD

**Issue by rxluz** [oliver-moran/jimp#560]
# Expected Behavior

The application runs without errors

# Current Behavior

When I tried to update JIMP to 0.3.5 it's break my AWS deploy once UTIF uses jpgjs from github, not from npm, probably AWS doesn't accept this dependency type

## Steps to Reproduce

1. Update JIMP to 0.3.5
2. Deploy to elasticbeanstalk/AWS

## Context

-   Jimp Version: 0.3.5
-   Operating System: Linux
-   Node version: 8.9.3

## Failure Logs
I received this message:

Error: Cannot find module 'jpgjs'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /var/app/current/node_modules/utif/UTIF.js:10:74
    at Object.<anonymous> (/var/app/current/node_modules/utif/UTIF.js:911:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/app/current/node_modules/*jimp*/dist/utils/image-bitmap.js:20:36)

**Comment by hipstersmoothie** [comment]
@rxluz do you have git installed?

**Comment by hipstersmoothie** [comment]
Also please post a comment here. https://github.com/photopea/UTIF.js/issues/39 The more complaining we do the faster they can merge

**Comment by lipho** [comment]
We are encountering this issue.  Have git installed in the container and also have other git/github dependencies resolve correctly.

**Comment by hipstersmoothie** [comment]
@lipho  can you go to the mentioned issue and comment there too?  Part of the problem is that they’re using an unmaintained fork of that library

**Comment by hipstersmoothie** [comment]
Oh yeah there was a bug for git resolution in older nom. @lipho I’d still appreciate a comment of the utif issue!

**Comment by rxluz** [comment]
@hipstersmoothie Yes I have, but the issue isn't in my local environment, the problem is when I try to update the application to AWS, probably they don't accept git dependencies in package.json, I backed to Jimp 0.2.28 version and worked well

**Comment by hipstersmoothie** [comment]
Check your node version. I’m gonna do a release tomorrow that allows you to
exclude tiff as a image option

**Comment by rthomps7** [comment]
I've actually seen this issue in a couple other places: Heroku deploys and CI integrations.

What's odd is it seems inconsistent. Sometimes I redeploy without any changes (or rerun my CI) and things work.

**Comment by hipstersmoothie** [comment]
If you care about this issue please go bug the project owners on this issue. https://github.com/photopea/UTIF.js/issues/43 and 🙏 for a fast release.

**Comment by cccRaim** [comment]
I rollback version to `0.2.28`, and remove the `jpgjs` dependency successful.  

---
I just need change 'xxxxxAsync' to 'xxxxx'.
Because I don't use `tiff`, so the downgrade action is convince for me.

**Comment by hipstersmoothie** [comment]
Please go comment on the above issue. I can help you set up a custom
versions of jimp. It’s quite easy

**Comment by hipstersmoothie** [comment]
Released in [v0.4.0](https://github.com/oliver-moran/jimp/releases/tag/v0.4.0)
