### ISSUE TITLE
Wrong documentation for buffer constructor.

### ISSUE THREAD

**Issue by luigi-rosso** [oliver-moran/jimp#565]
# Intro
This documentation is wrong:
```js
new Jimp({ buffer: buffer, width: 1280, height: 768 }, (err, image) => {
    // this image is 1280 x 768, pixels are loaded from the given buffer.
});
```

# Expected Behavior
Construct an image from a buffer by calling: 

```js
new Jimp({buffer: buffer, width: width, height: height});
```

# Current Behavior
Error occurs complaining about unexpected/wrong parameters.

# Failure Information
I peaked through the source and realized that the buffer field is actually expected to be named **data**. This will work:
```js
new Jimp({ data: buffer, width: 1280, height: 768 }, (err, image) => {
    // this image is 1280 x 768, pixels are loaded from the given buffer.
});
```

Relevant internal code here:
https://github.com/oliver-moran/jimp/blob/d23d5ecbc470d66006505d05471d12f21f94242c/packages/core/src/index.js#L97

**Comment by hipstersmoothie** [comment]
Wanna make a PR? @luigi-rosso

**Comment by d07RiV** [comment]
Just ran into the same issue and got the same answer after debugging. +1

**Comment by luigi-rosso** [comment]
Thanks for submitting @d07RiV! 

I hadn't submitted one myself as I wanted to give the author the option of deciding whether to change the docs or the code. Not sure which is preferred, but the name **buffer** is nice as it also implies the expected type.
