### ISSUE TITLE
NPM and github are out of sync but have the same package.config version

### ISSUE THREAD

**Issue by davidlashlee** [oliver-moran/jimp#58]
tried playing around with jimp.

installed via ```npm install jimp@latest```

tried following the advice on the github readme.

got jimp.read was undefined.

check package.config says verison 0.2.10

checked the npm package.config says same version as github @ 0.2.10

followed the documentation in the npm readme and everything worked fine.

https://www.npmjs.com/package/jimp seems to be behind.

**Comment by oliver-moran** [comment]
@davidlashlee yes, I did a major change over the weekend: https://github.com/oliver-moran/jimp/issues/58

The change is backwards compatible but, for simplicity, I work off just one main branch. This obviously causes confusion if you are reading the docs on GitHub.

I've published the change to NPM now. Please let me know what you think of the new API.
