### ISSUE TITLE
Custom color for the contain function

### ISSUE THREAD

**Issue by christofferEkblom** [oliver-moran/jimp#580]
# Expected Behavior
If you use the contain function and pick a value that is higher than the image size, you should be able to set a custom color.

# Current Behavior
The current color is rgb(0,0,0).

**Comment by hipstersmoothie** [comment]
@christofferEkblom contain will use the `_background` color for those pixels. you can use the `background` function to set this value

```js
async function test(params) {
  const image = await Jimp.read('./exampleImages/bit32_alpha_out.bmp');

  image
	.background(0x0000ffff)
	.contain(2000, 1500)
	.write('modified.png', console.log)
}

test()
```
