### ISSUE TITLE
v0.4.0

### ISSUE THREAD

**Issue by hipstersmoothie** [oliver-moran/jimp#590]
I would like to get a release out this weekend. I just got publish access for https://github.com/photopea/UTIF.js/ so we can close #560 

What I would like in the release:

Features:
* #586
* #589 
* #588 
* #585 

Bugs
* #587 
* #560

@edi9999

**Comment by edi9999** [comment]
Yes, good idea ! So you will  publish all packages and plugin in version 0.4.0 ?

**Comment by hipstersmoothie** [comment]
I'm pretty sure that lerna will do that. If i understand correctly it keeps all the package numbers in sync default. some packages didn't bump last time though. Maybe a minor will force bump them all?

**Comment by hipstersmoothie** [comment]
The monorepo is live btw. I think it went out with 0.3.9. Everything is currently published

**Comment by edi9999** [comment]
Ok ! Good

**Comment by hipstersmoothie** [comment]
0.4.0 released https://github.com/oliver-moran/jimp/releases/tag/v0.4.0
