### ISSUE TITLE
Multiple transformations with best quality and minimal bytes

### ISSUE THREAD

**Issue by canvas-manik** [oliver-moran/jimp#60]
Hi Oliver,

Thank you for your quick responses to all of my queries. 

As, you suggested, I am now uploading the original images, without using HTML Canvas object on client.
I am looking for rotating the image and making the multiple sizes of the images, viz. large, medium, small.

I am loading the image on server using Jimp.read and then EXIF rotating the image. After that keeping the object, I am creating a clone of the image and then creating multiple sizes of images. 

I want to know if my approach is right keeping in mind the minimal of bytes, best of image quality and server performance. Also, I want to know, what should be optimal quality setting I should use. Should it be fine at 60% or it requires 70%?

Thanks a lot for your help,
Manik Mittal

**Comment by oliver-moran** [comment]
You overall approach sounds good. With regard to JPEG compression see the first answer here and follow the link to the interactive demonstration of different quality settings: http://photo.stackexchange.com/questions/30243/what-quality-to-choose-when-converting-to-jpg
