### ISSUE TITLE
JPG read error on some photos, which can be viewed by normal tools with no problem

### ISSUE THREAD

**Issue by KangarooBee** [oliver-moran/jimp#603]
# use jimp read function like below, but got error.
jimp.read(targetjpg, function (err, demo) {
	 if (err) throw err;
 if ((demo.bitmap.width==640 && demo.bitmap.height==480)
........

# some JPG photo (photo taken by different devices, android camera, micro controller controlled camera)
,which can be view by normal picture tool, but can not be read by Jimp, the error message is "if (err) throw err;  ReferenceError: width is not defined"
Not all photo can not be read, but only a small portion

# Failure Information (for bugs)

ReferenceError: width is not defined

## Context

- Jimp Version: 
- Operating System: centos 7
- Node version: v8.9.4

## Failure Logs

![20180829080751](https://user-images.githubusercontent.com/43085373/45251026-caf93f80-b32e-11e8-946b-87e6eb36c67c.jpg)
![20180908095437a](https://user-images.githubusercontent.com/43085373/45251028-efedb280-b32e-11e8-84ae-713dd1126fcd.jpg)

**Comment by hipstersmoothie** [comment]
@KangarooBee what jimp version are you on?

**Comment by hipstersmoothie** [comment]
```js
```

**Comment by KangarooBee** [comment]
@hipstersmoothie Thanks for the reply!

I rechecked the code, there is some variable mismatch in my program. Due to unfamiliar with the call back method, thought it is a Jimp problem.  As you said, Jimp works fine. 

My bad, for this issue reporting. I am closing it. Or you can delete it. 

Thank you again for your time and contribution!
