### ISSUE TITLE
Whitespace not erased when aligning text to the right / center

### ISSUE THREAD

**Issue by rossbulat** [oliver-moran/jimp#610]
# Expected Behavior
The last character of a line of text should not be whitespace. Some weird stuff is happening when you align text to the right. Maintains whitespace, sometimes more than 1 space.

Spaces to be removed at the alignment side (right side in this case) 

# Current Behavior

Some weird stuff is happening when you align text to the right. Maintains whitespace, sometimes more than 1 space.

Also when aligning to the center, takes into consideration whitespace and therefore is not perfectly aligned.

## Steps to Reproduce

```
.then(font => {

	let maxWidth = 679;
	let maxHeight = 64;

	tpl.print(
		  font,
		  10,
		  10,
		  {
		        text: 'My text here',
			alignmentX: Jimp.HORIZONTAL_ALIGN_RIGHT
		   },
		   100,
		   100
         );
});
```

## Context

- Jimp Version: 0.4.0
- Operating System: Mac OS
- Node version: 10.7.0

**Comment by hipstersmoothie** [comment]
Released in [v0.5.0](https://github.com/oliver-moran/jimp/releases/tag/v0.5.0)
