### ISSUE TITLE
Is it possible to use new color modification rules in plugin-color?

### ISSUE THREAD

**Issue by forethoughtde** [oliver-moran/jimp#618]
I have noticed that there are only few color modification rules are defined. I have a scenario where I should be able to change image color to any given **Hex Color Code**(#800000, #637B80, #F6AE99). I would like to know if it is possible to achieve using jimp?

If yes, how can I go about achieving this? 

Thanks

**Comment by forethoughtde** [comment]
The first one

**Comment by hipstersmoothie** [comment]
If you are just changing one solid color to another why not just create a new image?

```js
const image = await Jimp.create(300, 300, '#800000')
```

**Comment by forethoughtde** [comment]
@hipstersmoothie I already have images which needs to be changed to different color and saved in a directory. Please chech the attached image.  
![turbine_sgt5_2000e_10](https://user-images.githubusercontent.com/9781577/45738831-b7cd5600-bbf1-11e8-89d8-44f8c7886a4f.png)

**Comment by hipstersmoothie** [comment]
what would you want the output to look like? like a blue pipe?

**Comment by forethoughtde** [comment]
For instance, the output image should be in the following colors;
1. #ff33cc, 
2. #0066ff

**Comment by hipstersmoothie** [comment]
I'm not sure i can picture what that would look like. You want jimp to somehow divide up all the colors and only render them those two colors?

**Comment by forethoughtde** [comment]
Please check this. 
![turbine_sgt5_2000e_10_ 0066ff](https://user-images.githubusercontent.com/9781577/45739301-ed267380-bbf2-11e8-935f-10b7670c6250.png)

**Comment by hipstersmoothie** [comment]
The method I described in the linked issue generates this

```js
const Jimp = require('jimp');

test()

async function test() {
  const image = await Jimp.read('./exampleImages/pipe.png');

  image
    .grayscale()
    .color([{ apply: 'mix', params: ['#ff33cc'] }])
    .writeAsync('test.png');
}
```

![test](https://user-images.githubusercontent.com/1192452/45739608-3bfaeb80-bba8-11e8-9238-604e66f98783.png)

**Comment by forethoughtde** [comment]
Can I please know why are you using  grayscale() on the image?

**Comment by hipstersmoothie** [comment]
If you just mix then some other colors get mixed in. just check the result yourself and you will see. Going to greyscale makes the image black and white only so it is easier to mix in just the one color

**Comment by MuruganSCT** [comment]
I want to change watermark text color into orange, but when i used color function it changed image color. how can i do it? any suggestions...
