### ISSUE TITLE
write() image fires the callback before the full image is written

### ISSUE THREAD

**Issue by ettmobile** [oliver-moran/jimp#62]
Hi, 
we are encountering occasional issues whereby the image is still being written while the callback has already fired.  The problem is in the Jimp.prototype.write whereby the callback is returned within the "open" stream event.  To fix the issue, update this section as follows:

```js
    this.getBuffer(mime, function(err, buffer) {
        if (err) return throwError.call(that, err, cb);
        var stream = FS.createWriteStream(path);
        stream.on("open", function(fh) {
            stream.write(buffer);
            stream.end();
//            return cb.call(that, null, that);
        });

        stream.on("finish", function(fh) {
            return cb.call(that, null, that);
        });

    });
```

Many thanks!

Paul

**Comment by oliver-moran** [comment]
Thanks a lot, Paul. If you do a pull request I'll pull it in. Otherwise, I'll add it to the next release manually.

**Comment by ettmobile** [comment]
Hi, can you please add this manually (copy and paste) as I don't have a lot of time at the moment.   Is there any chance you can release an interim release today or tomorrow, as we have a launch next week.
Thanks!
Paul

**Comment by oliver-moran** [comment]
Okey-doke. That's in and released to NPM. Thanks for the catch.

**Comment by ettmobile** [comment]
Hi Oliver,

Thank you for the quick turnaround!

Cheers,

Paul
