### ISSUE TITLE
aws lambda and webpack

### ISSUE THREAD

**Issue by dragouf** [oliver-moran/jimp#641]
# Expected Behavior

I try to use jimp with webpack to execute it on aws lambda. 

# Current Behavior

unfortunately it crash when I just try to read image from base64 with :
```
const Jimp = require('jimp');
async getImageAsync() {
    let img = await Jimp.read(Buffer.from(base64Img, 'base64'));
}

getImageAsync();
```

# Failure Information (for bugs)

it return something like o.read is not a function

## Steps to Reproduce

here is my webpack.config.js :
```
const path = require('path');

module.exports = {
  entry: './index.js',
  target: 'node',
  output: {
    libraryTarget: 'commonjs',
    filename: 'index.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

then just run webpack and upload index.js from dist folder

## Context

- Jimp Version: 0.5.3
- Operating System: aws lamda
- Node version: 8.1.0

## Failure Logs
```
TypeError: o.read is not a function
at t.exports.getImageAsync (/var/task/index.js:10:40130)
at e.handler (/var/task/index.js:10:313576)
```

So is there something to do to use jimp with webpack on node (here aws lambda but it may be same as just node) ?

**Comment by dragouf** [comment]
ok it works with 
```
const Jimp = require('jimp/dist');
```

**Comment by hipstersmoothie** [comment]
So what I think is happening is webpack is resolving the "browser" field first. since you are targeting node its breaking.

You can configure what webpack resolves first. since we ship a module build you could use that instead.

https://twitter.com/HipsterSmoothie/status/1023453544710516738

You'll probably want:

```json
{
   resolve: [ "module", "main" ]
} 
```

**Comment by hipstersmoothie** [comment]
Feel free to open another issue if this doesn't resolve it. I'm pretty sure it does.
