### ISSUE TITLE
color manipulation not working

### ISSUE THREAD

**Issue by gvelasquez760** [oliver-moran/jimp#648]
# Expected Behavior

im tryng to manipulate r,g,b of a image object

# Current Behavior

Throw the error:  TypeError: Cannot read property 'constructor' of undefined

# Failure Information (for bugs)

im tryng to run a basic code like the example:

```
async function main() {
  const image = await Jimp.read('./test.jpg');
  image.color([{ apply: 'red', params: [100] }]);
}

main();
```

Thanks!

**Comment by hipstersmoothie** [comment]
fixed in v0.5.5
