### ISSUE TITLE
global polyfill overwriting native Promise

### ISSUE THREAD

**Issue by mgh** [oliver-moran/jimp#65]
Polyfilling globally has the (unintended?) consequence of overwriting the native Promise implementation if it exists in node (or other polyfills).  When used as a library in a larger project, this seems undesirable.  It probably doesn't cause many bugs (it caused one in a project I am working on), but it does cause confusion, and I'd suggest an explicit `var Promise = require('es6-promise').Promise` in any file that needs a `Promise` instead of the polyfill.

Further discussions [here](https://github.com/jakearchibald/es6-promise/search?q=%22%5Bobject+Promise%5D%22&type=Issues&utf8=%E2%9C%93)

**Comment by oliver-moran** [comment]
Thanks. I'll change it to this in the next release (tonight):

```js
var Promise = Promise || require('es6-promise').Promise;
```

You think that will work?
