### ISSUE TITLE
Error on read function

### ISSUE THREAD

**Issue by RezaT1994** [oliver-moran/jimp#655]
# Expected Behavior
It should resolve the image in promise, but it's return an error.

# Current Behavior
The error I get: 
`TypeError: Cannot read property 'image/jpeg' of undefined`

- Jimp Version: @jimp/types@0.5.4
- Operating System: Windows
- Node version: 10.13.0

**Comment by hipstersmoothie** [comment]
Can i get the image and code to reproduce this problem? Cant do much without that

**Comment by RezaT1994** [comment]
```typescript
import Jimp from '@jimp/core';

resize(image, resizedImage, size) {
    Jimp.read(image).then((img) => {
        img.scaleToFit(size.width, size.height).write(resizedImage);
    }).catch((err) => {
        console.log(err);
    });
}
```

Image:
![15419512476045439](https://user-images.githubusercontent.com/31609638/48334660-ac862c00-e670-11e8-96bb-9a9c0a4fb217.jpg)

**Comment by RezaT1994** [comment]
I change the import line to this:
`import jimp from 'jimp';`

Now it returns `TypeError: Cannot read property 'read' of undefined`

I'm using it just like this [link](https://github.com/oliver-moran/jimp/tree/master/packages/plugin-resize)

**Comment by hipstersmoothie** [comment]
This following code works 

```js
const Jimp = require('jimp');

test();

async function test() {
  const image = await Jimp.read('./exampleImages/wings.jpg');

  image
    .resize(500, 500)
    .scaleToFit(500, 500)
    .write('test.png');
}
```

They way resize works is not how you're calling it. It doesn't take 3 args. So i'm not sure your code is doing what you intend. At least that's not how jimp's resize works

**Comment by hipstersmoothie** [comment]
oh okay i understand you code more now `resize` is a function you've defined

**Comment by RezaT1994** [comment]
I'm using typescript, not javascript

**Comment by hipstersmoothie** [comment]
The following works as well

```js
const Jimp = require('jimp');

resize('./exampleImages/wings.jpg', 'test.png', {
  width: 500,
  height: 500
});

function resize(image, resizedImage, size) {
  Jimp.read(image)
    .then(img => {
      img.scaleToFit(size.width, size.height).write(resizedImage);
    })
    .catch(console.log);
}
```

**Comment by hipstersmoothie** [comment]
@RezaT1994 can i close?

**Comment by RezaT1994** [comment]
Yes, thank you. solved my problem
