### ISSUE TITLE
How change depth color?

### ISSUE THREAD

**Issue by maikelag** [oliver-moran/jimp#656]
how to convert png image from 24 to 8 bit

**Comment by hipstersmoothie** [comment]
You can try fiddling with the pngjs options. But if pngjs doesn’t support it jimp won’t be able to encode to that bit depth

**Comment by thbl** [comment]
+1

**Comment by Ronkiro** [comment]
+1

**Comment by Ronkiro** [comment]
I managed to using ImageMagisk module. (Prefixing with PNG8)
