### ISSUE TITLE
Write/read error: no such file or directory

### ISSUE THREAD

**Issue by Romans96** [oliver-moran/jimp#661]
i have this code:

```
const i = await jimp.read("./img/nero.jpg");
		//const srcImage = await jimp.read("./img/v.png");
		const font = await jimp.loadFont('./font/Windlass.fnt' /*jimp.FONT_SANS_32_WHITE*/);
		await i.resize(532,392);
		await i.print(font, 50, 50, 'Hello World!', 500);
		await i.print(font, 200, 50, 'Test 2a riga', 500);
		//i.composite(srcImage, 100, 0);
		await i.write('./nero.jpg', err => console.error('write error: ', err));
		await msg.channel.send({
			files: [
			  "./nero.jpg"
			]
		});
		fs.unlinkSync('./nero.jpg');
```

It gives 1 time on 2, Error: ENOENT: no such file or directory, stat 'D:\Discord Bot\gamertags-img\nero.jpg'. I tried some things, searched, but nothing works...

**Comment by hipstersmoothie** [comment]
Basically your problem was using the callback style `write` instead of the promise based `writeAsync`

Things I changed:

- only function on the image with async in the name are async. so only they need to be awaited, not any image manipulation operations
- you can chain image manipulation function if you want
- write -> writeAsync - writeAsync will actually return a promise
- remove callback - writeAsync will throw an error and not use the callback for the error

```js
const image = await jimp.read('./img/nero.jpg');
const font = await jimp.loadFont(
  './font/Windlass.fnt' /*jimp.FONT_SANS_32_WHITE*/
);

await image
  .resize(532, 392)
  .print(font, 50, 50, 'Hello World!', 500);
  .print(font, 200, 50, 'Test 2a riga', 500);
  .writeAsync('./nero.jpg');

await msg.channel.send({
  files: ['./nero.jpg']
});
fs.unlinkSync('./nero.jpg');
```js

**Comment by Romans96** [comment]
> Basically your problem was using the callback style `write` instead of the promise based `writeAsync`
> 
> Things I changed:
> 
> * only function on the image with async in the name are async. so only they need to be awaited, not any image manipulation operations
> * you can chain image manipulation function if you want
> * write -> writeAsync - writeAsync will actually return a promise
> * remove callback - writeAsync will throw an error and not use the callback for the error
> 
> ```js
> const image = await jimp.read('./img/nero.jpg');
> const font = await jimp.loadFont(
>   './font/Windlass.fnt' /*jimp.FONT_SANS_32_WHITE*/
> );
> 
> await image
>   .resize(532, 392)
>   .print(font, 50, 50, 'Hello World!', 500);
>   .print(font, 200, 50, 'Test 2a riga', 500);
>   .writeAsync('./nero.jpg');
> 
> await msg.channel.send({
>   files: ['./nero.jpg']
> });
> 
> fs.unlinkSync('./nero.jpg');
> ```

I tried changing in writeAsync, but it continues to gives the same error at Object.fs.unlinkSync

**Comment by Romans96** [comment]
ok tried again changin a bit of things, and now it seems it works. The only moment where it didn't works, was when i type the command before the bot/program hadn't sent the image (and the fs unlinked)

Thank you so much
