### ISSUE TITLE
writeAsync seems not finished

### ISSUE THREAD

**Issue by RDeluxe** [oliver-moran/jimp#668]
# Expected Behavior

After calling `await image.resize().writeAsync(p)` I should be able to upload it on AWS S3 without issue.

# Current Behavior

Currently, I need to add a timeout after `writeAsync`, based on the file size (longer for bigger size) to be sure that I can upload my file

# Failure Information (for bugs)

I'm getting "File not found, ENOENT" errors.

## Steps to Reproduce

Here is a snapshot of my code : 

``` typescript 
public async uploadAndSaveWithTx(file: ToUpload, manager: EntityManager, type?: PictureType) {
    const p = file.path;

    try {
      // TODO: This is small helper, for an unknown reason Jimp.writeAsync() seems to return to soon
      const timeout = (ms: number) => {
        return new Promise(res => setTimeout(res, ms));
      };

      let awsStored: ManagedUpload.SendData;

      const image = await Jimp.read(p);

      if (type) {
        // We use only height to resize, Jimp will preserve ratio
        const newHeight = config.upload.resizedHeights[type];

        // resize image to dimension
        await image.resize(Jimp.AUTO, newHeight).writeAsync(p);
      }

      // This code makes the whole thing work quite OK even for big files
      const size = (await image.getBufferAsync(file.mimetype)).byteLength;
      await timeout(size / 500);

      // Uploading the file
      awsStored = await upload(p, file.filename, file.mimetype);

      // Delete original file
      await fs.unlink(p);


      // Database code
      const media = new MediaEntity();
      media.awsKey = awsStored.Key;
      media.publicUrl = awsStored.Location;

      return super.createWithTx(media, manager);
    } catch (e) {
      await fs.unlink(p);
    }
  }
```

The AWS upload code : 

``` typescript
export async function upload(
  path: string,
  filename: string,
  mimeType: string,
): Promise<AWS.S3.ManagedUpload.SendData> {
  const ext = config.upload.extByMime[mimeType];

  const fileStream = await fs.createReadStream(path);

  const params: AWS.S3.PutObjectRequest = {
    Key: filename + '.' + ext,
    Body: fileStream,
    Bucket: config.aws.bucket,
    ACL: config.aws.fileAcl,
    ContentType: mimeType,
    CacheControl: 'public, max-age=2592000',
  };

  if (ext !== 'jpg' && ext !== 'png') params.ContentEncoding = 'base64';
  return s3.upload(params).promise();
}
```

## Screenshot

<img width="681" alt="applicationframehost_2018-11-29_00-49-08" src="https://user-images.githubusercontent.com/2767681/49189986-c4e48f00-f370-11e8-8f79-b61c2778a667.png">

## Context

- Jimp Version: 0.5.4
- Operating System: Alpine docker container, volume in windows (but same error in k8s)
- Node version: 8

**Comment by hipstersmoothie** [comment]
Super weird. Maybe we are doing something wrong with out promises? 

Relevant code:

writeAsync fn:
https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js#L556

promisify:
https://github.com/oliver-moran/jimp/blob/master/packages/core/src/utils/promisify.js

write fn:
https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js#L549

Is it possible for you to walk thought the code and see what's happening? Maybe it's something to do with the pipes? I am not at all familiar with pipes so this part of the code is a little fuzzy to me. Would be awesome if you could step through it a little to see what's really happening!

**Comment by RDeluxe** [comment]
Well, actually even without trying to upload (commenting all the code linked to AWS) the error still happens.

I'm wondering if chaining like this is not causing a problem, as `resize` is asynchronous too.

**Comment by RDeluxe** [comment]
Ok, it crashes before any file operation, it seems `Jimp.Read()` is the culprint.

``` typescript
      const exists = await fs.exists(p);
      console.log(exists);
      const image = await Jimp.read(p);
      console.log('read');
```

This crashes before the `console.log('read')`, but the file always exists.

**Comment by RDeluxe** [comment]
I'm closing this, it seems that this bug is not related to Jimp in any way, but to some issues with FS in a shared volume between windows and a linux container. The file exists, but is apparently not readable (the first file uploaded is, but after that I'm getting only errors).

**Comment by hipstersmoothie** [comment]
Cool!
