### ISSUE TITLE
Quite different images give a 0 (zero) distance (!)

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#67]
The two images blow give a zero distance...

Test code:

    var Jimp = require('jimp');

    var imageName1 = __dirname + '/' + 'img.jpg';
    var imageName2 = __dirname + '/' + 'img2.jpg';

    Jimp.read(imageName1, function(err, image1) {
      if (err) {
        return console.error(err);
      }
      Jimp.read(imageName2, function(err, image2) {
        if (err) {
          return console.error(err);
        }
        console.log('Distance betweer images is:', Jimp.distance(image1, image2));
      });
    });

(their distance does not seem *zero*, to me... :-)

![img](https://cloud.githubusercontent.com/assets/849127/11039776/9265ffae-8709-11e5-98ae-8a3fa88533f1.jpg)
![img2](https://cloud.githubusercontent.com/assets/849127/11039777/956f13b6-8709-11e5-8062-c918441efb3e.jpg)

Do I miss something?

**Comment by oliver-moran** [comment]
This is the same issues as with Taylor in #66. Use the latest version of phash.js straight from GitHub. Just copy and paste it over the one in your `node_modules` directory. When you do that it will work:

```
Hillary: 			cAjc7i6AH1r
Hillary (scribble):	e0kL7a0k9hi

Distance:	0.3125
Diff:		0.2898695136417556
```

I'll release it tonight. Sit tight.

**Comment by marcolino** [comment]
Thanks... Just testing...

I plan to use distance (because it's a value can be pre-calculated and saved to DB, and to check for image duplication I just need a hamming distance, for every DB image).

To use diff() I should call it once for each DB image, right? I'm afraid it should be too slow (db is expected to reach ~750K  images...). Correct me if wrong, please...

One more thing, about hashes lengths: you said it is due to chance... But so I can't expect hashes lengths to be all the same? But if they do differ, how do I calculate a distance???
Thanks for your attention!

**Comment by marcolino** [comment]
While calculating hashes for my images, I get:

    my-app/node_modules/jpeg-js/lib/decoder.js:323
            throw "marker was not found";
            ^
     marker was not found
    [21:20:35] [nodemon] app crashed - waiting for file changes before starting...

and my app crashes... Probably the image was empty, but Jimp should try to catch these errors, to avoid crashing, right? I (Jimp user) could catch these exceptions, too, but...

**Comment by oliver-moran** [comment]
I think your strategy regarding distance and diffing sounds good.

About exceptions: Errors in Jimp are handled by throwing exceptions (unless a Node-style callback is passed). Yes, that will crash your app but I'm delegating that to you to catch. Most are a straight-forward case of a wrong argument being passed to a method so I'm surprised at the error you got.

To compute the hammering distance, you would be better off converting the base 64 hash to binary and padding to 64 digits with leading zeros as necessary. You can get the binary quite easily with: `image.hash(2);` Compute the hammering distance against those.

I'm planning on padding each the hashes with leading 0s as necessary for this reason.

**Comment by oliver-moran** [comment]
I've also just made a fix where hashes will be returned with leading zeros. This will make it easier to compare binary hashes stored in a DB for hammering distance.

**Comment by marcolino** [comment]
This night I did realizewhy 11... :-)

**Comment by marcolino** [comment]
Correct me if wrong: to encode a byte in base64 you need 6 bits (2^6 = 64). Then to encode 64 bits you need 11 base64 bytes (64 / 6 = 10.6...) (i.e.: you need 10 full base64 bytes, plus one, that you'll use for the last 4 bits... Hence, no need for padding, it's automatic...
Please don't tell me I'm completely wrong... :-D

**Comment by oliver-moran** [comment]
The padding is in case is if the first bit is not 1:

```
var white = new Jimp(256, 256, 0xFFFFFFFF);
var black = new Jimp(256, 256, 0x000000FF);

console.log("W: " + white.hash(2));
console.log("B: " + black.hash(2));

// Output:
// W: 1000000000000000000000000000000000000000000000000000000000000000
// B: 0000000000000000000000000000000000000000000000000000000000000000

console.log("W: " + white.hash(64));
console.log("B: " + black.hash(64));

// Output:
// W: 80000000000
// B: 00000000000
```

**Comment by marcolino** [comment]
Perfect...

--
Marco Solari
System Analyst, Software Engineer and IT Consultant at Koinè Sistemi Torino

**Comment by marcolino** [comment]
Already in NPM ?

--
Marco Solari
System Analyst, Software Engineer and IT Consultant at Koinè Sistemi Torino
