### ISSUE TITLE
Can't crop small images RangeError

### ISSUE THREAD

**Issue by YoavSarfaty** [oliver-moran/jimp#673]
# Expected Behavior

I am trying to detect if an image is inside another image by looping with an xoffset and yoffset and comparing the one image with a subsection of the other using crop()

# Current Behavior

But when i try to crop with the xoffset as anything above 0 it fails with an `RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9212. Received 9216`

This is my code:
`for (let xoff = 0; xoff < 10; xoff++) {
      for (let yoff = 0; yoff < 10; yoff++) {
        // console.log(xoff, yoff);
        let img = {
          img: originalimg.img.clone().crop(xoff, yoff, 48, 48),
          value: originalimg.value
        };
        // console.log(img);
        let dist = jimp.distance(shot, img.img);
    }
}`

# Failure Information (for bugs)

## Steps to Reproduce

This happens sometimes but only with small images (48*48).

## Context

- Jimp Version: 0.6.0
- Operating System: windows 10 64 bit build 17134.407
- Node version: 10.13.0

**Comment by YoavSarfaty** [comment]
Sorry this is my code not jimp!

**Comment by hipstersmoothie** [comment]
Glad you solved your problem!

**Comment by wantao666** [comment]
i meet the same problem with you . can you say how to resolve it finnally? @YoavSarfaty

**Comment by mbehzad** [comment]
Hi @YoavSarfaty , can you remember what was the issue? and how did you solved it?

**Comment by nathanfranke** [comment]
I think this happens when you try to `crop` when `x >= width` or `y >= height`
