### ISSUE TITLE
Create an image from scratch in browser

### ISSUE THREAD

**Issue by marktani** [oliver-moran/jimp#677]
**Is your feature request related to a problem? Please describe.**
I want to create a new image from scratch without reading an image before. I am in the browser.

**Describe the solution you'd like**
An API to create a new image buffer from scratch, given a certain size. `Jimp.create(300, 300)` creates a new 300x300 image buffer, on which I could run the normal Jimp API.

**Comment by marktani** [comment]
Found this API, `read` should work:

```
const image = await Jimp.read(1000, 1000, 0x0000ffff);
```

**Comment by hipstersmoothie** [comment]
If you want your code to read a little clearer you can use `Jimp.create` its just sugar
