### ISSUE TITLE
How do I add a watermark?

### ISSUE THREAD

**Issue by androetto** [oliver-moran/jimp#678]
Hi, i read post on watermark but not resolve my problem. Until now have is it:

function waterMark() {
    

    const image =   Jimp.read('./original.png');
    const watermark =   Jimp.read('./watermark.png');
  
    image.composite(watermark, 0, 0, {
      mode: Jimp.BLEND_SOURCE_OVER,
      opacityDest: 1,
      opacitySource: 0.5
    })
  
    image.writeAsync('originalwithmark.png');

}

Response : image.composite is not a function

Somebody could help me?

**Comment by hipstersmoothie** [comment]
When using promises you must either `await` or use `then`.

```js
async function waterMark() {
  const image = await Jimp.read("./original.png");
  const watermark = await Jimp.read("./watermark.png");

  image.composite(watermark, 0, 0, {
    mode: Jimp.BLEND_SOURCE_OVER,
    opacityDest: 1,
    opacitySource: 0.5
  });

  await image.writeAsync("originalwithmark.png");
}
```

**Comment by hipstersmoothie** [comment]
The original post had the awaits too. You cannot just delete them and expect the code to work.
