### ISSUE TITLE
Just a behaviour note...

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#68]
It's not an issue, just a note.

I'm testing `hash()` function.

I find signatures it generates are quite effective to calculate the *distance* among two images.

However I notice that the hashes (*perceptual hashes*) are not as 'sensible' as I'd expect to: sometimes 
making a small change to an image does not change the hash (and then the distance) at all (0 bits changed), while sometimes a similar change makes a 2% difference...

I suppose this behaviour can be expected knowing the internals of perceptual hashes algorithm, but it's not always aligned with humanly preceived distance...

**Comment by oliver-moran** [comment]
Yes. I think that raises a question about how sensitive you expect it to be.

I also think it's a question of the right tool for the job:

When I wast testing it, I used a cut-off of 15%, so 2% would be considered a match. And they are, if you are testing for similarity.

On the other hand, if you are testing for **difference** then the `image.diff` method is probably the better tool.

**Comment by marcolino** [comment]
I meant  an *additional* 2%, I was verifiyng how many additional changes to an image would cause the threshold (I currently use 12%) to be overcome...

On the other hand, I don't completely understand the distinction you make between **similarity** and **difference**... Ultimately, they are just two different algorithms (one from 'pHash' and one from 'PixelMatch') to measure the same entity... Or am I wrong?

**Comment by oliver-moran** [comment]
They are two different algorithms though.

If pHash and PixelMatch were people, pHash would scrunch up its eyes and say that a cat looks like a dog. PixelMatch, on the other hand, would carefully detail all the things about a cat that a different to a dog within a given threshold.

Both are right. pHash is good at finding similarity. PixelMatch is good at finding difference.

**Comment by marcolino** [comment]
I see... Your metaphor was great! :-) Now I clearly understand what you meant...
Now I'm even more convinced I'll use pHash (`Jimp.hash()`) to find similarities on my images...
Thanks a lot, Oliver!
