### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Allaphy** [oliver-moran/jimp#688]
Well, i can't find anything undefined or null on my code, thats why i came here. I hope that one of you may tell me what is wrong in this code.

part of the code:

var imgs = [userGlobal[sender.id].petImg, userGlobal[sender.id].petIlha];
const jimps = await Promise.all(imgs.map(img => jimp.read(img)));

var pxp = userGlobal[sender.id].petxp;
var pbs = userGlobal[sender.id].petbase;
var plvl = userGlobal[sender.id].petlvl;
var pxpf = pxp.toString() + "/" + pbs.toString();
var plvl2 = (plvl).toString();
var ptp = userGlobal[sender.id].petType;
var ptn = userGlobal[sender.id].petName;
var ilh = 0;
var letra = 454;
if (userGlobal[sender.id].petIlha === "./pets/ilhas8.png") {
	ilh = 139;
        letra = 588;
}
const font = jimp.loadFont(jimp.FONT_SANS_32_WHITE);
const font2 = jimp.loadFont(jimp.FONT_SANS_16_BLACK);
const font3 = jimp.loadFont(jimp.FONT_SANS_16_WHITE);

console.log(ptn + " " + plvl2 + " " + pxpf + " " + ptp + "\n");

jimps[1].composite(jimps[0], userGlobal[sender.id].petPosX, userGlobal[sender.id].petPosY);
jimps[1].print(font, 8, letra, { text: ptn, alignmentX: jimp.HORIZONTAL_ALIGN_CENTER }, 257); // LINE 7727
jimps[1].print(font3, 441, 22, { text: plvl2, alignmentX: jimp.HORIZONTAL_ALIGN_CENTER }, 50);
jimps[1].print(font3, 427, 51, { text: pxpf, alignmentX: jimp.HORIZONTAL_ALIGN_CENTER, alignmentY: jimp.VERTICAL_ALIGN_MIDDLE }, 69, 21);
jimps[1].print(font2, 377, 351+ilh, { text: ptp, alignmentX: jimp.HORIZONTAL_ALIGN_CENTER, alignmentY: jimp.VERTICAL_ALIGN_MIDDLE }, 105, 39+ilh);

PS: all the variables (ptn, plvl2, pxpf, ptp) are property defined, as we can see in the console.log;

The error in the console:
![imagem](https://user-images.githubusercontent.com/44046193/50619899-636d8e00-0ee3-11e9-8d28-1474eb018cfd.png)

**Comment by hipstersmoothie** [comment]
Rewrote all you code to be more es-sexy. The problem you were running into was that `Jimp.loadFont` returns a promise and you were not awaiting.  The font hadn't been resolved yet so you got errors while printing. 

Hope this helps!

```js
const Jimp = require("jimp");

const testPet = {
  petxp: 80,
  ptn: "Some string",
  petbase: "dog",
  petlvl: 20,
  petType: "foo",
  petName: "bar",
  petImg: "./exampleImages/anime.png",
  petIlha: "./exampleImages/dice.png",
  petPosX: 10,
  petPosY: 10
};

async function test({
  petxp,
  ptn,
  petbase,
  petlvl,
  petType,
  petName,
  petImg,
  petIlha,
  petPosX,
  petPosY
}) {
  const imgs = [petImg, petIlha];
  const [petProfile, ilha] = await Promise.all(imgs.map(img => Jimp.read(img)));

  const pxpf = `${petxp.toString()}/${petbase.toString()}`;

  let ilh = 0;
  let letra = 454;

  if (petIlha === "./pets/ilhas8.png") {
    ilh = 139;
    letra = 588;
  }

  const font = await Jimp.loadFont(Jimp.FONT_SANS_32_WHITE);
  const font2 = await Jimp.loadFont(Jimp.FONT_SANS_16_BLACK);
  const font3 = await Jimp.loadFont(Jimp.FONT_SANS_16_WHITE);

  console.log(`${petName} ${petlvl} ${pxpf} ${petType}\n`);

  await ilha
    .composite(petProfile, petPosX, petPosY)
    .print(
      font,
      8,
      letra,
      { text: ptn, alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER },
      257
    )
    .print(
      font3,
      441,
      22,
      { text: petlvl.toString(), alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER },
      50
    )
    .print(
      font3,
      427,
      51,
      {
        text: pxpf,
        alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER,
        alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE
      },
      69,
      21
    )
    .print(
      font2,
      377,
      351 + ilh,
      {
        text: petType,
        alignmentX: Jimp.HORIZONTAL_ALIGN_CENTER,
        alignmentY: Jimp.VERTICAL_ALIGN_MIDDLE
      },
      105,
      39 + ilh
    )
    .writeAsync("test.png");
}

test(testPet);
```
