### ISSUE TITLE
Circular image?

### ISSUE THREAD

**Issue by haydenbleasel** [oliver-moran/jimp#69]
Hello,

I'm wondering whether it's possible to create a circular image in JIMP i.e. creating a 200x200 transparent canvas and create a circle on top of it with a radius of 200px. The aim is to create Firefox OS favicons e.g.

![](http://gleero.com/pictures/firefoxRound.png)

**Comment by oliver-moran** [comment]
This is very easy using masks:

```js
var p1 = Jimp.read("lenna.png");
var p2 = Jimp.read("mask.png");

Promise.all([p1, p2]).then(function(images){
	var lenna = images[0];
	var mask = images[1];
	lenna.mask(mask, 0, 0).write("lenna-circle.png");
});
```

And this is exactly the purpose I wrote Jimp for BTW. Best of luck!

---

![lenna](https://cloud.githubusercontent.com/assets/414918/11165708/fbeb5164-8b0e-11e5-893d-9d0e91cb3d32.png)
![mask](https://cloud.githubusercontent.com/assets/414918/11165709/051d10b0-8b0f-11e5-864a-20ef0bada8d6.png)
![lenna-circle](https://cloud.githubusercontent.com/assets/414918/11165710/092f30ca-8b0f-11e5-8722-60a569ca9b76.png)

**Comment by haydenbleasel** [comment]
Yep that was my fallback solution, problem is when you're programmatically generating images of different sizes, scaling a single size mask won't give the best quality, but no matter.

**Comment by oliver-moran** [comment]
Is it that bad? Try creating just one "high resolution" icon then scaling and saving that:

```js
var p1 = Jimp.read("lenna.png");
var p2 = Jimp.read("mask.png");

Promise.all([p1, p2]).then(function(images){
	var lenna = images[0];
	var mask = images[1];
	
	lenna.mask(mask, 0, 0).write("lenna-circle.png");
	
	var sizes = [256, 128, 64, 60, 48, 32, 30, 16];
	
	for (var i = 0; i < sizes.length; i++) {
		lenna.clone().resize(sizes[i], Jimp.AUTO)
		.write("lenna-circle" + i + ".png");
	}
});
```

**Comment by haydenbleasel** [comment]
It'll definitely work, just saying it won't be absolutely pixel-perfect, but I guess then again neither will the resized image so it's all good :)

**Comment by spsiddarthan** [comment]
@oliver-moran, @haydenbleasel : I was trying to do the exact same thing today. I just wanted to know if I understood the concept of mask correctly. 

If I have an image with dimensions x*x and want to create the circular crop for it, I first have to generate the mask image on the fly. Is that correct?

**Comment by devdemi** [comment]
@oliver-moran is there possibility to make transparent corners? I want to generate circular avatar and composite it with another image but that image has not white background
![b7fc031739](https://user-images.githubusercontent.com/890372/40652501-0b0b9426-6341-11e8-824f-33fcdee8b920.png)
