### ISSUE TITLE
Running in Worker Threads

### ISSUE THREAD

**Issue by davesnotes** [oliver-moran/jimp#693]
# Expected Behavior

Jimp writes out my byte array to disk as an image.

# Current Behavior

It throws an exception when run inside a node worker thread.  It works just fine in the main Node thread.

# Failure Information (for bugs)

TypeError: process.umask is not a function
    at Function.sync (...\index.js:64:34)
    at Jimp.write (...\index.js:645:25)
    at Jimp.read.then.image (...\test.js:18:31)

## Steps to Reproduce

Inside a node worker thread (worker_threads) run this code:

`````
Jimp.read(image_byte_array)
                    .then(image => {
                        // Do stuff with the image.
                        image.write('E:\\Temp\\my_image.jpg', err => console.log(err)) // Line 18
                        // throws exception in worker thread!
                    })
                    .catch(err => {
                        // Handle an exception.
                        console.log(err)
                    });
`````

Note: worker threads are experimental so you must run node thus:

> "start": "node --experimental-worker ./bin/www"

## Context

I'm running a basic Express.JS app with the Jimp code inside a worker thread.

- Jimp Version: ^0.6.0
- Operating System: Windows 10
- Node version: v10.9.0

**Comment by hipstersmoothie** [comment]
Can you put together a simple sample repo?

**Comment by davesnotes** [comment]
Will do

**Comment by davesnotes** [comment]
I just tried to recreate this with a simple node script and it worked just fine.

https://github.com/davesnotes/web-workers

I wonder if the problem only exists when run from a web-worker in express...  I'll create another test repo using Express and update this thread...

**Comment by davesnotes** [comment]
My code wrote to an absolute path which exists but errors.  If I save to a relative path it works.  I don't know why tbh, but the requirement is to save to a DB anyway, saving to the file system was temporary to test the image manipulation code.

Thanks for your time and sorry for any wasted effort.

I'll close this as it doesn't seem to be a problem with Jimp.

Thanks,
Dave
