### ISSUE TITLE
Is an 'auto-crop' feature scheduled?

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#70]
Is an `auto-crop` feature scheduled any point in time?

I mean: some images have one-color borders, which can be sometimes annoying, something that distracts from the real image contents...

I suppose it should not be so difficult, to implement (knowing the inners of jimp... :-): you should check the colors of the most external pixel for each one of the four borders: if they are **all** the same, you should crop that side by one pixel, and continue with the next pixel...

As an edge case, you could finish with an empty image (if the source image was just one color)... That should be fine, of course (auto-cropping one-color image is a quite silly operation in itself... :-).

For example, from:
![amb](https://cloud.githubusercontent.com/assets/849127/11170084/91a66b6a-8bca-11e5-9995-b0c6b2cccf78.png)

to:
![am](https://cloud.githubusercontent.com/assets/849127/11170086/9acc79be-8bca-11e5-8b9b-277301254416.png)

**Comment by gcq** [comment]
jimp is so lowe level and so straightforward to use that a feature like that, so specific, would not add much value and instead add complexity.

You layed out the algorithm, now it's a matter of implementing it :smile:

**Comment by marcolino** [comment]
Yup! I did never read throughtfully jimp docs, now I see there is a `getPixelColor(x, y)` method... So yes, I'll try to implement an autocrop() method myself... Or should I directly use bitmap data, to improve performance?

**Comment by oliver-moran** [comment]
@marcolino, I'm happy to include in an auto-crop method. If you implement it and make a pull request, I'll happily pull it in. Alternatively, if you can write a simple method using the API and post it here, I'll add it to the code base.

**Comment by marcolino** [comment]
Hi!
I'm trying to `git push origin autocrop-branch`, to easily create a PR, but am I supposed to know repository authentication, to push a branch?

**Comment by oliver-moran** [comment]
1. Create a fork by clicking the link in the top right here: https://github.com/oliver-moran/jimp
2. Check that out, make your modifications and commit your changes to the fork.
3. Then go here and create a new pull request: https://github.com/oliver-moran/jimp/pulls

**Comment by marcolino** [comment]
Yes... I forgot to *fork*, but did clone directly from your repo... :-(
Sorry, it's a *long* time from my last PR... :-)
Please let me now what you think about the autocrop feature...

**Comment by oliver-moran** [comment]
Merged the pull request here: https://github.com/oliver-moran/jimp/pull/71

Thanks!

**Comment by marcolino** [comment]
Sorry, last question: I have already some minor changes to autocrop... Should I create a new PR, or what?

**Comment by oliver-moran** [comment]
Sure thing, just create a new pull request from the fork you have.
