### ISSUE TITLE
Error: Cannot find module 'jimp'

### ISSUE THREAD

**Issue by dex-labs** [oliver-moran/jimp#726]
# Expected Behavior

var Jimp = require('jimp'); to load the requested modules.

Checked the node_modules folder and it only has the browser and fonts folders.
Dist folder seems to be missing.

No errors when running npm install.

Using in node env not browser.

# Current Behavior

Error: Cannot find module 'jimp'

# Failure Information (for bugs)

## Steps to Reproduce

npm i --save jimp

var Jimp = require('jimp');

**Screenshots**

https://i.ibb.co/dbr79sM/Screenshot-042819-031817-AM.jpg
https://i.ibb.co/wsyfVXs/Screenshot-042819-031913-AM.jpg

## Context

- Jimp Version: 0.6.1 & 0.6.2
- Operating System: Windows
- Node version: 10.15.1

**Comment by dpgraham** [comment]
Same here....

I think the `dist/` folder wasn't published.

When I tried installing with Node 12 the message was:

```
Cannot find module '/Users/danielgraham/appium/node_modules/jimp/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

`dist/` wasn't there only `browser/`.

**Comment by dpgraham** [comment]
I'd recommend unpubishing 0.6.2 and then republishing 0.6.3 as the latest once the problem has been figured out.

**Comment by hipstersmoothie** [comment]
@dex-labs @dpgraham how does 0.6.3 look?

**Comment by Thermofish** [comment]
Now I am receiving:

Error: Cannot find module '@jimp/types'

**Comment by hipstersmoothie** [comment]
Okay I synced all the package versions and changed lerna to force publish all of them. 0.6.4 should work 🙏

**Comment by dpgraham** [comment]
0.6.3 worked for me

**Comment by Thermofish** [comment]
0.6.4 worked for me.  The 0.6.3 publish was giving "Error: Cannot find module '@jimp/types'" for me.

**Comment by hipstersmoothie** [comment]
sweet. sorry for the fuss!

**Comment by dpgraham** [comment]
Everything's good now! Thanks for the quick response.

**Comment by dex-labs** [comment]
All is good in the world once again
