### ISSUE TITLE
Littera seems to not be working

### ISSUE THREAD

**Issue by mrkent** [oliver-moran/jimp#729]
http://kvazars.com/littera/ opens to a page that simply says to get flash player (which I should have) on chrome and safari.

What's the easiest way to convert a ttf to bmfont?

**Comment by jasonhargrove** [comment]
To test I tried https://convertio.co/

**Comment by jasonhargrove** [comment]
docs provide this https://github.com/libgdx/libgdx/wiki/Hiero
