### ISSUE TITLE
Issue with some images.

### ISSUE THREAD

**Issue by canvas-manik** [oliver-moran/jimp#73]
Hi Oliver,

I am seeing some issues with some of the images, where it is not able to generate the image. I am using the following code:

```js
Jimp.read(srcImgLocation, function (err, image) {
    var imgCloneMedium = image.clone();
    var promises=[];
    promises.push(imgCloneMedium.resize(Jimp.AUTO,400).quality(80).write(mediumImgLocation));
    Promise.all(promises).then(function(err,img){
        // Here I should get the image saved on mediumImgLocation, which for this image, i am not getting. It does not shrow any exception as well
    }
}
```

Attaching image which is failing.
![kanvzhelp-vyykavuq](https://cloud.githubusercontent.com/assets/11735090/11342262/77872716-922c-11e5-888f-521938e9bc77.PNG)

**Comment by oliver-moran** [comment]
@canvas-manik, that's not how promises work. See here: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

Your code should work like this:

```js
Jimp.read(srcImgLocation, function (err, image) {
    var imgCloneMedium = image.clone();
    imgCloneMedium.resize(Jimp.AUTO,400).quality(80).write(mediumImgLocation);
});
```

**Comment by canvas-manik** [comment]
Thanks Oliver. Yeah it worked.
