### ISSUE TITLE
Wrong argument check in Image.color

### ISSUE THREAD

**Issue by anpep** [oliver-moran/jimp#74]
https://github.com/oliver-moran/jimp/blob/master/index.js#L1704

The current implementation checks the arguments to the `Image.color` this way:

```javascript
if (!actions | actions.constructor !== Array)
  return throwError.call(this, "actions must be an array", cb);
```

However, he `||` operator is mistyped and the `Array` type-checking is wrong too.
I would rather do something like:

```javascript
if (!actions || !Array.isArray(actions))
  return throwError.call(this, "actions must be an array", cb);
```

Otherwise it always throws an exception.

**Comment by oliver-moran** [comment]
Thanks, I've made this change and will release to NPM shortly.
