### ISSUE TITLE
Browserified version

### ISSUE THREAD

**Issue by strandedcity** [oliver-moran/jimp#75]
Hi There!

Jimp is terrific. Thanks so much for all the work you've put into it! I've prototyped an addition to the project I thought might be of interest. Some background:

A project I'm working on requires a series of thumbnails of different sizes for each image uploaded by a user. Doing this server-side (which is the typical solution used by most) requires substantial investment in server infrastructure to handle the load with reasonable response times, but doing the same work using `<canvas>` blocks the UI thread in a way that interrupts user's work. This is a very common use case that generates a lot of load around the internet.

Using Jimp + Browserify, I've successfully prototyped a client-side image thumbnailer that runs as a web worker. It turns out that performance is terrific, and the workload of thumbnailing can be successfully distributed to clients. The minified + gzipped file is 300kb, reasonable enough for an application that is by definition graphics-heavy anyways.
- My fork with the quick-and-dirty prototype: https://github.com/strandedcity/jimp
- Demonstration of the web-worker in action: http://strandedcity.github.io/jimp/browser/

(just select any jpg or png image and wait a few seconds, a thumbnail will appear)

Currently, I've hacked together a rather inflexible prototype that involves deleting code to remove dependencies... not good pull request material.

My question is this: if I were to rework my changes so that they are non-destructive to the original project, would you be interested in seeing a pull request for a web-worker version of jimp to be included in the main repo? Seems like something many others would be interested in.

Thanks again for the awesome project!

**Comment by oliver-moran** [comment]
Sounds smashing.

I couldn't get your demo page to work (`Uncaught TypeError: Cannot read property 'width' of undefined`) but I get the idea. And it sounds great.

If you code it, I will pull.

**Comment by strandedcity** [comment]
Cool, will do! I'll watch browser compatibility as well :+1:

**Comment by strandedcity** [comment]
Here we go: https://github.com/oliver-moran/jimp/pull/79

**Comment by oliver-moran** [comment]
Thanks, I've replied on the pull request thread.

**Comment by oliver-moran** [comment]
OK. I pulled it and broke it.

I made one change: https://github.com/oliver-moran/jimp/commit/d2e9582e71e98b395ed308a088f880922f3f0b42#diff-168726dbe96b3ce427e7fedce31bb0bc

I don't think that should have broken it but when I did a `npm install` afterwards the browser example stopped working. Any ideas?

**Comment by strandedcity** [comment]
I saw this at one point also. I think it's because uglifyjs will remove this:

```
if (true == false) { /* Code will be stripped entirely */ }
```

but it does not actually evaluate the code (it just makes a syntax tree), so this:

```
var test = true == false;
if (test) { /* Code will remain! */ }
```

is not removed (I think). The uglified code will never execute, but it will be present in the output file.

In this case, if the line is not stripped out entirely before browserify hits it, browserify will attempt to include a whole lot of extra stuff to read and write files to the filesystem. That code doesn't work in web browsers as-is, and makes the file huge.

If you find a way around this I'm all ears. But I tried the same thing you tried, no go.

**Comment by oliver-moran** [comment]
OK. Good to know I didn't do something stupid anyway. I'll fix it tonight.

**Comment by oliver-moran** [comment]
No joy. I reverted my changes to `index.js` and ran `npm install` but the browser build still didn't work.

On Firefox I get:
```
Could not process 96fm.png: Line 1 in [...]/jimp/browser/jimp-worker.js: : NS_ERROR_FAILURE:
```

And on Chrome:
```
Uncaught SecurityError: Failed to construct 'Worker': Script at '[...]/jimp/browser/jimp-worker.js' cannot be accessed from origin 'null'.
```

**Comment by oliver-moran** [comment]
No joy. I reverted my changes to `index.js` and ran `npm install` but the browser build still didn't work.

On Firefox I get:
```
Could not process image.png: Line 1 in [...]/jimp/browser/jimp-worker.js: : NS_ERROR_FAILURE:
```

And on Chrome:
```
Uncaught SecurityError: Failed to construct 'Worker': Script at '[...]/jimp/browser/jimp-worker.js' cannot be accessed from origin 'null'.
```

**Comment by strandedcity** [comment]
Oh, are you using the "file" protocol to load the example page (ie, your url in the browser bar starts ```file://```)? Those look like security errors that would go away if you ran the page on a webserver (either by pushing to a gh-pages branch, or by running apache locally).

http://stackoverflow.com/questions/21408510/chrome-cant-load-web-worker

**Comment by oliver-moran** [comment]
OK. Back looking at this. Still no joy. Running over HTTP now but seeing: `Uncaught ReferenceError: window is not defined` on line 29 of `jimp.min.js`.

**Comment by instructaPhil** [comment]
Looks to me like something substantial changed somewhere in the dependencies. I checked out my own "browserification" branch (the one you merged). The code works well. I rebuilt the browser libraries from there with no changes, but the built libraries break. I see a slightly different error, but the same effect. For me, it's ```jimp.min.js:30 Uncaught ReferenceError: encode is not defined```

On the branch you merged, jimp.js is 621kb uncompressed. When I rebuild now, I get 960kb. I'll try to take a look at what might have happened in the mean time (the dependencies are shifting under us), but time is now short for me in real life. In any case, you can definitely stop beating your head against the build process. I think something outside our control changed.

**Comment by strandedcity** [comment]
Are you using a mac?

I did this work originally on Linux, then had trouble building more recently on a mac. Turns out the mac build never worked because of syntax differences between sed BSD and GNU flavors. This fixes those issues: https://github.com/oliver-moran/jimp/pull/123

I am now building successfully on both Linux Mint 17.3 and OSX 10.9.5. I'm using node 4.5 and 5.x incidentally, in case that matters too.

There are no dependency problems; I'm testing with completely fresh clones of the repo. Also, there are no problems with anything you've checked in. That pull request is based on your current master.

The specific error you saw was different from the one I saw, but this may push things forward. Let me know if that works for you?

**Comment by oliver-moran** [comment]
Still no joy. This time `window is not defined`.

**Comment by strandedcity** [comment]
Looks like you have a different issue than I have seen. It may help to list full steps to reproduce (ie, starting from a fresh clone of the repo), but for some additional debugging information can you replace line 1 of jimp-worker.js with

```
importScripts("lib/jimp.js");
```

so that we can see which line causes the error in the unminified file?

#### Also, to confirm:
- You see this error in all browsers?
- You do *not* see this error when using the demo at http://strandedcity.github.io/jimp/browser/ ?

#### For the record, I'm doing this:
- Using MacBook Pro, OSX 10.9.5, node v4.4.3, npm v2.15.1
- Navigate in terminal to a web-accessible directory (on some systems, ```~/Sites/```)
- ```git clone git@github.com:oliver-moran/jimp.git jimp-testbuild```
- ```cd jimp-testbuild```
- ```npm install```
- ```npm run-script prepublish``` (if you don't see the browserify output when you install)
- In a browser, visit http://localhost/path/to/jimp/browser/
- Click "load some images via xhr for the demo."

Expected behavior: Thumbnails are displayed
Actual behavior: ?

#### One other thought:
- The build script calls uglifyjs on the command line. I believe npm handles that, but if not it may help to replace line 25 of browserify-build.sh with:

```
$PWD/../node_modules/uglify-js/bin/uglifyjs tmp.jimp.js --compress warnings=false --mangle -o tmp.jimp.min.js
```

Happy to make a PR with that guess if it's helpful.

Then you'll want to: ```npm run-script prepublish``` again.

Sorry this is so much work to get started. We're close, I'm sure of it!

**Comment by oliver-moran** [comment]
Success. Replacing line 25 of the build script did it. Maybe there's more elegant way to do it this get us back on the road.

**Comment by oliver-moran** [comment]
Good news. Nearly five months later: it's live! Thanks so much for this.

**Comment by strandedcity** [comment]
So glad we could get to the bottom of things. Jimp is an awesome library, thanks so much for your patience getting things running everywhere! I'll take a look at a more elegant solution for that line of the build script. There must be a better way.

**Comment by oliver-moran** [comment]
Ugh. I had to make an emergency release because of a broken dependency. And guess what? The browserify functionality broke.

I swear, I didn't even touch it!

**Comment by strandedcity** [comment]
Browserify also doesn't like node-zlib-backport:

https://github.com/lukeapage/pngjs/commit/b914ab4d80add0844cfaec663a9f4f7cbaaca860

I'll see if I can figure a way around that shortly.... it's a pretty legit breakage though. That package broke a lot of stuff that depends on pngjs, including jimp (https://github.com/oliver-moran/jimp/issues/129)

**Comment by lukeapage** [comment]
@strandedcity we rolled back the dependency, though there is still a require, used if you try a sync function and have a zlib without sync. Does this still cause an issue for browserify or are you able to work-around that? if browserify tries to get it, you can just configure browserify to null out the result of that require. Anyway, raise an issue on pngjs if you require assistance getting it to work in the browser, I've long thought of switching to panko for zipping to avoid these issues.

**Comment by strandedcity** [comment]
Thanks @lukeapage ! Looks like I had a version of pngjs from the middle, when the dependency was required. Your fix worked great once I upgraded again.

However there's another break to the browser build here, caused by other new libraries assuming that "window" is defined. I realized it's not defined in the demo actually, since the demo uses a web worker with a global variable ```self```. 

Fixed: https://github.com/oliver-moran/jimp/pull/131

@oliver-moran it seems like dependency changes are an issue for the browserify build. Not many folks test their libraries against node, browserify, chrome, ie9, and web workers all at the same time. Would you prefer that I maintain this functionality in a separate fork instead? I like the extra motivation that comes from an "it's broken!" note, but I'm sure that's very frustrating for you. Either way; I believe in the functionality and will continue to maintain it.

**Comment by strandedcity** [comment]
For the ```window``` problem, see https://github.com/thlorenz/exposify/pull/3

**Comment by strandedcity** [comment]
https://github.com/oliver-moran/jimp/pull/133 will let us ignore the zlib-backport issue, which shouldn't matter in the browser use anyways so far as I can tell.

**Comment by oliver-moran** [comment]
Looks like we're back on track. All seems to be working again.

**Comment by lukeapage** [comment]
I released a new major version without 0.10 support...

**Comment by oliver-moran** [comment]
@strandedcity - Broken again. Doesn't build correctly. Says Buffer is missing. Would you mind taking a look at it?

**Comment by strandedcity** [comment]
Dang! I'm afraid I can't reproduce.... following your steps, and testing at current head (#2575c9a57bba030ec95190b5171ddd34842c32a1), your steps to reproduce work fine for me. In confirmed that the size of jimp.min.js changed in the browser network panel after running the build script, to make sure I didn't have a cached copy. No notes in console, except the mime type in the example.

I'm using a completely clean repo (starting with "git clone" just now) and:
node 5.1.0
npm 3.3.2
OSX 10.11.6

Any major differences for your setup?

**Comment by strandedcity** [comment]
Any local changes to the test files by chance? That's a condition at the top of jimp-wrapper.js that's there to catch basically a fatal error in the loading order of stuff on the page:

```
if (!self.Buffer && !window.Buffer){
    throw new Error("Node's Buffer() not available");
}
```

Would be a strange build problem, I think.
