### ISSUE TITLE
How to catch write errors?

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#76]
I'm trying to catch all possible errors in my Jimp-powered app.
I am testing the first Jimp example, simplified (here with function, but nothing changes with Promises...):

    var Jimp = require("jimp");

    // open a file called "lenna.png"
    Jimp.read("lenna.png", function (err, lenna) {
        if (err) {
          console.log('read error:', err);
          throw err;
        }
        lenna.write("/NONEXISTENT/lena.jpg"), function(err) {
          // would like to handle error, but I never get here...
          console.log('in write callback!);
          if (err) {
            console.log('write error:', err);
            throw err; // or something else...
          }
        })
    });

The issue I face is that I am able to catch read errors, but not write errors: in the code above, trying to write to a nonexistent directory, I am thrown an error, and my little write-error handling function is never called... :-)

All I get in console is:

    events.js:141
      throw er; // Unhandled 'error' event
      ^

    Error: ENOENT: no such file or directory, open '/NONEXISTENT/lena.jpg'
    at Error (native)

What do I miss?

**Comment by oliver-moran** [comment]
@marcolino, as luck would have it, a patch was emailed to me to fix this error. See here:

https://github.com/oliver-moran/jimp/commit/948fb5ef6166255e9e25cd6c63d15c8eb407badd

I'll release this this evening.

**Comment by marcolino** [comment]
Great!
