### ISSUE TITLE
Can Jimp return a manipulated external image URL?

### ISSUE THREAD

**Issue by clarke94** [oliver-moran/jimp#779]
Can Jimp return a manipulated image from an external URL?

for example:

```js
return Jimp.read( 'https://some-domain.com/image.png' )
                    .then( image => image.cover( 300, 300 ) )
                    .catch( err => console.error( err ) );
```

Would that return the image from `http://some-domain.com/image.png` at a size of 300x300, or does it not work like that?

**Comment by FridayJew** [comment]
you can try it or just asking? Some images from internet have this problem https://github.com/oliver-moran/jimp/issues/775 . You can't read everyone image. This is sad...
