### ISSUE TITLE
TypeScript import won't work

### ISSUE THREAD

**Issue by cancerberoSgx** [oliver-moran/jimp#785]
None of the three methods detailed in the readme worked for me when importing gimp on my TypeScript project when upgrading to jimp@0.8.0

I couldn't even access the right type so at least I can force a cast to require('gimp'). The error I'm seeing in the suggested methods is that the type resolved to never. 

I'm using typeScript 3.6.2 , and node 12.8.1. I also tried with all combinations of `esModuleInterop` and `allowSyntheticDefaultImports` as the readme mention but without luck. I feel competent with TypeScript and I really think you have something wrong with your type declarations. It would be awesome if you could just export the constructor type - in my case I need to cast the Jimp class, as in `new Jimp()`. Also, just an opinion, these type declarations are unnecessary complex I think. Any tip is most welcome, thanks. This is my tsconfig.json 

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["esnext", "dom"], 
    "strict": true, 
    "esModuleInterop": true,
    // "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "outDir": "./dist", 
    "rootDir": ".",
    "declaration": true
  },
  "include": ["src", "test"]
}

```

**Comment by hipstersmoothie** [comment]
@crutchcorn

**Comment by hipstersmoothie** [comment]
Seriously considering moving the definition to definitely typed. There have been countless issues around managing the types in this project. 

I love typescript but I'm starting to believe that if a library isn't shipped in TS it shouldn't try to ship .d.ts files too.

**Comment by hipstersmoothie** [comment]
If we do keep theme we definitely need some type testing @crutchcorn

**Comment by crutchcorn** [comment]
Blech, I tried to test myself but musta dropped the ball somewhere - okay. I'll see if I can write some tests tomorrow and get a PR to fix this 

I totally get if we want to move the types to their own repo. I'm willing to maintain these types for this repo, and I feel that when typings are moved out of a project they're maintained to a lesser degree and they suffer as a result, but that's my initial thoughts 

@cancerberoSgx, regarding the type complexity - I agree that they're just complex but they're forced to be so if the plugin system is able to be properly and strictly typed. While it's unfortunate that such complex typings are required, I sincerely did my very best to document things as I could and make the typings as verbose and clear as possible (I'd love feedback on how they might be made more straightforward without removing the plugin functionality - it's within huge possibilities I missed something obvious)

**Comment by crutchcorn** [comment]
Working on it more today and I _think_ I have it fixed 

That said, I am writing dts-lint tests (the same in DefinitelyTyped) to try to ensure to the best of my abilities it will work

**Comment by hipstersmoothie** [comment]
I think that should help with future PRs for types too. Thanks for your work! It's my fault for the plugin system 😅 If any fingers should be pointed for needless complexity it's at me lol.

**Comment by crutchcorn** [comment]
For sure. Huge apologies for introducing a PR without doing more thorough testing (it turns out my IDE was doing some weird things to fix the mistaken type errors and I just assumed it worked) - I'm trying to prioritize getting a fix out today for it since the version was deployed 

I think the plugin system is great - it's never easy to introduce one and it seems to work really well

**Comment by crutchcorn** [comment]
Issue has been resolved in PR #786 and typing tests were added to confirm functionality. Again, huge apologies

**Comment by aethys256** [comment]
I spent 1 hour trying to figure why the hell I was not able to type at all my generic mixins until I found this issue.
Reverted to 0.7.0 until a fix is out, 3rd party typing is not easy indeed, maybe considering a TS rewrite in the future for proper support.
Thanks anyway for the work 👍

**Comment by cancerberoSgx** [comment]
@crutchcorn Aja, I'm not experienced with jimp plugins, but in other projects what they do is pass the responsibility declaring plugin types to plugin authors. If you delegate this to community definetely typed then they will have the same problem. This is what project jest does for example (my idea BTW ) : https://jestjs.io/docs/en/expect#expectextendmatchers

Basically If a plugin adds a new member to an existing interface or adds new types or modifications to existing types thet are responsible of declaring those modifications / new signatures by themself. 

Jimp project just need to be sure to expose the types that are susceptible of being modifiable by plugin authors. 

If you need a hand with this I will be glad to help, but need your confirmation so I start familiarizing with your plugin's API and so on. 

I strongly advice that, if you are interesting in supporting  TypeScript definitions maintaining them here will add value and quality  to this project for sure!- -will you let me know if you need a hand with it ? 

THanks

**Comment by crutchcorn** [comment]
@cancerberoSgx It's not quite that easy. The plugin authors in this case is us:

https://github.com/oliver-moran/jimp/tree/master/packages/plugins

The other issue is that we're enabling composing of these packages via function ala:

https://github.com/oliver-moran/jimp/tree/master/packages/custom

Using interface merging as you're suggesting (and as jest uses) only extends the initial type without doing any strictness testing to see if the `configure` function actually has those values or not (no better than the original 0.7 typings in that manor)

This PR should have the typings fixed https://github.com/oliver-moran/jimp/pull/786 and introduces type testing. If you're wanting to contribute to these typings, a code review of them would be phenominal (I'd love if we're able to maintain the type scrictness for `@jimp/custom` as well)

**Comment by cancerberoSgx** [comment]
@cancerberoSgx

> The other issue is that we're enabling composing of these packages via function ala:

Ajá, again, totally new with these APIs, and I assume you cannot solve the problem with mixings or modifying ambient modules. I will try to take a look to your code, but just in case (and this is personal opinion) in these cases I always have a small TS project between my test assets as part of my CI just to make sure the compilation doesn't fail (check the readme example works). Is not important to reflect there that plugins typings works, but just that the simple TS example in the readme don't fail. 

Also another feedback - don't describe three different import methods in the readme - it's too verbose. In general you just want to describe the import statement both JavaScript and TypeScript users will use. TypeScript users knows how to configure their project to make it work - and in general when developing in the web they always use `esModuleInterop` - and remember they probably run the same generated JS both in node and browsers.. 

Last feedback: avoid default exports or assignment exports to the user - so they just can `import {Jimp, create, etc} from 'jimp` and JS users an analogous syntax `const {Jimp, create} = require('gimp')` .... course this is pretty personal taste.... Thanks , I  will be alert for the PR and new npm version with this fix. And just an advice: if they got in your way, you are not  forced to use namespaces or modules at all. 

Thanks again! Keep it up

**Comment by crutchcorn** [comment]
Said PR introduces fairly complete typing tests (that tests against 2.8 all the way to 3.6 using [`dtslint`](https://github.com/microsoft/dtslint), the official tool used by Microsoft itself to test types) to hopefully reduce the type's breakage in the future. 

We're also shipping a version of the typings for 2.8 seperate from the ones for 3.1+ (as those are built on top of the plugin system and require some functionality that older versions of TS dont have).

As for the documentation of various import methods - I think that's a seperate set of concerns. I don't know if that's related to the work being done on typings here

Also, regarding default exports - this is a two-fold problem:

1) I can't in many instances due to the acutal IO of the module having a default export. To not default export in these instances is problematic as then the types dont reflect the package typing properly

2) I am trying to do so in many of the places. EG, `Jimp` is an exported named class from `@core/jimp` as well as having a default export of an instance of that class

**Comment by hipstersmoothie** [comment]
@cancerberoSgx Could you verify that v0.8.1 fixes you issue?

**Comment by jerry-sky** [comment]
When trying to build my app I get these errors all over the place using `0.8.1` or `0.8.2-canary.792.290.0`:

![image](https://user-images.githubusercontent.com/4989529/64877052-dd4c3e80-d650-11e9-88c0-ddfd82fa2455.png)

None of that can be seen on version 0.6.8 though.

**Comment by amirburbea** [comment]
Sorry to say that 0.8.2 is also no bueno.  It says can not find types for @jimp/core

**Comment by crutchcorn** [comment]
Alright y'all. I know I've been gone for a while now, but I have a new version for everyone to test. This includes typing tests for things like:

```typescript
import Jimp from 'jimp'

const jimpInst: Jimp = new Jimp()
```

And more. Please be patient and understand if this version does not work (I am still putting a fair amount of time into this outside of my full-time job), but I'd love some feedback on:
`0.8.2-canary.792.353.0`

### Please Read
Now, I do want to make a note:
** `const Jimp = require('jimp')` and `import * from Jimp from 'jimp'; new Jimp()` DO NOT WORK**

Both of these import methods were broken as-of 0.6.4 (hense why that was the last version that worked for you, ), and unless we remove all other named exports, there is nothing that can be done there.

The good news is: This should not impact the ability for your code to run.

When looking at the built version of the code, you can clearly see:
```javascript
var _default = (0, _custom.default)({
  types: [_types.default],
  plugins: [_plugins.default]
});

exports.default = _default;
module.exports = exports.default;
```		


That is to say (for those of us who don't speak ES6 Babel nonesense): The export is duplicated to have both ES6 and commonJS exports. It will work regardless of how you import it in TS (but the typings, I will remind, will not).

This is all a long TLDR that's to say: Before you test this version - please make sure to change all of your imports to use the default `import Jimp from 'jimp'` syntax

**Comment by crutchcorn** [comment]
FWIW, the canary release I tested works for our use-case in `node-vibrant`:

https://github.com/akfish/node-vibrant/blob/develop/packages/vibrant-image-node/src/index.ts#L8

As well as the suggested change to add in `custom` (that sparked this whole typing frenzy):

https://github.com/akfish/node-vibrant/issues/96#issuecomment-515717736

**Comment by patheticcockroach** [comment]
It's working quite better, I only have a couple of errors left.

The first relevant parts of code look like this:
```typescript
import Jimp from 'jimp';
let finalImage: Jimp = new Jimp(width, height, 0x00000000);
return finalImage.resize(newWidth, newHeight);
```
and I get this error:
```
 error TS2322: Type 'import("[...]/node_modules/@jimp/core/types/jimp").Jimp' is not assignable to type 'import("[...]/node_modules/jimp/types/ts3.1/index").default'.
  Type 'Jimp' is missing the following properties from type 'Bmp': constants, mime, decoders, encoders

xx     return finalImage.resize(newWidth, newHeight);
```

The second one looks like:
```typescript
import Jimp from 'jimp';
this.baseImage = await Jimp.read('filename');
this.finalImage = this.baseImage.clone()
    .resize(1, 1)
    .setPixelColor(0x00000000, 0, 0)
    .resize(width, height);
```
and I get this error:
```
error TS2339: Property 'resize' does not exist on type 'Jimp'.

XX       .resize(width, height);
```

No other errors, so this is clearly going in the right direction 👍

**Comment by amirburbea** [comment]
@patheticcockroach  I am seeing the `resize` method has disappeared like you.

However I don't get this error you have
`error TS2322: Type 'import("[...]/node_modules/@jimp/core/types/jimp").Jimp' is not assignable to type 'import("[...]/node_modules/jimp/types/ts3.1/index").default'`

That again sounds like `allowSyntheticDefaultImports` is not set to `true`.  I wonder if you might try removing the explicit assignment (Instead of `let finalImage: Jimp = new Jimp(width, height, 0x00000000);` try simply `let finalImage = new Jimp(width, height, 0x00000000);`)

**Comment by amirburbea** [comment]
@patheticcockroach - a temporary workaround to the resize method could simply be module augmentation.

```ts
declare module '@jimp/core'{
  class Jimp {
    resize(x:number,y:number):this;
  }
}

import Jimp from 'jimp';

function doSomething() {
   const output = new Jimp(450, 250, '#2b384b').resize(10, 10).opaque()
...
```

**Comment by patheticcockroach** [comment]
allowSyntheticDefaultImports was already set to true, and removing the explicit assignment didn't change things. However, adding this:
```typescript
declare module '@jimp/core'{
  class Jimp {
    public resize(x: number, y: number): this;
  }
}
```
as you suggested, fixed both errors

**Comment by crutchcorn** [comment]
I am able to recreate the issue described by @patheticcockroach. It seems the `this` keyword is not behaving as I'd expect. Let me see if I can fix it.

**Comment by patheticcockroach** [comment]
The resize method definition simply seems to have been omitted in `@jimp/core/types/jimp.d.ts` ;)

**Comment by crutchcorn** [comment]
The resize method shouldn't be on `@jimp/core`. It should be in `@jimp/plugins-resize`. The reason these typings are so difficult and complex is because we're trying to get TS typings for 3.1+ to follow the plugin system in a type strict manor. The issue comes from this line:

https://github.com/oliver-moran/jimp/blob/f5db61068f71f7ceef563bbd08ab0d8f78f82454/packages/core/types/jimp.d.ts#L114

Where `this` is returning `@jimp/core` `Jimp` instance as opposed to the intersected value with all of the plugins:

https://github.com/oliver-moran/jimp/blob/f5db61068f71f7ceef563bbd08ab0d8f78f82454/packages/jimp/types/ts3.1/index.d.ts#L27

**Comment by crutchcorn** [comment]
@cancerberoSgx I'm wondering if we're wanting to move forward with the PR in #792, close this ticket, then make a new ticket for the concern with `clone` that @patheticcockroach mentioned. At least then MOST `jimp` usages should work, and we can start tracking those issues a bit better (and with a smaller scope). What do you think? I'm still trying to figure out the right way to solve against the `this` issue

**Comment by crutchcorn** [comment]
Actually, @patheticcockroach can you test this one last time against `0.8.2-canary.792.360.0`

If this commit works, the typings WILL fully work, but will not utilize the new plugin system. `@jimp/custom` will still have the issues with `clone`, but my thought is, with this new release we can fix `jimp`, then merge that commit, create a new release, close this issue, then create a new issue for the new typings and custom, then fix those immediately after (so long as we have a working `jimp` typings)

**Comment by patheticcockroach** [comment]
> Actually, @patheticcockroach can you test this one last time against 0.8.2-canary.792.360.0

It works! :)

**Comment by crutchcorn** [comment]
@patheticcockroach when you get a chance, it'd be great if you can test against #798 (with the same import restrictions of 0.8.3 [which was the last version you said worked - it got published]). If that works, then the 3.1 TS migration should be complete. I am so sorry this was such a frustrating lengthy process. The type tests put in place should DRASTICALLY reduce the potential for this type of thing to happen again

**Comment by crutchcorn** [comment]
This issue should be solved as-of 0.8.4. I'd love to see it closed.

Please keep in mind that, per the updated README, `import * from Jimp` and `const Jimp = require('jimp')` will not work as-expected. Please update to using `import Jimp from 'jimp'`

**Comment by wwarby** [comment]
This doesn't seem to be fixed as far as I can see.

`const Jimp = require('jimp');` works fine, but if I use `import Jimp from 'jimp';` I see

`Cannot read property 'read' of undefined`

the first time I try to use Jimp:

`const image = (await Jimp.read(buffer));`

I'm using version 0.8.4.

**Comment by amirburbea** [comment]
If you need to use that old = require syntax, you don't have
esModuleInterop/allowSyntheticDefaultImports both on.

**Comment by wwarby** [comment]
Urgh. You're right. But when I turn both those on, about 10 other imports in my project break. `import * as moment from 'moment';` for example no longer compiles, and changing that to `import moment from 'moment';` doesn't help. I'll stick with the old syntax for now - at least everything was working that way - cheers.

**Comment by cancerberoSgx** [comment]
@crutchcorn New version is working OK for me but I leave in your hands closing  this issue. BTW I don't need to add any special configuration in tsconfig.json . THanks!

**Comment by crutchcorn** [comment]
@cancerberoSgx I am unable to close this. I'd love if you would be able to
