### ISSUE TITLE
0.8.1 type errors

### ISSUE THREAD

**Issue by simllll** [oliver-moran/jimp#793]
In the latest 0.8.1 release I guess the type folder is missing,
the current version does not work on my side and I see an entry in the package json:
"types": "types/index.d.ts",

that points to types/index.d.ts..but there is no types folder. 
You probably need to add "types" to "files": [..] inside package.json to add this files for publishing.

Thanks
Simon

**Comment by hipstersmoothie** [comment]
:rocket: Issue was released in v0.8.2 :rocket:

**Comment by simllll** [comment]
This was quick, thanks. I can confirm it works now!
