### ISSUE TITLE
Is it possible to get the output image buffer to save it in database instead of write it in file.

### ISSUE THREAD

**Issue by beny78** [oliver-moran/jimp#8]

**Comment by oliver-moran** [comment]
You can do this already with the bitmap data:

    var image = new Jimp( ...);
    image.bitmap; // this is a image buffer (bitmap data)
    image.width; // this is the width of the image
    image.height; // this is the height of the image

That's pretty huge however. I'll add a write-to-buffer method now.

**Comment by oliver-moran** [comment]
Added this in the latest version.

**Comment by beny78** [comment]
Thanks for your work.

It will be nice to have a jpg or png image buffer.

I have an other suggestion.
Instead of return this in each method, you should implement the Node.js
callback pattern "function(err, result)"
In this case it will be easy to use promise and have async task.

ex:
var jimb = new Jimb(buffer, "image/png");
return Q.nfcall(jimb.resize, 200, 200).then(function(image){
    return Q.nfcall(jimb,toBuffer, image,
"image/png").then(function(buffer){
        //And do what you want
    });
});


2015-01-18 22:27 GMT+01:00 Oliver Moran <notifications@github.com>:

**Comment by oliver-moran** [comment]
Sounds good for a version 0.2. Will you open another ticket for it and I'll get around to it shortly?
