### ISSUE TITLE
Generate a box-shadow

### ISSUE THREAD

**Issue by BenoitClaveau** [oliver-moran/jimp#80]
I use blit function to insert an image into a background image.
I'll love to create shadow effect around my smaller image.

How can I do that ?

**Comment by oliver-moran** [comment]
You could clone the image, turn all it's pixels black, up the opacity a little, and slightly enlarge it. This creates a "shadow". Then blit the "shadow" onto the background and the image on top of that.

I'll be very busy for the next month and a half but I might make a function out of this. Or if you have it cracked by then you can submit it as a pull request.
