### ISSUE TITLE
Write slooowness

### ISSUE THREAD

**Issue by marcolino** [oliver-moran/jimp#81]
I am sorry I am posting an issue without having tested it more thoroughly, it's more a sensation then a certainty... :-(

The sensation is that Jimp.write is too slow: on my notebook it tooks ~0.7 seconds (almost one second) to write a 69381 bytes long image to file system (disk is SSD).

A copy of the image is **much** faster:

    $ time cp image.jpg copy.jpg 
    real	0m0.006s
    user	0m0.000s
    sys	0m0.000s

Of course a system copy has an easier job then Jimp.write(), but the difference is nonetheless huge (it's more than 100 times...). But even a `convert` (a system command, which has to be loaded, run, read the source and close, in addition to write, compared to Jimp.write...:

    time convert image.jpg converted.jpg
    real	0m0.077s
    user	0m0.036s
    sys	0m0.020s

(on a 244Kb image, 6 times bigger than the image written by Jimp) is 9~10 times faster than Jimp...

The duration of Jimp.write was measured with process.hrtime(), this way (read time is excluded):

    var timeStart = process.hrtime();
    image.write(destination, function(err) {
      console.log('image saved in', process.hrtime(timeStart)[0] + '.' + process.hrtime(timeStart)[1], 'seconds');
    });

I simply ask if any similar issue was already reported, and/or if these timings are to be expected...

If you think it's worth, I will set up some more 'scientific' profiling...

**Comment by oliver-moran** [comment]
Sorry for being slow getting back to you. I'll be mega busy IRL for the next month and a half.

Did you have any more insight into this?

The most obvious cause is that Jimp has to encode the JPEG from pixel data before it has anything to write. In memory, Jimp uses a bit array of pixels. But before it can write it has to convert these to a JPEG. Depending on the size of your image that could take some time.

The relevant functions in `index.js` are `Jimp.prototype.write` and `Jimp.prototype.getBuffer`: https://github.com/oliver-moran/jimp/blob/master/index.js

**Comment by marcolino** [comment]
I did check that functions, and I did not find any performance issue... I was debugging *my* usage of image.write, since probably the slowness cause  was not in jimp... After that I did change the structure of my code, and that problem didn't happen any more... :-)

**Comment by oliver-moran** [comment]
Happy days. Thanks!
