### ISSUE TITLE
Angular App not working on Firefox and Safari when using JIMP

### ISSUE THREAD

**Issue by FloMueh** [oliver-moran/jimp#836]
# App should start with each browser. 

The App should start without any problems with Chrome, Safari and Firefox

# Currently its just working with google chrome

Its just working with Google Chrome. On other browsers i get the following error message.

# Failure Information (for bugs)
The whole angular application is not loading / starting. 

## Steps to Reproduce
Well, i am using angular version 8.2.* combined with zone 0.9.1 and jimp 0.9.3
After hours of trying i found out that everything is working well when i am using jimp in version 0.8.0. I tried it once with 0.8.3 there was the same error.

I cant change the order of the loading modules. I tried to move the import from polyfill into the main.ts. Its not working as well.

I cant add a code example cause the code belongs to a company. I wanna use jimp in the future. hopefully this bug is fixed some days. I found similar issues by using another library like exceljs. Maybe this helps you.

- Jimp Version: 0.9.3
- Operating System: Mac Os Catalena
- Node version: 13.2

## Context package.json dependencies

"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "8.2.3",
    "@angular/material-moment-adapter": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@ngrx/store": "^8.5.2",
    "@sentry/browser": "^5.9.1",
    "ag-grid-angular": "^19.1.2",
    "ag-grid-community": "^19.1.4",
    "ag-grid-enterprise": "^19.1.4",
    "aws-amplify": "^1.2.4",
    "aws-amplify-angular": "^2.1.12",
    "aws-sdk": "^2.581.0",
    "bootstrap": "^4.4.1",
    "chart.js": "^2.9.3",
    "core-js": "^2.6.10",
    "crypto-js": "^3.1.9-1",
    "file-saver": "^1.3.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "idb": "^4.0.4",
    "jimp": "^0.8.0",
    "leaflet": "^1.6.0",
    "moment": "^2.24.0",
    "ng-pick-datetime": "^7.0.0",
    "ngx-device-detector": "^1.3.20",
    "ngx-gallery": "^5.10.0",
    "ngx-webstorage": "^3.0.2",
    "ppsharedlibrary": "0.0.16",
    "primeicons": "^1.0.0",
    "primeng": "^6.1.7",
    "quill": "^1.3.7",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.3",
    "tslib": "^1.10.0",
    "uuid": "^3.3.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular-devkit/schematics": "^7.3.9",
    "@angular/cli": "^8.3.20",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@sentry/types": "^5.7.1",
    "@types/chart.js": "^2.9.2",
    "@types/crypto-js": "^3.1.43",
    "@types/file-saver": "^1.3.0",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/jimp": "^0.2.28",
    "@types/leaflet": "^1.5.5",
    "@types/node": "^10.17.6",
    "codelyzer": "^5.0.1",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-teamcity-reporter": "^1.1.0",
    "pdfreader": "^1.0.6",
    "prettier": "^1.19.1",
    "protractor": "^5.4.2",
    "protractor-video-reporter": "^0.3.0",
    "ts-node": "^4.1.0",
    "tslint": "~5.9.1",
    "typescript": "3.5.3"
  }

## Failure Logs
Error: Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)
assertZonePatched — zone-evergreen.js:52
NgZone — core.js:39457
getNgZone — core.js:40708
bootstrapModuleFactory — core.js:40523
(anonyme Funktion) — jimp.js:14817

**Comment by mochicode** [comment]
@FloMueh I had the same issue a couple of days ago.
You have to import zone,js after your application code.

```JavaScript
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

// move zone.js from polyfills to main.ts
require('zone.js/dist/zone');

if (environment.production) {
    enableProdMode();
}

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by FloMueh** [comment]
@mochicode thanks for your response but this was not working for me. 

However, the new version of jimp 0.10.2 fixes this issue for me!
