### ISSUE TITLE
read from input type="file"

### ISSUE THREAD

**Issue by NookieGrey** [oliver-moran/jimp#842]
Is it any way to read from input type="file" event.target.files[0] ?

**Comment by ninaandcam** [comment]
```Jimp.read()``` optionally accepts a ```Buffer``` instead of a path string as the first parameter. Getting a ```Buffer``` seems to be a two-step process:

1. Use ```FileReader.readAsArrayBuffer(event.target.files[0])```
2. Use ```new Uint8Array(arrayBuffer)```

See [this SO post](https://stackoverflow.com/questions/32556664/getting-byte-array-through-input-type-file/32556944)) for a full example.

**Comment by NookieGrey** [comment]
great thank, work with 1. step

**Comment by avichal-neweradeveloper** [comment]
can you explain 1 and 2 what is FileReader.readAsArrayBuffer

**Comment by NookieGrey** [comment]
This is vanilla js
https://developer.mozilla.org/docs/Web/API/FileReader/readAsArrayBuffer

**Comment by alclimb** [comment]
The following typescript works fine in browsers:

```ts
/**
 * files: List of files from HTML5 input or drop.
 */
async function read(files: FileList) {
  // Convert to ArrayBuffer format.
  const arrayBuffer = await files[0].arrayBuffer();

  // Read ArrayBuffer with Jimp ("any" to avoid type errors)
  const img = await Jimp.read(arrayBuffer as any);
}
```
