### ISSUE TITLE
Image is resized down and gets bigger file size

### ISSUE THREAD

**Issue by nirber** [oliver-moran/jimp#85]
```javascript
Jimp.read(file.buffer, function (err, image) {
    image
      .resize(SmallerWidth, Jimp.AUTO)
      .getBuffer(Jimp.MIME_JPEG, function(err, buffer){
        s3Upload(buffer);
      });
 });
```

New smaller image has larger file size (in some cases even 4 times larger).

**Comment by skoa-h** [comment]
I don't think this is a bug, because the default quality setting for jpg is 100%, so there is almost no loss even if the source image had a e.g. 60% encoding. JPGs are always reencoded.

**Comment by oliver-moran** [comment]
@skoa-h is correct. The default quality for JPEGs is 100. You should set this to something lower to gain compression:

```javascript
Jimp.read(file.buffer, function (err, image) {
    image
      .resize(SmallerWidth, Jimp.AUTO)
      .quality(60) // set the quality for JPEGs
      .getBuffer(Jimp.MIME_JPEG, function(err, buffer){
        s3Upload(buffer);
      });
 });
```

**Comment by nirber** [comment]
Alright, thanks!

**Comment by CapnSpellcheck** [comment]
@oliver-moran Is there a way to set this globally on Jimp so that it doesn't need to be fiddled with on each image? I consider it very bad that there's no way to change that default.
