### ISSUE TITLE
TS error `Type '"constants"' cannot be used to index type 'T' (2536) when consuming .d.ts

### ISSUE THREAD

**Issue by peterblazejewicz** [oliver-moran/jimp#853]
I'm writing 3rd part TypeScript/Definition file that consumes Jimp (this part works marvelously):
```ts
import mergeImg from 'merge-img';
import { resolve } from 'path';
import Jimp from 'jimp';

const fixturePath = resolve(__dirname, 'fixtures');

mergeImg(['image-1.png', 'image-2.jpg']).then(img => {
    // Save image as file
    img.write('out.png', () => console.log('done'));
});
```
```ts
export default function mergeImg(
    images: Array<string | ImageDescriptor | Buffer | Jimp>,
    options?: Options,
): Promise<Jimp>;
```
I cannot see the outcome of the adding TS support as the tsc tooling complains:
```bash
Error: Errors in typescript@next for external dependencies:
node_modules/@jimp/core/types/utils.d.ts(16,3): error TS2536: Type '"class"' cannot be used to index type 'T'.
node_modules/@jimp/core/types/utils.d.ts(17,3): error TS2536: Type '"constants"' cannot be used to index type 'T'.
```
Relevant `jimp` def type:
```ts
export type WellFormedValues<T extends any> = 
  T['class'] &
  T['constants'];
```
https://www.google.com/search?q=typescript+TS2536&oq=typescript+TS2536&aqs=chrome..69i57.1779j0j1&sourceid=chrome&ie=UTF-8

Shoudl this one be changed by restructuring consuming code? Or there in the upstream source?

Thanks folks!

**Comment by crutchcorn** [comment]
Thanks for raising this issue! Sorry for missing it beforehand 😅 This should be fixed in #858

**Comment by crutchcorn** [comment]
@hipstersmoothie think we can close this issue out now?

**Comment by hipstersmoothie** [comment]
@peterblazejewicz if you could verify this is fixed and close this issue I would appreciate it!
