### ISSUE TITLE
Multiple layers

### ISSUE THREAD

**Issue by haydenbleasel** [oliver-moran/jimp#87]
Hello, I'm not sure exactly what to ask or whether Jimp has the capacity, but is it possible to create an `.ico` file with multiple sizes (typically `16x16`, `32x32`, `64x64`, etc)?

**Comment by skoa-h** [comment]
Hi,

currently there is no support for the .ico file format and I don't know if there are plans to add support.

**Comment by jaydenseric** [comment]
I too would *really* like to see a pure Node tool for creating multi-layered `favicon.ico` files from `.png`. I just added links to the Microsoft `.ico` spec along with some implimentations in other languages in the [Iwip "ICO support" issue](https://github.com/EyalAr/lwip/issues/38#issuecomment-172167542).

**Comment by haydenbleasel** [comment]
Okay, if that's the case I'll get this off the Jimp repo. @jaydenseric Let me know if you ever find or create a module that does that, we'll all be in your debt haha.
