### ISSUE TITLE
Color profiling issue

### ISSUE THREAD

**Issue by canvasmanager** [oliver-moran/jimp#88]
I have ran Jimp resize on this image
![jimp_issue-orig](https://cloud.githubusercontent.com/assets/11734952/12271932/a95d4f6c-b983-11e5-9b41-031613ae61bf.jpg)

The image got converted into this one:

![jimp_issue](https://cloud.githubusercontent.com/assets/11734952/12271962/c629e556-b983-11e5-8bc9-1f4a83eff596.jpg)

**Comment by skoa-h** [comment]
Hi, 

your source jpg is CMYK colortype, jimp and the underlying pngjs only support RGB and RGBA colortype. I don't know, if there are plans to support additional colortypes.

**Comment by canvasmanager** [comment]
Hi Skoah,

Do you know any package which is good for ascertaining the Color Space "CMYK". I tried multiple options but none works consistently. I don't want to install any package like GM. If it is some JS only package, it should be good.

Thankyou,
Manik Mittal

**Comment by skoa-h** [comment]
Hi Manik,

There is color-js, which I never used but it does not support cmyk I think.

I don't think there is a good solution but Graphics-/ImageMagick for color space conversion and color profile management / conversion, at least not JS-only.

Regards
Skoah

**Comment by oliver-moran** [comment]
Yes. Looks like colour space is the culprit again. But this issue is stark compared to here: https://github.com/oliver-moran/jimp/issues/84

The best place to deal with this is at the jpeg-js library, which does the reading/writing of JPEGs (Jimp just pushes pixels around): https://github.com/eugeneware/jpeg-js

**Comment by canvasmanager** [comment]
Hi Oliver / Skoah,

I got an interim solution to it. I used npm package sharp (https://www.npmjs.com/package/sharp) to extract the color space data. I am not Jimping the images with color space "CMYK".

I have raised the issue with jpeg-js library as well https://github.com/eugeneware/jpeg-js/issues/13 

Thanks for your help. Truly appreciate.

**Comment by skoa-h** [comment]
Hi Manik,

good to see that you found a solution. Maybe in the future there is a pure js solution for this.

Regards
Skoah

**Comment by strandedcity** [comment]
I've submitted a pull request that fixes this issue in jpeg-js. I used a smaller version of your image (which displays the same behavior in jimp right now) as one of the test cases there.

If you want to test it yourself before that PR gets merged and released, and then jimp has another release cycle, you can play with it by making this change to your own local dependency:

https://github.com/eugeneware/jpeg-js/pull/16/files#diff-f8ef8b8e3a0bcafb6e68ba4a7051a503

If you're curious to try it on the web, I've built the browser demo of jimp with that change. Yesterday, your test image looked like a black rectangle. Today, it works!

Yesterday:
![image](https://cloud.githubusercontent.com/assets/1693906/14588239/fd9199c2-0478-11e6-9a4a-18059c5a853f.png)

Today:
![image](https://cloud.githubusercontent.com/assets/1693906/14588737/58b57d9e-0485-11e6-90bc-540feb699472.png)


http://strandedcity.github.io/jimp/browser/

**Comment by canvas-manik** [comment]
Thankyou Stranded City for your help. This is a great improvement. 

Can we have a solution for Image colors getting lost as well.

**Comment by strandedcity** [comment]
You mean color profiles? That's harder.

The black and white image there is just part of the web-browser demo. The image is read into Jimp in full CMYK. If you modify your local copy of jpeg-js according to https://github.com/eugeneware/jpeg-js/pull/16/files#diff-f8ef8b8e3a0bcafb6e68ba4a7051a503, Jimp will work with CMYK jpegs.

**Comment by strandedcity** [comment]
Fixed as of https://github.com/oliver-moran/jimp/pull/125 by including https://github.com/eugeneware/jpeg-js/pull/16

@canvasmanager can you re-run your test with current code (v0.2.22) and let me know if you still see any issues?

**Comment by oliver-moran** [comment]
Happy days. This will be in the next release. Thanks all!
