### ISSUE TITLE
Preserve Exif Data

### ISSUE THREAD

**Issue by molipha** [oliver-moran/jimp#89]
Hi,

I just tried rotating an image and see that the resulting image is without exif data. Is there a way to preserve exif data?

Thanks

**Comment by oliver-moran** [comment]
At the moment, Jimp blows away all exif data. This is because every image is treated as a brand new bitmap. No objection to support being added though or adding it to a roadmap.

**Comment by hipstersmoothie** [comment]
https://github.com/eugeneware/jpeg-js/issues/44
https://github.com/photopea/UTIF.js/issues/36

Keeping track of the orientation after rotations might be hard

**Comment by photopea** [comment]
Guys, images are not a place to store text. Just add a text file next to your image, or put it inside a file name (in your file system).

**Comment by hipstersmoothie** [comment]
@photopea that's not the point. Both JPEG and TIFF support EXIF data. The images we are processing start out with exif data. we should be able to keep that data in the image. Also this doesn't look like text to me


```json
{ "orientation": 1 }
```

It's metadata about the image. It makes no sense to just store it in a text file. As a user I would be confused if my image processing library started producing text files randomly

**Comment by hipstersmoothie** [comment]
closing in favor of #556
