### ISSUE TITLE
Implement the Node.js callback pattern

### ISSUE THREAD

**Issue by beny78** [oliver-moran/jimp#9]
Instead of return "this" in each method, you should implement the Node.js callback pattern "function(err, result)"
In this case it will be easy to use promise and have async task.

ex:
var jimb = new Jimb(buffer, "image/png");
return Q.nfcall(jimb.resize, 200, 200).then(function(image){
    return Q.nfcall(jimb.toBuffer, image, "image/png").then(function(buffer){
        //And do what you want
    });
});

**Comment by HarleyKwyn** [comment]
I realized you've ignored this, but I think it'd make this a much more compelling library. :+1: It's difficult to do this nicely with async tasks.

**Comment by oliver-moran** [comment]
Hi Harley,

Not ignoring you - promise! And I agree. The pattern isn't the most elegant right now.

Bit busy IRL - but will set aside some hours this week to catch up on this project since it seems to have taken people's imagination.

**Comment by HarleyKwyn** [comment]
Yeah, I know that feeling, no worries! This part of the project has been delayed to similar inconsistencies in the code base I inherited. I appreciate your responsiveness :)

**Comment by oliver-moran** [comment]
Good news, Harley. I've started work on this. Not as bad as I thought and can remain backwards compatible. Should be ready this weekend.

**Comment by HarleyKwyn** [comment]
Yaaaay! That's awesome. :D thanks.

**Comment by oliver-moran** [comment]
Done. A bit more testing then I'll do a release.

**Comment by HarleyKwyn** [comment]
W00+
