### ISSUE TITLE
Promise based write/getBuffer

### ISSUE THREAD

**Issue by Vanuan** [oliver-moran/jimp#90]
Currently, write needs callback.
I'd like to be able to do this:

```
image.getBuffer(Jimp.MIME_JPEG).then(function(buffer) {
  res.writeHead(200, {
     'Content-Type': Jimp.MIME_JPEG,
     'Content-Length': buffer.length
   });
   res.end(buffer);
})
```

**Comment by gabrielalan** [comment]
+1

**Comment by oliver-moran** [comment]
It's a little bit awkward because methods, `write` and `getBuffer`, are currently designed for chaining, like this:

```js
image.scale(0.5).write("image-small.jpg").greyscale()..write("image-small-greyscale.jpg");
```

**Comment by efernandesng** [comment]
@oliver-moran  [node-horseman](https://github.com/johntitus/node-horseman/) has a good chaining strategy. It use [bluebird](http://bluebirdjs.com/docs/getting-started.html) as Promise implementation.

You can continue using callbacks through the bluebird [`.asCallback`](http://bluebirdjs.com/docs/api/ascallback.html).

**Comment by oliver-moran** [comment]
@efernandesng, thanks and apologies for delay getting back. I'll look into this for the release after next.

**Comment by ryuken** [comment]
Any progress on this?

**Comment by thisconnect** [comment]
I'd love native Promises for all jimp methods. Bluebird should not be included by default, it could be used opt-in. Chaning the API requires the test https://github.com/oliver-moran/jimp/issues/227 to be implemented first

**Comment by AshwinMekala** [comment]
Any progress on this?

**Comment by majiy** [comment]
As a workaround for the time being, using Bluebird promisify:

```
const bluebird = require('bluebird');
const jimp = require('jimp');
jimp.prototype.getBufferAsync = bluebird.promisify( jimp.prototype.getBuffer );
```

**Comment by ilyaLibin** [comment]
Node 8, has built in `promisify` method

const bluebird = require('util');
const jimp = require('jimp');
jimp.prototype.getBufferAsync = util.promisify( jimp.prototype.getBuffer );

**Comment by SourceBoy** [comment]
For >= ES6, native Promise is available:
```
(new Promise((resolve) => {
  <img>.getBuffer(<mime>, resolve);
})).then((buf) => {
  // Do something with buffer
})
```

**Comment by FireController1847** [comment]
Using promisify now results in a "cannot read property 'width' of undefined". Any status on making this a promise?

**Comment by webarthur** [comment]
+1

**Comment by septs** [comment]
@FireController1847 
```typescript
import { promisify } from "util";

const jimp = new Jimp(100, 100); // jimp object
const boundGetBuffer = promisify(jimp.getBuffer.bind(jimp));

async main() {
   const buffer = await boundGetBuffer();
}
main();
```
see https://mdn.io/bind
see https://nodejs.org/dist/latest/docs/api/util.html#util_util_promisify_original

**Comment by FireController1847** [comment]
I had actually been doing it wrong and got it to work lol, thanks anyways
