### ISSUE TITLE
Can't resize .gif

### ISSUE THREAD

**Issue by 2JJ1** [oliver-moran/jimp#901]
# Expected Behavior

#.resize() to work on .gif file types. My .gif dimensions of 1000x1500 pixels should resize to 160x160 pixels.

# Current Behavior

Saving the resize results in a 0-byte sized file. There is a file, but no data. 

## Steps to Reproduce

```
await jimp.read("filename.gif")
			.then(file => {
				return file
				.resize(160, 160) // resize
				.write("filename.gif"); // save
			})
```

## Context

There are no issues with using a .jpg or .png file. The issue only occurs for .gif, which is supported according to README.md. This issue occurs for any .gif file pulled from Google.

- Jimp Version: 0.13.0
- Operating System: Windows 10 Home
- Node version: 12.15.0

## Failure Logs
None

**Comment by 2JJ1** [comment]
I now see that resizing with keeping the same dimension ratio will work without issue. 
`resize(160, jimp.AUTO)`

I still think it might be a bug that resizing into a new ratio does causes an unexpected effect.

**Comment by hipstersmoothie** [comment]
GIF is definitely one of the less supported image types in jimp. If there are any improvements you can see contributions are welcome!

If I were you I would try out https://www.npmjs.com/package/gifwrap
