### ISSUE TITLE
Use Buffer.isBuffer to check whether an object is a buffer

### ISSUE THREAD

**Issue by Vanuan** [oliver-moran/jimp#91]
I used this great library along with node-canvas. Unfortunately, `canvas.toBuffer()` returns `SlowBuffer`. So jimp doesn't accept it.

See also https://github.com/Automattic/node-canvas/issues/711

**Comment by oliver-moran** [comment]
Untested. But StackOverflow suggests converting from `SlowBuffer` to `Buffer` is trivial:

```js
var f = function(slowBuffer) {
  var buffer = new Buffer(slowBuffer.length);
  slowBuffer.copy(buffer);
  return buffer;
}
```

From: http://stackoverflow.com/questions/14009048/what-makes-node-js-slowbuffers-slow
