### ISSUE TITLE
There is any way to draw?

### ISSUE THREAD

**Issue by aronrodrigues** [oliver-moran/jimp#92]
I need to generate a badge, so I need to draw circles, squares, lines and write names and numbers.

Is it possible?

**Comment by Igor1201** [comment]
+1
I was using [canvas](https://github.com/Automattic/node-canvas), but it relies on `cairo`, which is a hell to maintain on docker or similar.

**Comment by NoPinky** [comment]
I think you will have to implement your own routines based on the low level manipulation of each pixel that is offered within this library

**Comment by oliver-moran** [comment]
@NoPinky is correct. Currently there are not "drawing" methods but you can manipulate each pixel. But anyone willing to write a drawing API is welcome to make a pull request!
