### ISSUE TITLE
Documentation incorrect for measureText

### ISSUE THREAD

**Issue by manolan1** [oliver-moran/jimp#921]
# Expected Behavior

Correct documentation

# Current Behavior

Incorrect documentation

The code snippet looks like this:
```js
Jimp.measureText(Jimp.FONT_SANS_32_BLACK, 'Some string'); // width of text
Jimp.measureTextHeight(Jimp.FONT_SANS_32_BLACK, 'Some string', 100); // height of text
```

But the font required for these methods is not a font name, it is a loaded font. I think you could just replace `Jimp.FONT_SANS_32_BLACK` with `font`, but if you want a complete example, you need the promise code from the previous code example.

## Steps to Reproduce

1. Read the documents
2. Try to use the example for measureText
3. Find it doesn't work

**Screenshots**
N/A

## Context

N/A

- Jimp Version: 0.14.0
- Operating System: N/A
- Node version: N/A

## Failure Logs

N/A

**Comment by konradgoldammer** [comment]
The correct way would be:

`Jimp.measureText((await Jimp.loadFont(Jimp.FONT_SANS_32_BLACK)), 'Some string'); // width of text
Jimp.measureTextHeight((await Jimp.loadFont(Jimp.FONT_SANS_32_BLACK)), 'Some string', 100); // height of text`
(in an async function of course)

Just in case anyone else is stuck here.
