### ISSUE TITLE
use jimp with react native

### ISSUE THREAD

**Issue by parice02** [oliver-moran/jimp#986]
**Is your feature request related to a problem? Please describe.**
When I install Jimp in my native react app I get errors like Unable to resolve module `fs` from ... or Unable to resolve module `path` from ...
Isn't Jimp compatible with react native?

Thank you!

**Comment by valerioleo** [comment]
I bumped into the same error. Downgrading to `0.14.0` fixed the issue, but looking into the source code both `0.14.0` and `>0.16.0` make use of `path` and `fs` in their index file https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js.

So I can't really tell why downgrading worked, unfortunately. I hope it helps anyway!

**Comment by parice02** [comment]
> I bumped into the same error. Downgrading to `0.14.0` fixed the issue, but looking into the source code both `0.14.0` and `>0.16.0` make use of `path` and `fs` in their index file https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js.
> 
> So I can't really tell why downgrading worked, unfortunately. I hope it helps anyway!

Hi. It really helped me. But now i'm getting this warning:

`Possible Unhandled Promise Rejection (id: 1):
Event {
  "isTrusted": false,
  "methodName": "constructor",
}`

Thank you!!

**Comment by parice02** [comment]
> > I bumped into the same error. Downgrading to `0.14.0` fixed the issue, but looking into the source code both `0.14.0` and `>0.16.0` make use of `path` and `fs` in their index file https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js.
> > So I can't really tell why downgrading worked, unfortunately. I hope it helps anyway!
> 
> Hi. It really helped me. But now i'm getting this warning:
> 
> `Possible Unhandled Promise Rejection (id: 1): Event { "isTrusted": false, "methodName": "constructor", }`
> 
> Thank you!!

I get this error on Android but not on iPhone. 
It seems to me that the playback is going smoothly on iPhone.

**Comment by z2043947** [comment]
> > > I bumped into the same error. Downgrading to `0.14.0` fixed the issue, but looking into the source code both `0.14.0` and `>0.16.0` make use of `path` and `fs` in their index file https://github.com/oliver-moran/jimp/blob/master/packages/core/src/index.js.
> > > So I can't really tell why downgrading worked, unfortunately. I hope it helps anyway!
> > 
> > 
> > Hi. It really helped me. But now i'm getting this warning:
> > `Possible Unhandled Promise Rejection (id: 1): Event { "isTrusted": false, "methodName": "constructor", }`
> > Thank you!!
> 
> I get this error on Android but not on iPhone.
> It seems to me that the playback is going smoothly on iPhone.

Hi 
Did you find a solution for the rejection?
